### ISSUE TITLE
Trying to install dependency binaries raises unhandled error if they don't exist

### ISSUE THREAD

**Issue by Phidica** [pipxproject/pipx#107]
I'm using pipx 0.12.3.3, and trying to test the `setup.py` of a local package I'm developing. My package does not provide any binaries or scripts, so pipx refuses to install it if I simply pass `install --spec <path> <name>`. I'm sure that's a feature, but it inconveniences me. I tried to work around it by passing the `--include-deps` option, even though the one dependency of my package *also* provides no binaries or scripts. Here is the trace:

```
$ pipx install --spec <path/to/my/package> --include-deps <name>
  installed package <name>
Traceback (most recent call last):
  File "<snip>/.local/bin/pipx", line 10, in <module>
    sys.exit(cli())
  File "<snip>/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "<snip>/pipx/main.py", line 157, in run_pipx_command
    include_deps=args.include_deps,
  File "<snip>/pipx/commands.py", line 318, in install
    _run_post_install_actions(venv, package, local_bin_dir, venv_dir, include_deps)
  File "<snip>/pipx/commands.py", line 352, in _run_post_install_actions
    random_binary_name = metadata.binaries_of_dependencies[0]
IndexError: list index out of range
```

I believe this issue arises because pipx assumes that `metadata.binaries_of_dependencies` will exist, when in fact in this scenario it does not.

**Comment by cs01** [comment]
I believe this has been fixed in a later version.

**Comment by Phidica** [comment]
This still happens with 0.13.1.0

**Comment by cs01** [comment]
Thanks for letting me know, I will look into it.
