### ISSUE TITLE
what am I doing wrong?

### ISSUE THREAD

**Issue by Laurentiu-Andronache** [pipxproject/pipx#111]
```cmd
C:\>pipx install pyjokes
  installed package pyjokes 0.5.0, Python 3.7.2
  These binaries are now globally available
    - pyjoke
    - pyjokes
  Note: 'C:\\Users\\Nebu\\.local\\bin' is not on your PATH environment variable. These binaries will not be globally accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it, or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).
done!

C:\>pipx run pyjoke
Assuming binary is 'pyjoke.exe' (Windows only)
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Nebu\AppData\Local\Temp\pip-install-yygzrenk\nltk\
'C:\\Users\\Nebu\\.local\\pipx\\.cache\\8c2f5730a463fd9\\Scripts\\python.exe -m pip install pyjoke -q' failed

C:\>pyjoke
'pyjoke' is not recognized as an internal or external command,
operable program or batch file.

C:\>pip list
Package    Version  Location
---------- -------- --------------------------------
pip        19.0.3
pipx       0.12.3.2 c:\projects\python\_helping\pipx
setuptools 40.8.0
wheel      0.33.1

C:\>pipx list
venvs are in C:\Users\Nebu\.local\pipx\venvs
binaries are exposed on your $PATH at C:\Users\Nebu\.local\bin
   package pyjokes 0.5.0, Python 3.7.2
    - pyjoke
    - pyjokes

C:\>pipx --version
0.12.3.2

C:\>
```

**Comment by Laurentiu-Andronache** [comment]
This is a lie btw:

> 'C:\\Users\\Nebu\\.local\\bin' is not on your PATH environment variable.

**Comment by Laurentiu-Andronache** [comment]
And regarding `pipx run ...`.... why did it take so long creating venv again? Couldn't it detect that pyjoke was already installed in a venv?

**Comment by Laurentiu-Andronache** [comment]
I think it didn't install an exe for me:
```cmd
C:\>pipx ensurepath
Your PATH looks like it already is set up for pipx. Pass `--force` to modify the PATH.

C:\>Users\Nebu\.local\bin\pyjoke
'Users\Nebu\.local\bin\pyjoke' is not recognized as an internal or external command,
operable program or batch file.

C:\>Users\Nebu\.local\bin\pyjoke.exe
'Users\Nebu\.local\bin\pyjoke.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\>Users\Nebu\.local\bin\pyjoke.exe
'Users\Nebu\.local\bin\pyjoke.exe' is not recognized as an internal or external command,
operable program or batch file.

C:\>dir Users\Nebu\.local\bin\
 Volume in drive C is Windows
 Volume Serial Number is 4496-9AD4

 Directory of C:\Users\Nebu\.local\bin

03/17/2019  02:26 PM    <DIR>          .
03/17/2019  02:26 PM    <DIR>          ..
03/17/2019  02:26 PM             1,250 pyjoke
03/17/2019  02:26 PM               184 pyjokes
               2 File(s)          1,434 bytes
               2 Dir(s)  13,409,476,608 bytes free
```

**Comment by cs01** [comment]
On Ubuntu, I was able to install pyjokes with

```
pipx install pyjokes
```

and run `pyjoke` from the commandline. @sahensley would you mind trying to install and run `pyjokes` on a windows machine to test if there was a regression in pipx? 

> And regarding pipx run ....... why did it take so long creating venv again? Couldn't it detect that pyjoke was already installed in a venv?

`pipx run` does not look for or reuse environments from `pipx install`. It **does** reuse environments from previous invocations of `pipx run` though. So if you run `pipx run --spec=pyjokes pyjoke` twice, the first time will take a while, and the second will be quick, regardless of whether you have already run `pipx install pyjokes` or not.

**Comment by sahensley** [comment]
Sure thing.  I get the same results as above on Windows while using both pipx and a standard venv. It's not a `pipx` issue but a `pyjokes` packaging issue.

It looks like the [setup.py file](https://github.com/pyjokes/pyjokes/blob/d4f317e644611ebc607a5c7ae5ec040e3504452e/setup.py#L43) is using the legacy _scripts_ keyword instead of _entry\_points_ with _console\_scripts_.  That's why .exes aren't being generated on the Windows install.

The [automatic script creation](https://setuptools.readthedocs.io/en/latest/setuptools.html?#automatic-script-creation) section of the setuptools docs has the details.

**Comment by Laurentiu-Andronache** [comment]
Thanks, you're both awesome. The pyjokes dude said he'll push a new version with a fix when he gets a chance.
