### ISSUE TITLE
Docs on pypi have internal links that don't work

### ISSUE THREAD

**Issue by Wooble** [pipxproject/pipx#114]
The 2 links in "For comparison to pipsi, see how does this compare to pipsi? and migrating to pipx from pipsi" in the readme on pypi don't work, because pypi strips out the anchor tags in the real docs.

(I have no idea if this can actually be made to link correctly within pypi, but having the links show up there when they're not going to go anywhere is a bit confusing.)

**Comment by sahensley** [comment]
It appears this is a limitation of the PyPI handling of long_description.  Here's a [feature request](https://github.com/pypa/warehouse/issues/4064) with more information.

**Comment by cs01** [comment]
Nice research, @sahensley  :smile: Thank you for sharing.

Sort of a meta-question, but here goes: do people browse PyPI? I personally *never* search PyPI or read documentation on PyPI. I would be fine just replacing the README on PyPI with a pointer to the github README. Maybe that is just my bias though. Anyone thoughts?

**Comment by sahensley** [comment]
I'll occasionally take a look on PyPI to get a quick overview of a project's maintainers, a link to the homepage, the project's license and review the release history.  My overall goal is to quickly check if a project is still maintained and what license it uses.

**Comment by itsayellow** [comment]
This seems to be fixed with the current pypi pipx README.
