### ISSUE TITLE
Running pipx install  --editable may result in errors `No binaries associated with package`

### ISSUE THREAD

**Issue by skoneka** [pipxproject/pipx#126]
Hi, this is an issue I encountered with pipx 0.12.3.3 installed through pip (anaconda).
When installing a package as  editable pipx fails in my case:
```# pipx install --spec=. package_in_dev --editable --force```

```No binaries associated with package package_in_dev. Try again with '--include-deps' to include binaries of dependent packages.```

After that package_in_dev.egg-info directory is left laying around. Subsequent pipx  runs without `--editable` (pipx install --spec=. package_in_dev --force) will fail  with error ```No binaries associated with package package_in_dev. Try again with '--include-deps' to include binaries of dependent packages.``` until egg-info directory is deleted.

**Comment by cs01** [comment]
Can you run this with the `--verbose` flag and share the output?

**Comment by itsayellow** [comment]
Closing because of age and no response from OP.  Reopen if you still have issues with a recent version of pipx.
