### ISSUE TITLE
cowsay screencast doesn't work

### ISSUE THREAD

**Issue by jaraco** [pipxproject/pipx#128]
While getting to know pipx, I first observed the screencast in the readme, which shows the user running 'pipx install cowsay' and 'pipx run cowsay'. When I tried the same commands, I got errors:

```
~ $ pipx install cowsay                                                                                                                                                        
No binaries associated with package cowsay. 
```

Reading further into the readme, I see the package is 'pycowsay'. It would be nice if the screencast were updated to include pycowsay.

**Comment by cs01** [comment]
Thanks for reporting! The cowsay PyPI package was reverted without my knowledge. I just pushed an update to it (v2.0.3) that should work fine, just like the screencast.

**Comment by jaraco** [comment]
And I can confirm the command now works as expected. Thanks!
