### ISSUE TITLE
in tests, FileNotFoundError: No such file or directory black

### ISSUE THREAD

**Issue by jaraco** [pipxproject/pipx#130]
When I run the tests on master, I get this error:

```
======================================================================
ERROR: test_static (tests.test_pipx.PipxStaticTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jaraco/code/public/pipx/tests/test_pipx.py", line 29, in test_static
    self.run_cmd(["black", "--check"] + files)
  File "/Users/jaraco/code/public/pipx/tests/test_pipx.py", line 22, in run_cmd
    rc = subprocess.run(cmd).returncode
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'black': 'black'

----------------------------------------------------------------------
```

I see that `black` is declared as an requirement, but I don't see anything in the repository to orchestrate the installation and execution of the tests.

Perhaps the project should consider adopting [tox](/tox-dev/tox) to orchestrate the tests.

**Comment by cs01** [comment]
Did you follow the instructions in the readme? https://github.com/pipxproject/pipx#contributing

I've heard a lot about tox but never used it. Would be nice to adopt, but for now my test set up works fine, other than the fact that it must be run locally and doesn't work on Travis (maybe it will work on another CI system?). 

If you think tox would make things easier I would be open to a pull request, but don't have the time or sufficient motivation to take that on myself.

**Comment by cs01** [comment]
The tox PR fixes t his
