### ISSUE TITLE
Running test suite installs pipx into system python

### ISSUE THREAD

**Issue by jaraco** [pipxproject/pipx#132]
Simply running `python setup.py test` in the repository causes `.` to be installed to the system site packages. That's unexpected and undesirable.

**Comment by cs01** [comment]
If you follow the instructions in the readme this will not happen. https://github.com/pipxproject/pipx#contributing

**Comment by jaraco** [comment]
I was unaware of the instructions. Unfortunately, I can't follow those instructions as they assume a virtualenv workflow that [doesn't play well with xonsh](https://xon.sh/python_virtual_environments.html). The instructions are also Unix-specific. A tox-based workflow should be compatible with other shells and platforms.
