### ISSUE TITLE
inject --include-binaries on a package without binaries will remove already-existing binaries

### ISSUE THREAD

**Issue by apnewberry** [pipxproject/pipx#137]
Using `inject --include-binaries original new` on a `new` package that doesn't have binaries will remove the existing binaries from PATH.

```
# Create a virtualenv with ipython binary
pipx install ipython
# Add black binary to the virtualenv
pipx inject --include-binaries ipython black
which black
# Add toolz to the virtualenv, even though it doesn't have a binary
pipx inject --include-binaries ipython toolz 
# Black is now missing
which black
```

I do this `--inject-binaries` even for packages that don't have binaries because I like to have a main virtualenv with most of my things in it. I want to run a single command to get everything I need. Since pipx doesn't yet support a single command to get multiple things, I'm splitting it into two. 

```
pipx install ipython
pipx inject  --include-binaries ipython toolz pytest attrs
```

**Comment by cs01** [comment]
Thank you for reporting and following up. The reproduction was straightforward thanks to your code block. This has been fixed in 0.13.1.0.
