### ISSUE TITLE
Some executables not linked during pipx install

### ISSUE THREAD

**Issue by elgertam** [pipxproject/pipx#143]
`pipx install` is not finding all executables for certain packages.

For example, here is what happened when I tried to install `jupyter` using `pipx`: 

```bash
$ pipx install jupyter --include-deps
  installed package jupyter 1.0.0, Python 3.7.3
  These binaries are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-trust
done! ✨ 🌟 ✨
$ 
$ 
$ jupyter
-bash: jupyter: command not found
$ which jupyter
$ 
$ cd ~/.local/bin
$ ls *jupyter*
jupyter-bundlerextension jupyter-nbconvert        jupyter-run
jupyter-console          jupyter-nbextension      jupyter-serverextension
jupyter-kernel           jupyter-notebook         jupyter-trust
jupyter-kernelspec       jupyter-qtconsole
$ # Looking in ~/.local/bin, none found.
$ 
$ cd ~/.local/pipx/venvs/jupyter/bin/
$ ls *jupyter*
jupyter                  jupyter-migrate          jupyter-run
jupyter-bundlerextension jupyter-nbconvert        jupyter-serverextension
jupyter-console          jupyter-nbextension      jupyter-troubleshoot
jupyter-kernel           jupyter-notebook         jupyter-trust
jupyter-kernelspec       jupyter-qtconsole
$ # Looking in ~/.local/pipx/venvs/jupyter/bin. Expected no `jupyter` executable;
$ # found `jupyter` executable, as well as `jupyter-migrate` and
$ # `jupyter-troubleshoot`, none of which were not found in ~/.local/bin.
```

According to the [readme's "How it Works"](https://github.com/pipxproject/pipx#how-it-works) section, `pipx install` scans the new virtualenv's bin/ directory, then links found executables into ~/.local/bin.

Further, output included in a comment from a [previous issue](https://github.com/pipxproject/pipx/issues/18#issuecomment-466693193) indicates that `pipx` properly linked `jupyter`, `jupyter-migrate` and `jupyter-troubleshoot` into `~/.local/bin`. Is this a regression?

I am running macOS 10.14.4 and Python 3.7.3 installed with `pyenv`. `pipx` is likewise using Python 3.7.3.

**Comment by cs01** [comment]
Yup looks like this is a regression. Thanks for reporting.
With pipx 0.13.1.0:
```
  These binaries are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-trust
done! ✨ 🌟 ✨
```

With pipx 0.12.3.0:
```
    - easy_install
    - easy_install-3.5
    - easy_install-3.6
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jsonschema
    - jupyter
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-migrate
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-troubleshoot
    - jupyter-trust
    - pygmentize
done! ✨ 🌟 ✨
```

**Comment by cs01** [comment]
Hmm I tried to bisect commits to find the one that caused the regression and I cannot reproduce it anymore. Even the latest release works for me. Maybe we one of the jupyter releases was updated which fixed this. 

Since jupyter is a [metapackage](https://github.com/jupyter/jupyter/blob/master/setup.py#L26), pinning its version wouldn't help because it just installs the latest version of all its dependencies.

```
>> pipx --version
0.13.1.0
>> pipx install jupyter --include-deps
  installed package jupyter 1.0.0, Python 3.6.7
  These binaries are now globally available
    - easy_install
    - easy_install-3.6
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jsonschema
    - jupyter
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-migrate
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-troubleshoot
    - jupyter-trust
    - pygmentize
done! ✨ 🌟 ✨
>> jupyter --version
4.4.0
>> jupyter-console --version
6.0.0
>> jupyter-notebook --version
5.7.8

```

**Comment by elgertam** [comment]
@cs01 I wondered about that myself. The difference in behavior between 0.12.3.0 and 0.13.1.0 seemed fairly convincing, but the behavior now is entirely what I expect. In fact, when I just ran it now, pipx ignored `easy_install`, `pygmentize` and some others, which is much better behavior to me.

```bash
$ pipx install --include-deps jupyter
  installed package jupyter 1.0.0, Python 3.7.3
  These binaries are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jupyter
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-migrate
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-troubleshoot
    - jupyter-trust
done! ✨ 🌟 ✨
```

Thank you for looking into this. I'll close the issue.

**Comment by aboutaaron** [comment]
pipx 0.13.1.1 installed the `jupyter` binary but it failed to symlink it to `~/.local/bin`. I had to do that manually but everything worked after that.

**Comment by pcr910303** [comment]
@elgertam Hmm, it looks like in pipx 0.14.0.0 this has regressed, I have installed package `jupyter` with `--include-deps` and I get this:

```shellsession
$ pipx install jupyter --include-deps
  installed package jupyter 1.0.0, Python 3.7.4
  These apps are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-trust
done! ✨ 🌟 ✨

$ pipx --version
0.14.0.0
```

**Comment by sahensley** [comment]
I'm reopening this issue to consolidate some of the other issues created around the `jupyter` package.

**Comment by pcr910303** [comment]
The latest release 0.15.1.1 still shows this behavior (at least in my machine), are there any pointers for me to fix things up?
It's a bit major pain for me, so I'm willing to try to fix this if I have some pointers.
Thanks in advance.

```shellsession
$ pipx install jupyter --include-deps
  installed package jupyter 1.0.0, Python 3.7.6
  These apps are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jupyter-bundlerextension
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-nbconvert
    - jupyter-nbextension
    - jupyter-notebook
    - jupyter-qtconsole
    - jupyter-run
    - jupyter-serverextension
    - jupyter-trust
done! ✨ 🌟 ✨

$ pipx --version
0.15.1.1
```

**Comment by itsayellow** [comment]
I started trying to drill down into the dependencies, installing with `--include-deps` each time to try and find a time when the `jupyter` app was actually installed.

`jupyter` is NOT installed with `pipx install jupyter-console`
```
carvel:~ pipx install jupyter-console --include-deps
  installed package jupyter-console 6.0.0, Python 3.7.6
  These apps are now globally available
    - iptest
    - iptest3
    - ipython
    - ipython3
    - jupyter-console
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-run
    - pygmentize
done! ✨ 🌟 ✨
```

`jupyter` IS installed with `pipx install jupyter-client`, the dep of `jupyter-console`.
```
carvel:~ pipx install jupyter_client --include-deps 
  installed package jupyter_client 5.3.4, Python 3.7.6
  These apps are now globally available
    - jupyter
    - jupyter-kernel
    - jupyter-kernelspec
    - jupyter-migrate
    - jupyter-run
    - jupyter-troubleshoot
done! ✨ 🌟 ✨
```

`venv_metadata_inspector.py` finds `jupyter` in the loop: `for name in pkg_resources.get_entry_map(dist)` in `get_apps()`

`jupyter-core` actually seems to be the python package that installs `jupyter`.  It is a dep of `jupyter_client`

**Comment by itsayellow** [comment]
I think the problem is in `venv_metadata_inspector` `_dfs_package_apps`:

Specifically if this function find apps for a particular package, it will NOT search that package's dependency tree for apps.  (Which is NOT correct.)

In this code:
```
    for d in dependencies:
        app_names = get_apps(d, bin_path)
        if app_names:
            apps = [str(Path(bin_path) / app) for app in app_names]
            app_paths_of_dependencies[d] = apps
        # recursively search for more
        if d not in app_paths_of_dependencies:
            # only search if this package isn't already listed to avoid
            # infinite recursion
            app_paths_of_dependencies = _dfs_package_apps(
                bin_path, d, app_paths_of_dependencies
            )
```

If the following statement is removed:
```
        if d not in app_paths_of_dependencies:
```

Then everything seems to work fine.  `jupyter` is installed without that statement.

**Comment by itsayellow** [comment]
I have a functional branch that fixes this and still avoids infinite recursion.  I'll make sure it's ok and submit tomorrow.

**Comment by pcr910303** [comment]
@itsayellow Ah☺️ thanks for inspecting this instead! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cs01** [comment]
Huge thanks to @itsayellow for drilling into this bug and fixing it. This one was pretty tricky.

**Comment by Ricyteach** [comment]
Thank you, @itsayellow!

**Comment by rundx** [comment]
For me this still an issue on v0.16.3 only the deps binaries are installed not the main binary

```
pipx install --include-deps "git+https://github.com/Tuhinshubhra/CMSeeK"
⚠️  Note: chardetect was already on your PATH at /usr/bin/chardetect
  installed package cmseek 1.1.3, Python 3.9.2
  These apps are now globally available
    - chardetect
done! ✨ 🌟 ✨
```

```
pipx install -f --include-deps "git+https://github.com/dark-warlord14/LinkFinder"
Installing to existing venv 'LinkFinder'
  installed package LinkFinder 1.0, Python 3.9.2
  These apps are now globally available
    - editorconfig
    - js-beautify
done! ✨ 🌟 ✨
```

```
$ pipx --version
0.16.3
```

**Comment by uranusjr** [comment]
@rundx I don’t see any executables defined in either of your projects. What do you expect pipx to install but it’s not?

**Comment by rundx** [comment]
I was expecting to get a link for the main project in .local/bin/
I thought pipx can deal with any project that has a proper setup.py just like pip right?

**Comment by itsayellow** [comment]
> I was expecting to get a link for the main project in .local/bin/
> I thought pipx can deal with any project that has a proper setup.py just like pip right?

You also need a valid "entry point" (`entry_points` in setup.py or setup.cfg) defined for a project for it to work with pipx.  This allows pipx to know what constitutes the "app" of the python package.
https://pypa.github.io/pipx/how-pipx-works/#developing-for-pipx

**Comment by rundx** [comment]
@itsayellow OK, I see now, Thanks
