### ISSUE TITLE
readme suggestion?

### ISSUE THREAD

**Issue by AlJohri** [pipxproject/pipx#153]
hi @cs01! may I suggest having a very barebones version of the install documentation right in the readme? it's almost always the first thing I look at when I check out a new project.

right now its three clicks to figure out how to even install pipx:

1. https://github.com/pipxproject/pipx
2. https://pipxproject.github.io/pipx/
3. https://pipxproject.github.io/pipx/installation/

having an `Installation`  section up front and center seems ideal to me. ex: https://github.com/pypa/pipenv#installation

happy to submit a PR, let me know your thoughts

**Comment by cs01** [comment]
Thanks for bringing this up.  I agree with you. Sure, a pr is welcome! I can make one tomorrow too, either way.  If you decide to, make sure you modify the templates and generate the Readme's. It's a little tricky, but should be documented in the contributing section.

**Comment by AlJohri** [comment]
@cs01 I won’t have a chance to do this until the weekend so please go ahead- I’ll focus on the homebrew auto release stuff

**Comment by cs01** [comment]
Updated, let me know what you think. Feel free to add brew instructions when it's ready (I haven't confirmed it's working).
