### ISSUE TITLE
`pipx install rope` says "No binaries associated with package rope"

### ISSUE THREAD

**Issue by julianhr** [pipxproject/pipx#154]
I'm trying to install `rope` since VS Code uses it to refactor Python but I get the following error:

`No binaries associated with package rope.`

I see a few closed tickets similar to this issue:
https://github.com/pipxproject/pipx/issues/91
https://github.com/pipxproject/pipx/issues/13

I tried [this suggestion](https://github.com/pipxproject/pipx/issues/18#issuecomment-466693193) but it didn't work either.

Other than this problem I'm really enjoying this package, thank you!

**Comment by cs01** [comment]
As far as I can tell, `rope` does not have any binaries or scripts to enter from the command line. If that is the case, then the pipx error is appropriate, since pipx is designed to run CLI tools.Their [setup.py](https://github.com/python-rope/rope/blob/master/setup.py) file does not have any entrypoints defined.

```
>> pip install rope
Collecting rope
  Downloading https://files.pythonhosted.org/packages/69/b7/4802c5736b70fc7b7ace5d4f81355fae72702e1da0675e3a305959fdb9ce/rope-0.14.0-py3-none-any.whl (178kB)
     |████████████████████████████████| 184kB 166kB/s 
Installing collected packages: rope
Successfully installed rope-0.14.0
>> ls venv/bin/
activate          activate.fish     easy_install-3.6  pip3              python            
activate.csh      easy_install      pip               pip3.6            python3 
```

**Comment by julianhr** [comment]
I see what you mean. I've gone ahead and reinstalled it with `pip`. Thanks for the prompt feedback.

**Comment by cs01** [comment]
No problem, let me know if anything else comes up.
