### ISSUE TITLE
Any possible to backup the list of all installed and then install the list?

### ISSUE THREAD

**Issue by thepenguinthatwants** [pipxproject/pipx#156]
Hiya!

I am just testing out pipx and it feels safer than pip --user.

Normally I can take backup and then install from it at pip by

```
pip freeze > requirements.txt
pip install --user -r requirements.txt
```
Are there similar ways to do it by pipx?

**Comment by funkyfuture** [comment]
is this a duplicate of #109?

**Comment by cs01** [comment]
> is this a duplicate of #109?

Yes, closing.
