### ISSUE TITLE
Wrong error message for symlink already existing in PIPX_HOME

### ISSUE THREAD

**Issue by kidpixo** [pipxproject/pipx#163]
I was using $PIPX_BIN_DIR before pipx as my user local bin directory, that's why I have some symlink already there.

## Expected Behavior

Installing a package that already have a symlink in PIPX_HOME should tell it to the user.

## Current Behavior

Now it uses the standard error message in case

    Note: '.....' is not on your PATH environment variable. These binaries will not be globally
    accessible until your PATH is updated. Run `pipx ensurepath` to automatically add it,
    or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).

## Possible Solution

Add an error message explaining to the user. 
I didn't dig in the cose, but I bet there is a check on the symlink.

## Steps to Reproduce

1.  touch test
1. ln -s test $PIPX_BIN_DIR/pycowsay
1. pipx install pycowsay
[Optional, same result]
1. pipx install --force pycowsay

PS: I am using a github issue template from [github-issue-templates/ISSUE_TEMPLATE.md at master](https://github.com/stevemao/github-issue-templates/blob/master/bugs-only/ISSUE_TEMPLATE.md), really nice to standardise the issues and help both developer and users.

**Comment by cs01** [comment]
Thanks! This has been fixed, and github templates were added to the project.

**Comment by kidpixo** [comment]
Thank you!

Templates are really something.
