### ISSUE TITLE
Installation fails per instructions

### ISSUE THREAD

**Issue by paranoidi** [pipxproject/pipx#173]
Fails to install per instructions on freshly installed Linux Mint 19.1

```
$ python3 -m pip install --user pipx
/usr/bin/python3: No module named pip
$ python3.7 -m pip install --user pipx
/usr/bin/python3.7: No module named pip
$ python3.6 -m pip install --user pipx
/usr/bin/python3.6: No module named pip
```

Seems like pip is NOT included in any of the python packages, you probably should mention this possibility.

**Comment by cs01** [comment]
Thanks, agreed that documenting pip installation would be helpful.
