### ISSUE TITLE
Upgrade package dependencies

### ISSUE THREAD

**Issue by jpyams** [pipxproject/pipx#175]
Is there a way to upgrade a package's dependencies inside its virtual environment?

From what I can tell, `pipx upgrade` is only upgrading the top-level package.  I tried forcing the upgrade by running `pipx reinstall`, but that only uninstalls and reinstalls the top-level package.  To make anything happen to the rest of the virtual environment, I had to `pipx uninstall` and `pipx install` the package.

I'd like to have my system regularly check for updates and upgrade the dependencies for my "binaries" so I get bugfixes and the like without having to uninstall and reinstall the package entirely.

**Comment by cs01** [comment]
I think `pipx upgrade` is what you want. It runs `pip install --upgrade PACKAGE`. 

`pip` will ensure all the dependencies are within the specified range that PACKAGE requires in its setup.py file. Sometimes that means not touching any dependencies, sometimes it means upgrading all of them, and sometimes just a few. It's not a good practice to blindly update all the dependencies because they may not be compatible with the top level package.

You can see what `pipx upgrade` is doing by running `pipx upgrade PACKAGE --verbose`.

I just ran it on `tox`. You can see it skipped many dependencies, but upgraded pyparsing, packaging, and tox:
```
>> pipx upgrade tox --verbose
pipx (run_pipx_command:125): Virtual Environment location is /Users/user/.local/pipx/venvs/tox
pipx (_run:137): running /Users/user/.local/pipx/venvs/tox/bin/python -m pip install --upgrade pip
Requirement already up-to-date: pip in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (19.1.1)
pipx (_run:137): running /Users/user/.local/pipx/venvs/tox/bin/python -m pip install --upgrade tox
Collecting tox
  Downloading https://files.pythonhosted.org/packages/77/da/b57be69750b7974a2b844f2b335be57b88d6f43c129f0efcd942c1709896/tox-3.13.1-py2.py3-none-any.whl (80kB)
     |████████████████████████████████| 81kB 1.4MB/s
Requirement already satisfied, skipping upgrade: py<2,>=1.4.17 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from tox) (1.8.0)
Requirement already satisfied, skipping upgrade: toml>=0.9.4 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from tox) (0.10.0)
Requirement already satisfied, skipping upgrade: pluggy<1,>=0.12.0 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from tox) (0.12.0)
Requirement already satisfied, skipping upgrade: importlib-metadata<1,>=0.12 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from tox) (0.18)
Collecting packaging>=14 (from tox)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Requirement already satisfied, skipping upgrade: six<2,>=1.0.0 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from tox) (1.12.0)
Requirement already satisfied, skipping upgrade: virtualenv>=14.0.0 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from tox) (16.6.1)
Requirement already satisfied, skipping upgrade: filelock<4,>=3.0.0 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from tox) (3.0.12)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /Users/user/.local/pipx/venvs/tox/lib/python3.7/site-packages (from importlib-metadata<1,>=0.12->tox) (0.5.1)
Collecting pyparsing>=2.0.2 (from packaging>=14->tox)
  Using cached https://files.pythonhosted.org/packages/dd/d9/3ec19e966301a6e25769976999bd7bbe552016f0d32b577dc9d63d2e0c49/pyparsing-2.4.0-py2.py3-none-any.whl
Installing collected packages: pyparsing, packaging, tox
  Found existing installation: tox 3.12.1
    Uninstalling tox-3.12.1:
      Successfully uninstalled tox-3.12.1
Successfully installed packaging-19.0 pyparsing-2.4.0 tox-3.13.1
upgraded package tox from 3.12.1 to 3.13.1 (location: /Users/user/.local/pipx/venvs/tox)
```

**Comment by jpyams** [comment]
I understand that blindly upgrading all dependencies can break the package, and doing it all the time will cause problems.  However, using your example, if I did a fresh install of `tox` and it was incompatible with, say, `toml` 1.0, then `tox` wouldn't work anyway.

What would be really nice to have is a way to tell `pipx` to upgrade all (or some) dependencies of a package to the latest version that the package's `setup.py` allows.  Sort of a way to get the package to the state that it would be if you did a clean install right now.

My thinking is this way I can get the installations updated with the latest bugfixes, though maybe I'm approaching this in the wrong way.  I'm developing in an internal corporate environment with lots of in-house packages, and I'd like to automatically update installations to use the latest bugfixes from our in-house libraries.

**Comment by cs01** [comment]
Gotcha, that makes sense. I think you can do that with pip's `--upgrade-strategy` option. It is a little verbose, but definitely faster than reinstalling the whole package.

```
pipx upgrade PACKAGE --pip-args='--upgrade-strategy eager'
```

**Comment by jpyams** [comment]
That's just what I needed!  I had to add equals signs for it to work:

    pipx upgrade PACKAGE --pip-args='--upgrade-strategy=eager'

Thanks!  And thanks for such a great tool!
