### ISSUE TITLE
Wrong error when symlinks(executables) already exist in ~/.local/bin (symlink not installed)

### ISSUE THREAD

**Issue by 1oglop1** [pipxproject/pipx#176]
Hi, I tried to install `awscli` and got the error below.
However after reading through issues and debugging I found out that I had symlinks already present in `~/.local/.bin` but they were pointing to wrong executables (`pipsi` leftovers).
But `pipx` error message was quite confusing and not really helping to find the root cause why `symling not installed`

Either I missed something or it would be good to warn use that there are existing links already.

Here is a description of steps I took:

```
jangazda@Jan-Gazdas-MacBook-Pro:~$ pipx --version
0.13.1.1

jangazda@Jan-Gazdas-MacBook-Pro:~$ pipx install awscli
  installed package awscli 1.16.190, Python 3.7.2
    - aws (symlink not installed)
    - aws.cmd (symlink not installed)
    - aws_bash_completer (symlink not installed)
    - aws_completer (symlink not installed)
    - aws_zsh_completer.sh (symlink not installed)
⚠️  Note: '/Users/jangazda/.local/bin' is not on your PATH environment variable. These binaries will not be globally accessible until your PATH is updated. Run `userpath append ~/.local/bin` to automatically add it, or manually modify your PATH in your shell's config file (i.e. ~/.bashrc).
done! ✨ 🌟 ✨
```
`pipx` said there is something wrong with my path (even though it was not), so checked my path and ran suggested command an
```
jangazda@Jan-Gazdas-MacBook-Pro:~$ echo $PATH
/Users/jangazda/.poetry/bin:/Users/jangazda/.nvm/versions/node/v12.4.0/bin:/Users/jangazda/.pyenv/shims:/Users/jangazda/.pyenv/shims/3.7.2:/Users/jangazda/.pyenv/bin::/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

jangazda@Jan-Gazdas-MacBook-Pro:~$ userpath append ~/.local/bin
The directory `` is already in PATH! If you are sure you want to proceed, try again with the -f/--force flag.
```

But in the end the real problem were existing symlinks, after deleting symlinks and `pipx install awscli` all went smooth finally.

**Comment by cs01** [comment]
Thanks for reporting and sorry for the inconvenience. I will add a better error message.
