### ISSUE TITLE
Feature request: bash completion

### ISSUE THREAD

**Issue by mgedmin** [pipxproject/pipx#181]
It would be _amazing_ if pipx had bash completion, so that users could do `pipx up<tab> packag<tab>` and stuff.

This would need two things:
1. a bash-completion plugin that defines the possible completions
2. a way for users to install it

Speaking of (2), I like the way `rustup` does it: the user is encouraged to run

    mkdir -p ~/.local/share/bash-completion/completions
    rustup completions bash > ~/.local/share/bash-completion/completions/rustup

So I suggest a similar `pipx completions bash`, maybe with an extra step (`pipx completions bash --install`) to automate the installation so the user doesn't have to mkdir and redirect manually.

(The `bash` on the command line is because different shells have different syntax for user-defined completions.)

**Comment by cs01** [comment]
I agree! 

I haven't looked into this much but https://github.com/kislyuk/argcomplete might be usable here too. pipx uses argparse, so that library should apply.

**Comment by mgedmin** [comment]
I wrote a bash-completion file for `pipx` as best as I could: https://github.com/mgedmin/dotfiles/blob/master/local/share/bash-completion/completions/pipx

I'm happy to contribute it under whatever FOSS licence you desire.

**Comment by cs01** [comment]
WHAT! Amazing! I can't wait to try it out.

**Comment by cs01** [comment]
This is so good, I love it! 

I do wonder about the maintenance burden though. If the API changes the completions will have to be updated, right?

**Comment by mgedmin** [comment]
> I do wonder about the maintenance burden though. If the API changes the completions will have to be updated, right?

That's true, and perhaps using argcomplete would fix that.  (I'm not familiar with it.  I looked a bit at the documentation, and it seemed rather complicated.)

**Comment by mgedmin** [comment]
I hereby volunteer to maintain the hand-written bash completion file wrt command-line changes.  All I ask is that somebody pings me before a release so I don't need to watch all the commits all the time.

**Comment by cs01** [comment]
> I hereby volunteer to maintain the hand-written bash completion file wrt command-line changes. All I ask is that somebody pings me before a release so I don't need to watch all the commits all the time.

I can definitely let you know when the API will change before a release. Thanks for the offer! 

Do you want to add in the bash completion file/installation to pipx or do you want me to do it? I am not sure how bash completion scrips are installed/the best place to install them to.

**Comment by cs01** [comment]
Actually before we start going down this road, let me experiment with the argcomplete package to see how hard it is to set up/use.

**Comment by mgedmin** [comment]
> Do you want to add in the bash completion file/installation to pipx or do you want me to do it?

I'm always happy when somebody else steps up to do the things I want done :)

> I am not sure how bash completion scrips are installed/the best place to install them to.

All you need is create a file in ~/.local/share/bash-completion/completions/ (and, possibly, os.makedirs() that directory if it doesn't exist).

As I mentioned in the original description, `rustup completions` chooses to print the completions file to stdout asking the user to do the mkdir and shell redirection themselves.  This is perhaps more transparent and less scary, but also less convenient.   Personally, if I found the time to do the PR, I'd be inclined to copy rustup (assuming they thought about this long and hard and came up with the best design), but also I'd add a `--install` switch to do the installation for me instead of just printing the completions to stdout, for convenience.

**Comment by cs01** [comment]
I don't mind doing it, especially since you took the time to write the bash completions. If I decide to go with your completions after experimenting w/ argcomplete I will put up a pr and tag you on it.

**Comment by cs01** [comment]
argcomplete actually works well, so I created a PR https://github.com/pipxproject/pipx/pull/182.

**Comment by cs01** [comment]
This is available in master now. Instructions can be seen by running `pipx completions`. It's also available to test in the pre-release channel.

```
python3 -m pip install --user --pre --no-cache-dir -U pipx
```
