### ISSUE TITLE
reinstall-all (and similar commands) break if unexpected items present in venvs dir

### ISSUE THREAD

**Issue by uranusjr** [pipxproject/pipx#185]
Many OSs inject hidden files when you open a directory in the file explorer, e.g. `.DS_Store` on macOS, `Thumbs.db` and `desktop.ini` on Windows.

Currently, `reinstall-all` et al. use `.iterdir()` to walk through venvs, and break when they encounter unexpected entries.

**Comment by cs01** [comment]
Thank you!
