### ISSUE TITLE
how to install packages globally?

### ISSUE THREAD

**Issue by haakenlid** [pipxproject/pipx#187]
pipx wants to install everything in the current user's $HOME directory. But how do I install something for all users?

I can add the env variable explicitly every time I'm installing. But that is very clunky. Shouldn't the default install location for `sudo pipx intall` be the same as with `sudo pip install`?

    sudo -H PIPX_BIN_DIR=/usr/local/bin/ PIPX_HOME=/usr/local/ pipx install ptpython

**Comment by cs01** [comment]
pipx's _raison d'être_ is to install things globally without needing sudo. It is not made by the pip team, and doesn't try to necessarily copy or be compatible with pipi's API or defaults. I think your case is valid, but not the most common case (and there for not the default pipx should use). 

To make the command less tedious, you could add this to your .bashrc file
```
export PIPX_BIN_DIR=/usr/local/bin/ 
export PIPX_HOME=/usr/local/
```

then run 
```
sudo pipx install ptpython
```
