### ISSUE TITLE
Pipx don't do auto cleanup after I accidentally interrupted the installation process

### ISSUE THREAD

**Issue by KsRyY** [pipxproject/pipx#193]
When I am installing poetry using pipx, I selected the wrong window and hits `Ctrl+C` and interrupts the installation process. When I attempt to resume the installation process (running `pipx install poetry --verbose`) I get a message:
```
pipx (run_pipx_command:125): Virtual Environment location is /home/andy/.local/pipx/venvs/poetry
'poetry' already seems to be installed. Not modifying existing installation in '/home/andy/.local/pipx/venvs/poetry'. Pass '--force' to force installation
```
Maybe there could be a auto cleanup process after the installation process that had been interrupted?

**Comment by cs01** [comment]
Good suggestion. I will add it, but can't promise when I'll get to it.

**Comment by cs01** [comment]
This has been added to pipx 0.13.2.1.
