### ISSUE TITLE
Typo in installation instructions: s/ensurepath/ensurepip/

### ISSUE THREAD

**Issue by cjolowicz** [pipxproject/pipx#198]
There appears to be a typo in the installation instructions:

```sh
python3 -m ensurepath
```

There is no such module. This should probably be `ensurepip`.

This typo occurs in the following files:

- [README.md](../tree/master/README.md) 
- [docs/index.md](../tree/master/docs/index.md)
- [docs/installation.md](../tree/master/docs/installation.md)

**Comment by cs01** [comment]
Thanks for reporting! I fixed it. 

```
python3 -m pipx ensurepath
```

is the correct command. `ensurepath` is a valid command to `pipx`.
