### ISSUE TITLE
Incorrect link in README

### ISSUE THREAD

**Issue by rjmorris** [pipxproject/pipx#205]
When viewing the README in GitHub, the link to installation details returns a 404. (I'm referring to the link that appears in the sentence "For more details, installation.") I believe this happens because the link points to `https://github.com/pipxproject/...` instead of `https://pipxproject.github.io/...`. The "Comparison to Other Tools" link, which appears earlier in the README, points to the latter and works.

**Comment by cs01** [comment]
Thanks! This has been fixed in master.
