### ISSUE TITLE
"Requires a different Python version"

### ISSUE THREAD

**Issue by jtrakk** [pipxproject/pipx#211]
I've been using pipx a while and currently falling in love with Poetry, but when I tried to use them together something went wrong.

Using Poetry with `python = "^3.7"` in the `tool.poetry.dependencies`, I get this error:
```
$ pipx install . --force --python python3.7
Installing to existing directory '/home/user/dotfiles/dotfiles/.local/pipx/venvs'
ERROR: Package 'aw-view-0.0.154' requires a different Python: 3.6.7 not in '>=3.7,<4.0'
                        
Not removing existing venv /home/user/dotfiles/dotfiles/.local/pipx/venvs because it was not created in this session
'/home/user/dotfiles/dotfiles/.local/pipx/venvs/bin/python -m pip install . -q' failed

```

`python -m pip install .` does work. 

Poetry is installed with 3.7, pipx is using `/usr/bin/python3` which is `3.6.7`.

The way poetry works is it [builds a setup.py](https://github.com/sdispater/poetry/tree/master/poetry/masonry/builders) and runs it with `pip`.

You might decide this is a Poetry issue, though hopefully in that case they won't decide it's a pipx issue :-)

pipx 0.13.2.3x
Poetry 0.12.17
Ubuntu 18.04

**Comment by itsayellow** [comment]
Both pipx and poetry have both changed a lot since this bug report. 😄 I'm going to close it, feel free to reopen if you're still having trouble.
