### ISSUE TITLE
Multi-step pip install

### ISSUE THREAD

**Issue by kshpytsya** [pipxproject/pipx#214]
```
pipx install urh
    ERROR: Command errored out with exit status 1:
     command: /home/uken/.local/pipx/venvs/urh/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-a7wvaym1/urh/setup.py'"'"'; __file__='"'"'/tmp/pip-install-a7wvaym1/urh/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-a7wvaym1/urh/
    Complete output (2 lines):
    You need Cython to build URH's extensions!
    You can get it e.g. with python3 -m pip install cython.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
'/home/uken/.local/pipx/venvs/urh/bin/python -m pip install urh -q' failed
```

Adding `--pip-args cython` does not help.

This matches exactly what happens if one creates a new venv and runs pip install:

```
$ python3 -m venv venv
$ venv/bin/pip install cython urh
Collecting cython
  Using cached https://files.pythonhosted.org/packages/f1/d3/03a01bcf424eb86d3e9d818e2082ced2d512001af89183fca6f550c32bc2/Cython-0.29.13-cp37-cp37m-manylinux1_x86_64.whl
Collecting urh
  Using cached https://files.pythonhosted.org/packages/c8/b4/6603578b0fef672a450a77c20f2a50aa8e9985cb0e850cdea8862cf9fbd9/urh-2.7.5.tar.gz
    Complete output from command python setup.py egg_info:
    You need Cython to build URH's extensions!
    You can get it e.g. with python3 -m pip install cython.

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-e2z83_ix/urh/
```

To work around this issue manually, one needs to do installation in two steps:
```
$ python3 -m venv venv
$ venv/bin/pip install cython
$ venv/bin/pip install urh
```

I cannot find any way to achieve this with `pipx`, preferably in a single invocation.

**Comment by cs01** [comment]
Interesting, I was able to install it:
```
>> pipx install urh
You should consider upgrading via the 'pip install --upgrade pip' command.
  installed package urh 2.7.5, Python 3.7.3
  These apps are now globally available
    - urh
    - urh_cli
done! ✨ 🌟 ✨
```
Have you followed installation instructions on https://pypi.org/project/urh/? Maybe there is some system dependency you are missing.

**Comment by kshpytsya** [comment]
Well, but it installs and works if I do it in two steps, i.e.:
```
$ python3 -m venv venv
$ venv/bin/pip install cython
$ venv/bin/pip install urh
```

**Comment by cs01** [comment]
It works for me in a single step, which indicates there is some difference between our environments. Have you followed installation instructions on https://pypi.org/project/urh/?

**Comment by cs01** [comment]
Looks like maybe you need to run
```
sudo apt-get install cython3
```

**Comment by kshpytsya** [comment]
First of all, I am not running Debian but Gentoo. Cython is installed in the system. Running `cython` uses the same python3.7 which is the default (and only) python3. But IMHO, if there is a way to achieve this with two pip calls, it should be possible to achieve with `pipx`.

**Comment by cs01** [comment]
I understand that this is not super streamlined with pipx, but unfortunately `urh` has a unique setup and does not have wheels published for all platforms. The urh maintainer has built wheels (platform-specific binary distributions) for mac and windows, but not linux. https://pypi.org/project/urh/#files

You can see in https://github.com/jopohl/urh/blob/master/setup.py#L49 that it will raise an error if it can't use cython before it even tries to install cython.

I suppose an argument could be added to pipx to run a command after pipx creates a virtual environment but before the installation occurs, but it seems like it's working around the core issue of the way setup.py is handled with urh.

Right now the following will work with no modifications to pipx. What do you think?
```
pipx install cython
pipx inject cython urh --include-apps
```

**Comment by kshpytsya** [comment]
The main problem with the suggested steps is that the `venv` will be named `cython` and not `urh`.

**Comment by itsayellow** [comment]
I think the main problem here is `urh`'s `setup.py` file lists `cython` as a run-time dependency but also needs it as a build- dependency.

`urh` could solve this in a PEP 518 compatible way by using `pyproject.toml` and adding `cython` to `requires` key of the `[build-system]` table.
https://www.python.org/dev/peps/pep-0518/#build-system-table

Closing since we're not going to add a workaround for something that `urh` could fix.

**Comment by n8henrie** [comment]
For anyone ending up here via Google, in mid 2022 I still cannot install urh via pipx on an M1 Mac; even if you resolve the cython dependency issue, you run into trouble with pyqt5, which as of yet doesn't provide any compatible wheels (`curl --silent "https://pypi.org/pypi/PyQt5/json" | grep -i arm64`).

My workaround is to use homebrew-installed pyqt5 (<https://stackoverflow.com/a/72363627/1588795>), which is arm64 compatible and accessible via the hombrew-installed python3.9, and then create a virtualenv with `python3.9 -m venv --system-site-packages .venv`, after which one can:

```console
$ source ./.venv/bin/activate
$ python -m pip install cython
$ python -m pip install urh
$ urh
```

**Comment by tomcass240** [comment]
Doesn't work don't waste your time with this "solution".
