### ISSUE TITLE
How to install a local package ?

### ISSUE THREAD

**Issue by halloleo** [pipxproject/pipx#216]
I want to install a package which is in a local directory. So I tried

    pipx install  /the/path/to/my/package

but I get the error message: *Not installing to existing directory.* I guess pipx takes the path as the location for new venv...

So how can I install a package not from pypi but from a local directory?

**Comment by cs01** [comment]
You can do 
```
pipx install PACKAGE_NAME --spec /the/path/to/my/package
```

Note that you'll have to use `pipx upgrade PACKAGE_NAME --spec /path/to/package` as well.

**Comment by halloleo** [comment]
Thanks cs01! That works.

**Comment by halloleo** [comment]
Confirmed. In the current version just use the path:

    pipx install /the/path/to/my/package

**Comment by omaxx** [comment]
Is any option for upgrade?
I try `pipx upgrade ./package-1.0.0.tar.gz`, but it doesn't work:
```
Package is not installed. Expected to find .local/share/pipx/venvs/package-1-0-0-tar-gz, but it does not exist.
```

**Comment by Roy-Orbison** [comment]
@omaxx looks like it's picking the package name from the last path segment. It's probably something that pipx could do better at, but try extracting it to a temporary directory whose name matches the expected package & venv name.

**Comment by Roy-Orbison** [comment]
FYI, upgrading using the local path failed for me:
```sh
pipx upgrade ~/Path/To/dbxfs
```
produced
```
Package is not installed. Expected to find /home/roy/path/to/package, but it does not exist.
```
Using just the package name seems to have automatically gone to the right place:
```
pipx upgrade package
```

If you need to move the source directory, updating the path in `~/.local/pipx/venvs/package/pipx_metadata.json` may be enough.

**Comment by zack-mayoh** [comment]
> FYI, upgrading using the local path failed for me:
> 
> ```shell
> pipx upgrade ~/Path/To/package
> ```
> 
> produced
> 
> ```
> Package is not installed. Expected to find /home/roy/path/to/package, but it does not exist.
> ```
> 
> Using just the package name seems to have automatically gone to the right place:
> 
> ```
> pipx upgrade package
> ```
> 
> If you need to move the source directory, updating the path in `~/.local/pipx/venvs/package/pipx_metadata.json` may be enough.

This doesn't seem to work for me? When I replace the whl file with a new version in the same location, I get this error:
```
Unable to parse package spec: /home/me/path/to/package-<currently-installed-version>.whl
```

**Comment by Roy-Orbison** [comment]
In my case, the package reference was a directory containing the source, not a `.whl` file.

**Comment by XcantloadX** [comment]
What if my local package depends on another local package? Pass mutiple paths to `pipx install` doesn't seem to work:
```
PS E:\GithubRepos\KotonesAutoAssistant> pipx install .\dist\ksaa-2025.2.14.tar.gz .\dist\ksaa_res-0.1.0.tar.gz
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\<username>\.local\pipx\logs\cmd_2025-02-18_17.32.03_pip_errors.log

pip seemed to fail to build package:
    pydantic==2.10.4

Some possibly relevant errors from pip install:
    ERROR: Ignored the following versions that require a different python version: 1.2.4 Requires-Python >=3.6,<=3.10; 1.2.5 Requires-Python >=3.6,<=3.10; 1.2.6 Requires-Python >=3.6,<=3.10; 1.2.7 Requires-Python >=3.6,<=3.10; 1.2.8 Requires-Python >=3.6,<=3.10
    ERROR: Could not find a version that satisfies the requirement ksaa-res==0.1.0 (from ksaa) (from versions: none)
    ERROR: No matching distribution found for ksaa-res==0.1.0

Error installing ksaa from spec
'E:\\GithubRepos\\KotonesAutoAssistant\\dist\\ksaa-2025.2.14.tar.gz'.
```
Swap the order:
```
PS E:\GithubRepos\KotonesAutoAssistant> pipx install .\dist\ksaa_res-0.1.0.tar.gz .\dist\ksaa-2025.2.14.tar.gz

No apps associated with package ksaa-res or its dependencies. If you are attempting to
install a library, pipx should not be used. Consider using pip or a similar tool
instead.
```
