### ISSUE TITLE
youtube-dl works when installed by Brew but not pipx

### ISSUE THREAD

**Issue by zachvalenta** [pipxproject/pipx#232]
same version of `youtube-dl` across both

❌ doesn't work with `pipx`
```sh
$ youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=FFZj_Srj4eU

[youtube] FFZj_Srj4eU: Downloading webpage
ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)'),))

$ pipx list
venvs are in /Users/zach/.local/pipx/venvs
apps are exposed on your $PATH at /Users/zach/.local/bin
   package youtube-dl 2019.9.28, Python 3.6.1
    - youtube-dl

$ pipx uninstall youtube-dl
uninstalled youtube-dl! ✨ 🌟 ✨
```

✅ does work with `brew`
```sh
$ brew install youtube-dl
==> Summary
🍺  /usr/local/Cellar/youtube-dl/2019.09.28: 12 files, 2.1MB, built in 4 seconds

$ source $HOME/.bash_profile
 updating ~/.bash_profile at: Wed Oct  2 17:29:47 EDT 2019

$ youtube-dl --extract-audio --audio-format mp3 --audio-quality 0 https://www.youtube.com/watch?v=FFZj_Srj4eU
[youtube] FFZj_Srj4eU: Downloading webpage
[youtube] FFZj_Srj4eU: Downloading video info webpage
[download] Destination: The Clipse- Mr. Me Too-FFZj_Srj4eU.webm
[download] 100% of 3.44MiB in 00:01
[ffmpeg] Destination: The Clipse- Mr. Me Too-FFZj_Srj4eU.mp3
Deleting original file The Clipse- Mr. Me Too-FFZj_Srj4eU.webm (pass -k to keep)
```

**Comment by cs01** [comment]
I just tested this and it worked fine for me. That looks like an issue with `youtube-dl` and the libraries it uses. Try searching the web for that error. Here are a couple places to start

https://stackoverflow.com/questions/41691327/ssl-sslerror-ssl-certificate-verify-failed-certificate-verify-failed-ssl-c

https://github.com/ytdl-org/youtube-dl/search?q=urlopen+error+%5BSSL%3A+CERTIFICATE_VERIFY_FAILED%5D+certificate+verify+failed+%28_ssl.c%3A749%29%3E+%28caused+by+URLError%28SSLError%281%2C+%27%5BSSL%3A+CERTIFICATE_VERIFY_FAILED%5D+certificate+verify+failed&type=Issues

https://stackoverflow.com/questions/46604114/python-requests-ssl-error-certificate-verify-failed

**Comment by zachvalenta** [comment]
Totally agree with you that it's a `youtube-dl` thing. 

The nut I couldn't crack was: how could the same version of `youtube-dl` exhibit disparate CLI behavior between `brew` and `pipx`?

btw `pipx` has been awesome to use so far, keep up the good work!

**Comment by cs01** [comment]
> btw pipx has been awesome to use so far, keep up the good work!

Thanks, good to hear! 😄 

> The nut I couldn't crack was: how could the same version of youtube-dl exhibit disparate CLI behavior between brew and pipx?

My guess is they are using different python/`site-packages`. How does brew bundle and install `youtuble-dl`? It is likely not using the same interpreter that `pipx` is using.

**Comment by zachvalenta** [comment]
> My guess is they are using different python/site-packages. How does brew bundle and install youtuble-dl? It is likely not using the same Python interpreter being used to run pipx.

Good point. Time for some detective work. Not sure how soon I'll get to it though, so feel free to close this if you think it makes sense.

**Comment by cs01** [comment]
I am pretty sure this is something not directly related to pipx since I was able to run it on my mac, so I will close. Feel free to reopen if you find otherwise.

**Comment by moribellamy** [comment]
I just got the same error. it's got something to do with the ssl certs that come with a python install. this stackoverflow links to a package which helps some people by installing extra certs, but it didn't work for me: https://github.com/ytdl-org/youtube-dl/issues/4816.

maybe this helps too https://stackoverflow.com/questions/39356413/how-to-add-a-custom-ca-root-certificate-to-the-ca-store-used-by-pip-in-windows.

re-opening the issue just on a hunch, feel free to close if you still feel this can't be fixed in pipx itself

**Comment by moribellamy** [comment]
well nevermind I can't open it myself, that's not how github works. please do consider taking another look though
