### ISSUE TITLE
How to see with which `--spec` option I installed a package

### ISSUE THREAD

**Issue by halloleo** [pipxproject/pipx#238]
Local package I install with `--spec` like this

    pipx install mypackage --spec /path/to/mypackage

which works perfectly! :-)

But when I later want to upgrade mypackage I might have forgotten whether I have installed it via `--spec` or not. Can I somehow see this via `pipx list` or similar?

**Comment by halloleo** [comment]
Thanks @cs01. Looking froward to the merge. To test the PR I might install pipx with it.

**Comment by itsayellow** [comment]
Right now #222 is mostly just infrastructure for pipx.  The user-facing aspects which you are looking for aren't part of that pull request as of now.  But you would be able to look in the venv directory at the pipxrc.json file to see installation details like the `--spec` in a DIY way.

**Comment by halloleo** [comment]
That's good enough for me. Thanks.
