### ISSUE TITLE
Allow multiple versions of Python package binaries

### ISSUE THREAD

**Issue by vikahl** [pipxproject/pipx#241]
**How would this feature be useful?**
Allowing multiple versions of the same Python package to be installed at the same time in a user friendly way. Sometimes it is needed to have multiple versions of the same package installed (for example Ansible).

The installation can be handled by pinning the version as `pipx install ansible==2.8.4` or `pipx run`. `pipx run` will however not run the package since it cannot find the binary called `ansible==2.8.4`.

**Describe the solution you'd like**
Symlinks would be created with the version name if supplied.
`pipx install ansible` -> symlink is named ansible
`pipx install ansible==2.8.4` -> symlink is named ansible284 (or similar)

**Describe alternatives you've considered**
- Manually create the symlinks
- Uninstall and reinstalling the packages

**Comment by itsayellow** [comment]
Just a note, you should be able to do this using for example:
```
pipx run --spec 'ansible==2.8.4' ansible
```

**Comment by itsayellow** [comment]
For multiple versions coexisting, see #445 (merged).

**Comment by vikahl** [comment]
Great, thank you. It solves my use cases.
