### ISSUE TITLE
Additional Maintainers

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#242]
After a year pipx has grown into a pretty successful open source project -- over [100k downloads](https://pepy.tech/project/pipx), mentioned on [episode 118 of Talk Python](https://pythonbytes.fm/episodes/transcript/118/better-python-executable-management-with-pipx), active contributors, issue creations, almost 1000 github stars, a page on [packaging.python.org](https://packaging.python.org/guides/installing-stand-alone-command-line-tools/), and no signs of slowing down! All thanks to @sahensley starting a conversation in the [pipsi issue tracker](https://github.com/mitsuhiko/pipsi/issues/178) with the same title as this issue :smile:, and to the many contributors besides me who have shaped pipx into what it is today. 

I have started a few open source projects, but never given up the reigns and granted commit rights to anyone else. I would like to do that now for pipx. It has wide adoption and fairly robust CI tests, so there is a good starting place for everyone to work from.

Maintainers would

* triage issues (add labels to them, or fix urgent things immediately)
* review pull requests
* merge code into master
* decide which features go into pipx and how to implement them
* be listed on the pipx readme as maintainers

I will still be the sole publisher to PyPI for now, with the plan to let maintainers publish eventually.

@itsayellow, @clbarnes, @jayvdb, @joshuarli, @sahensley, @aiguofer would you be interested in becoming maintainers?

**Comment by joshuarli** [comment]
I don't have a lot of spare time at all right now to donate, but would be interested in the future if things clear up. Thanks for asking though!

**Comment by cs01** [comment]
@joshuarli no problem, don't spread yourself too thin

> some pip packages can do really crazy stuff.

indeed :sweat_smile:

**Comment by itsayellow** [comment]
I'm honored to be asked and would love to help!

**Comment by sahensley** [comment]
It is amazing what you (and all the contributors) accomplished in a year!

While I don't have a huge amount of time, I could certainly commit a few hours a week.  I'd mainly focus on verifying, labeling and researching issues.

**Comment by clbarnes** [comment]
I'd love to be involved - pipx solves a serious problem in the large ecosystem of system tools written in python, and it's a great codebase. However, I'm about to start a new job while still working on a PhD thesis so I can't really predict my time allowance right now.

**Comment by aiguofer** [comment]
Hey! I'd love to help since I do use this every day (and my dotfile config depends heavily on it), although I'm not sure how much time I can commit to it. I guess with a few other maintainers we should hopefully be able to keep up with issues and PRs though :)

**Comment by gaborbernat** [comment]
I'm maintaining both virtualenv and tox, I probably would not be available for development, but more than happy to champion with maintenance (release, reviews, ci), integration with the python packaging ecosystem. This is a truly awesome project.

**Comment by cs01** [comment]
> It is amazing what you (and all the contributors) accomplished in a year!
> 
> While I don't have a huge amount of time, I could certainly commit a few hours a week. I'd mainly focus on verifying, labeling and researching issues.

For sure this project would not be where it is if it weren't for contributors. Everyone has been super helpful and friendly, and it's been a very positive experience for me and hopefully everyone else involved.

If you are up to it, help on issue organization would be great. I think the time of a few people combined will add up and be effective in managing the project. But if you don't have the time don't feel obligated.

**Comment by cs01** [comment]
> I'd love to be involved - pipx solves a serious problem in the large ecosystem of system tools written in python, and it's a great codebase. However, I'm about to start a new job while still working on a PhD thesis so I can't really predict my time allowance right now.

Sounds good! Congrats btw.

**Comment by cs01** [comment]
> I'm maintaining both virtualenv and tox, I probably would not be available for development, but more than happy to champion with maintenance (release, reviews, ci), integration with the python packaging ecosystem. This is a truly awesome project.

Wow, thanks so much! I think I'll take you up on that. And thanks for all your work on virtualenv and tox!

**Comment by AlJohri** [comment]
Happy to get involved as well- I can help on the packaging side, triaging issues, and other things that come up.

**Comment by cs01** [comment]
> Happy to get involved as well- I can help on the packaging side, triaging issues, and other things that come up.

Thanks, done! 

Btw I probably won't be able to respond or dig into issues for the next few days/weeks.

**Comment by itsayellow** [comment]
I think we've added the new maintainers, so can probably close this Issue. 😄
