### ISSUE TITLE
Offline tests

### ISSUE THREAD

**Issue by jayvdb** [pipxproject/pipx#248]
**How would this feature be useful?**
Packaging for distros requires running the tests in a VM isolated from the internet to avoid any pollution.  Offline tests are needed for this.

However, the test suite can also be quicker if it uses a fake PyPI server that only contains the packages needed for testing.

**Describe the solution you'd like**
pipenv project tests uses its own, as a fixture in the repo.

There are some other earlier standalone attempts

https://github.com/uranusjr/pytest-pypi-gateway

https://github.com/uranusjr/pytest-fakepi

https://pypi.org/project/pytest-pypi/

https://github.com/manahl/pytest-plugins has a devpi pytest plugin for https://github.com/devpi/devpi

**Describe alternatives you've considered**
An old style PyPI HTML `simple` index page.

**Comment by gaborbernat** [comment]
@jayvdb I've done some of this, the easiest is to just setup a devpi instance part of the pytest, as fixture; see https://github.com/tox-dev/integration-test/blob/master/tests/conftest.py#L73-L118

**Comment by cs01** [comment]
This would be a great addition. I've never liked how non-hermetic and slow pipx's tests are.

@gaborbernat your approach looks nice and straightforward. With pipx, the following packages are tested:
```
["cloudtoken", "awscli", "ansible", "shell-functools", "pycowsay", "black"]
```

The reason so many are tested is to exercise `pipx/venv_metadata_inspector.py`, which has been built as more of an art than a science. I make a guess at how to parse the files and check that things work, then add the difficult packages to CI to make sure there aren't regressions. 

Ideally a minimal sdist could be created that exercises all the code paths in that file, but I don't have the tribal knowledge or time to do that, so I added more CI tests. 

To make offline tests work, we'd have to add the source code for all those projects to pipx, then build+upload their respective wheels to the pydev server (as you did in tox's fixtures). That seems like a lot of bloat, so I would be interested to hear any other ideas. It would be easy to do for `pycowsay` for sure though.

**Comment by gaborbernat** [comment]
Why add sources. We can always just add the wheels/sdist of those directly, not? Similar to how virtualenv bundles wheels to the project. The test projects wheels could be considered as test resource 👍

**Comment by jayvdb** [comment]
Also the wheels/sdist can be fetched from PyPI, and cached for re-runs.  Then they can be either added during the sdist process, and/or a doc generated describing which objects to fetch from PyPI and where to put them in order to pre-cache for offline test runs.

@dephell went as far as adding [an offline job](https://github.com/dephell/dephell/blob/afa1fba/.travis.yml#L66) to ensure that the tests dont accidentally use network when they shouldnt.

**Comment by gaborbernat** [comment]
I don't think this belongs to sdist at all, or offline. Best is to use a pytest fixture with appdirs user data storage place. One then can use pip download to acquire the wheels from the remote.

**Comment by jayvdb** [comment]
Offline is the title of this issue. ;)

**Comment by gaborbernat** [comment]
I'm saying to provision the wheels at the first run for the machine if not present already. The other option is to bundle the wheels with the code.
