### ISSUE TITLE
installation failure in travis-ci

### ISSUE THREAD

**Issue by guykisel** [pipxproject/pipx#25]
```
1.45s$ curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python
Installing pipx
Traceback (most recent call last):
  File "<stdin>", line 231, in <module>
  File "<stdin>", line 215, in main
  File "<stdin>", line 136, in install
  File "<stdin>", line 52, in create_venv
  File "<stdin>", line 64, in upgrade_package
  File "<stdin>", line 70, in _run_pip
  File "<stdin>", line 36, in _run
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/opt/python/3.6.3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/home/travis/.local/pipx/venvs/pipx/bin/pip'): PosixPath('/home/travis/.local/pipx/venvs/pipx/bin/pip')
```
I suspect `get-pipx.py` probably needs to use https://docs.python.org/3/library/os.html#os.makedirs somewhere to ensure that the full path exists.

For reference, the WIP travis config in my PR in my project - https://github.com/guykisel/inline-plz/blob/8956751a942ce3088fbb81a563d63d8aa545073f/.travis.yml

**Comment by cs01** [comment]
Sorry for the inconvenience, will get this taken care of.

**Comment by guykisel** [comment]
Thanks for taking a look! There's no hurry :)

**Comment by r-darwish** [comment]
I looked into that a bit. These problem is stated [here](https://github.com/travis-ci/travis-ci/issues/9524) and [here](https://stackoverflow.com/questions/48186166/install-pip-in-travis-virtualenv) but there doesn't seem to be any solution.

As stated [here](https://docs.travis-ci.com/user/languages/python#travis-ci-uses-isolated-virtualenvs), the Travis file already runs inside a virtualenv. It appears that invoking `venv` from inside an exiting `virtualenv` creates a new virtual environment in which pip isn't present.

Perhaps `get-pipx` should not create a virtualenv of its own if `get-pipx` is already being run inside a virtualenv?

**Comment by cs01** [comment]
@r-darwish thanks for the additional info, it's very helpful!

I think the logic should be as follows:
```
if in_virtualenv():
    if travis():  # check for TRAVIS env var
        logging.warning("Detected travis test build. Installing pipx in non-standard way for testing")
        # use global pip and set path expectations appropriately, maybe running `pip -t` instead
    else:
        raise PipError(
            "pipx should not be installed while a virtualenv is activated. Run `deactivate` then try again."
        )
```

**Comment by cs01** [comment]
> It appears that invoking venv from inside an exiting virtualenv creates a new virtual environment in which pip isn't present.

@r-darwish I tested this theory, but it does not match what's happening on my computer. No matter how I create a new virtual env, pip is always there.
