### ISSUE TITLE
Add `reinstall` command

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#256]
**How would this feature be useful?**

per @sahensley 's comment in https://github.com/pipxproject/pipx/pull/246

> Also, a bit of a side trek but would it be worth introducing reinstall for an individual package? I could possible see a need if only certain venvs were made with a Python interpreter that is no longer present but it may be a bit of a niche case. The instance I've run into this when I've had multiple Python versions compiled via Pyenv.

**Describe the solution you'd like**

Add top-level `reinstall` command, as an alternative to the `reinstall-all` command.

**Describe alternatives you've considered**

Uninstall then reinstall the package, but that is not super very friendly.

**Comment by itsayellow** [comment]
This makes sense to me.  Especially combined with `pipx reinstall-all --skip`.
