### ISSUE TITLE
add isort to lint tests

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#257]
**How would this feature be useful?**

Ensure imports have been autosorted will make code consistent/readable and save time for developers.

**Describe the solution you'd like**

Use `isort` and https://github.com/asottile/seed-isort-config in the nox `lint` session. Also add a new nox session `format` to automatically run black, isort, and anything else we add.

Something like
```
    session.run("seed-isort-config", "--application-directories=pipx")
    session.run("isort", "--project=pipx", "--recursive", "--apply", *source_files)
```

**Describe alternatives you've considered**

Manually run isort, which is what I've been currently doing.

**Comment by gaborbernat** [comment]
Can we just call pre-commit instead; with black and all that, see e.g. https://github.com/tox-dev/tox/blob/master/.pre-commit-config.yaml

**Comment by itsayellow** [comment]
I started running pre-commit on one computer a while ago and am liking it.  Among other things it's nice for easily fixable things like black.  It's also nice that we can have a standard `.pre-commit-config.yaml` for the pipx project if we wish.

**Comment by itsayellow** [comment]
I have a mockup of two approaches for adding isort to lint tests.  I prefer the one that shows the actual diff of the necessary changes to fix a file when that file has badly-sorted imports.  But broadly speaking there are two options:

`isort --check --diff` actually shows diffs for failing files.  It's verbose but even if you aren't running isort yourself you could fix the file manually from the provided diff information.
Its output looks like this:
```
nox > isort --check --diff --profile black src/pipx tests noxfile.py get-pipx.py setup.py generate_docs.py
ERROR: /home/runner/work/pipx/pipx/src/pipx/animate.py Imports are incorrectly sorted and/or formatted.
ERROR: /home/runner/work/pipx/pipx/src/pipx/shared_libs.py Imports are incorrectly sorted and/or formatted.
--- /home/runner/work/pipx/pipx/src/pipx/animate.py:before	2020-09-20 04:11:42.338241
+++ /home/runner/work/pipx/pipx/src/pipx/animate.py:after	2020-09-20 04:11:52.216611
@@ -1,8 +1,8 @@
+import shutil
 import sys
 from contextlib import contextmanager
 from threading import Event, Thread
 from typing import Generator, List
-import shutil
 
 from pipx.constants import emoji_support
 
--- /home/runner/work/pipx/pipx/src/pipx/shared_libs.py:before	2020-09-20 04:11:42.338241
+++ /home/runner/work/pipx/pipx/src/pipx/shared_libs.py:after	2020-09-20 04:11:52.230354
@@ -1,8 +1,8 @@
+import datetime
 import logging
+import time
 from pathlib import Path
 from typing import List
-import time
-import datetime
 
 from pipx.animate import animate
 from pipx.constants import PIPX_SHARED_LIBS, WINDOWS
```

The `flake8-isort` plugin for flake8 is less verbose but not as helpful.  You'd probably have to just run isort yourself in order to fix things.
Its output looks like this:
```
nox > flake8 src/pipx tests noxfile.py get-pipx.py setup.py generate_docs.py
src/pipx/animate.py:5:1: I001 isort found an import in the wrong position
src/pipx/shared_libs.py:4:1: I001 isort found an import in the wrong position
src/pipx/shared_libs.py:5:1: I001 isort found an import in the wrong position
```

**Comment by spazm** [comment]
configuring isort to use the black config keeps them from fighting.  `isort --profile black`.  In my own project I have isort configured in `pyproject.toml` next to my black config.

e.g.: `pyproject.toml`:
```toml
[tool.black]
line-length = 100
[tool.isort]
line_length = 100
profile = "black"
```
