### ISSUE TITLE
add flake8-bugbear to automated tests

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#258]
**How would this feature be useful?**

From flake8-bugbear docs

> A plugin for Flake8 finding likely bugs and design problems in your program. Contains warnings that don’t belong in pyflakes and pycodestyle:

**Describe the solution you'd like**

Add to `noxfile.py` which will then automatically be used in the `lint` session.

**Comment by rpdelaney** [comment]
This can be achieved with [flake8-bugbear](https://pypi.org/project/flake8-bugbear/)
