### ISSUE TITLE
move source code from `pipx` to `src/pipx` directory 

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#259]
**How would this feature be useful?**

Moving pipx's source to a directory that is hard/impossible to import accidentally will solve confusion during development and use of pipx.

**Describe the solution you'd like**

Moving to the `src/pipx` directory will make it harder to accidentally run with an unexpected installation of pipx since imports will fail if the local package is not installed. It will also makes sense at a high level for the folder names, i.e. `docs`, `tests`, `src`.

**Comment by itsayellow** [comment]
One question, is there one python package repository directory layout that's more canonical than the others, or a couple that are equally valid?

I've seen this src/<package_name> and also other layouts on equally respectable packages.  Just wondering.

**Comment by gaborbernat** [comment]
You really have either src or non-src layout AFAIK. If you want to test packaging issues/coverage then the src layout is the path to go. Otherwise if you don't care about those two for your library you can use the non-src layout in my experience.

**Comment by cs01** [comment]
I have seen some threads on it over the years, and I recently came across https://hynek.me/articles/testing-packaging/ and decided to switch to src layout. In the past I ran into this issue with pipx, where I was testing my system pipx rather than the source code I had modified. While it has since been fixed, it always felt fragile so making the `src` dir explicit will make it less fragile.
