### ISSUE TITLE
How to upgrade pip (stop warnings about pip version)

### ISSUE THREAD

**Issue by jaraco** [pipxproject/pipx#264]
I went to install another command (towncrier) today, and when I did, I was getting warnings about the pip version:

```
setuptools master $ pipx install towncrier                                                                                              
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
  installed package towncrier 19.2.0, Python 3.8.0
  These apps are now globally available
    - towncrier
done! ✨ 🌟 ✨
```

I'd like not to have these warnings. I tried upgrading pip, but it's a shared dependency.

```
setuptools master $ ~/.local/pipx/venvs/towncrier/bin/python -m pip --version                                                           
pip 19.2.3 from /Users/jaraco/.local/pipx/shared/lib/python3.8/site-packages/pip (python 3.8)
setuptools master $ ~/.local/pipx/venvs/towncrier/bin/python -m pip install -U pip                                                      
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Not uninstalling pip at /Users/jaraco/.local/pipx/shared/lib/python3.8/site-packages, outside environment /Users/jaraco/.local/pipx/venvs/towncrier
    Can't uninstall 'pip'. No files were found to uninstall.
Successfully installed pip-19.3.1
setuptools master $ pipx uninstall towncrier                                                                                            
uninstalled towncrier! ✨ 🌟 ✨
setuptools master $ pipx install towncrier                                                                                              
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
done! ✨ 🌟 ✨g package 'towncrier'
  installed package towncrier 19.2.0, Python 3.8.0
  These apps are now globally available
    - towncrier
```

How does one upgrade pip for pipx?

**Comment by jaraco** [comment]
Looks like one can use `~/.local/pipx/shared/bin/pip` to upgrade that env.

```
setuptools master $ ~/.local/pipx/shared/bin/pip install -U pip                                                                         
Collecting pip
  Using cached https://files.pythonhosted.org/packages/00/b6/9cfa56b4081ad13874b0c6f96af8ce16cfbc1cb06bedf8e9164ce5551ec1/pip-19.3.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-19.3.1
setuptools master $ pipx uninstall towncrier; pipx install towncrier                                                                    
uninstalled towncrier! ✨ 🌟 ✨
done! ✨ 🌟 ✨
  installed package towncrier 19.2.0, Python 3.8.0
  These apps are now globally available
    - towncrier
```

Is that the recommended way to manage this pip version? Perhaps pipx could offer a command or command option to handle this behavior?

**Comment by jaraco** [comment]
This is all with `pipx` `0.14.0.0`.

**Comment by cs01** [comment]
I'm thinking the way to go here is to have pipx ensure the shared libs are at their latest version every time something is installed or run with pipx. 

This adds a slight delay to every command, but I *think* that is better than growing the api and adding a new command such as `pipx upgrade-shared-libs`, because that sort of requires the user to understand an implementation detail of pipx. Any thoughts @pipxproject/maintainers?

**Comment by uranusjr** [comment]
A subcommand to upgrade pip etc sounds OK to me, although pipx should set `PIP_DISABLE_PIP_VERSION_CHECK` regardless. It can emit something else, but pip’s version message if unhelpful.

**Comment by cs01** [comment]
`PIP_DISABLE_PIP_VERSION_CHECK` will be a good addition, thanks. But if we hide the pip version warning, what motivation will users have to upgrade shared libs?

**Comment by cs01** [comment]
Instead of trying to upgrade during every single invocation, we could instead have pipx check the last modified date of the shared pip. If the last modified date is older than some threshold, say 1 month, try to upgrade it (and `touch` it just to be sure it's marked as modified). 

If `pipx upgrade` or `upgrade-all` is run, it already tries to upgrade shared libs. Maybe we could just document that it does this, and avoid adding a new subcommand.

**Comment by flutterq** [comment]
[[Solved] WARNING: Value for scheme.platlib does not match. Please report this
](https://exerror.com/solved-warning-value-for-scheme-platlib-does-not-match-please-report-this/)
