### ISSUE TITLE
travis unix linux builds can't find gcc sometimes

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#266]
**Describe the bug**
Travis linux builds seem to fail occasionally.  The culprit seems to be packages that need gcc to install cannot find gcc.
> unable to execute 'gcc': No such file or directory
>  error: command 'gcc' failed with exit status 1

**How to reproduce**

Run code through Travis CI tests

**Expected behavior**

if local tests pass, they should pass on Travis, but often they fail.

**Comment by itsayellow** [comment]
https://travis-ci.org/pipxproject/pipx/builds/604553890?utm_source=github_status&utm_medium=notification

That one seems to have a passing test for python3.6, and a failing one for python3.7.  The failing test has the missing gcc problem.

Is this a Travis problem?

**Comment by itsayellow** [comment]
Could this have anything to do with us removing sudo from .travis.yml ? #243

**Comment by itsayellow** [comment]
I just saw a weird error running `make test` on my local computer, similar but different, while a test was trying to install `black`.
```
  In file included from regex_3/_regex.c:48:
  /usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m/Python.h:25:10: fatal error: 'stdio.h' file not found
  #include <stdio.h>
           ^~~~~~~~~
  1 error generated.
  error: command '/Library/Developer/CommandLineTools/usr/bin/clang' failed with exit status 1
```
Oddly the other python versions worked fine.

**Comment by itsayellow** [comment]
This seems to happen in particular with the linux python 3.7 tests.

That one uses `dist: xenial` so I tried removing it to see if that helped.  It did not help.

**Comment by michaeljoseph** [comment]
https://github.com/psf/black/issues/1112 👀
