### ISSUE TITLE
recently force pushed to master

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#270]
Just a notice that I recently force pushed to master since a PR was merged to master without being squashed into one commit first. I did this to keep the commit history on the master branch clean. This was a one time mix up that will not be a common thing in pipx (new maintainers are coming up to speed on pipx’s conventions). Sorry for the inconvenience. The content is identical, but it cleaned up some merge history from a pull request that wasn't squashed. 

Pull requests 251, 260, and 247 were rebased and squashed into three commits instead of a few dozen. The original commit history can be found in the branch `master-not-squashed` in case you need it. You can diff the two branches and see they are identical. I'll erase that branch after a few weeks.

The new HEAD of master is 18eb430d7b7dfd3f3f1161cd8efc15fb74aee994. There were three commits rebased onto "Change venv_metadata_inspector to support venv python 3.5+" (ba6ce46830c381018195211c251e9aa0b7d8103e). 

Outstanding pull requests may have to rebase onto origin/master:
```
git checkout <branch>
git fetch
git rebase origin/master
# if you hit conflicts, you can probably run `git rebase --skip` several times and it will end up in the correct state
# confirm everything looks good, then...
git push origin <branch> --force
```

**Comment by itsayellow** [comment]
If I'm on my fork, do I really want the following?
```
git checkout <branch>
git fetch upstream
git rebase upstream/master
git push origin <branch> --force
```

**Comment by cs01** [comment]
The master branch of pipx had its history rewritten, so all pull requests will need to rewrite theirs as well. AFAIK a rebase is the best way to do it, but if you prefer a different way that’s fine. One way or another you are going to have to force push to your pull request’s branch.

**Comment by itsayellow** [comment]
No, I don't know a better way, just making sure that the instructions aren't different if I'm working in my fork vs. with pipxproject/pipx.

**Comment by cs01** [comment]
Oh sorry, yeah you will have to do this too even if you’re on your own fork since it was forked from the master pipx branch.

**Comment by itsayellow** [comment]
But do I need to replace some of the instructions at the top with `upstream`?  Are the instructions at top only if I'm working with pipxproject/pipx?

**Comment by cs01** [comment]
Looks like you got it working, LMK if you are still having trouble.

I just changed repository permissions to only allow "squash merging" and to disallow "merge commits", so there is no confusion in the future.

**Comment by itsayellow** [comment]
😄 I just went and found how to only allow "squash merging" and disallow others, and was about to suggest it.  Then I saw you had already done it.

**Comment by itsayellow** [comment]
One of the tricky parts of the rebase was file renaming in amongst the changes.  And for some reason I always had to go back in and eliminate some of the `animate.py` squashed commits that showed up even after rebasing.

**Comment by cs01** [comment]
All relevant PRs have been rebased and merged, closing.
