### ISSUE TITLE
Installation ends with "Could not find package cowsay. Is the name correct?"

### ISSUE THREAD

**Issue by kradalby** [pipxproject/pipx#273]
**Describe the bug**
I just started to test pipx, was very excited, but every installation ends with:

`Could not find package cowsay. Is the name correct?`

I have tried to install: ansible, black, cowsay

**How to reproduce**

MacOS 10.15.1 (19B88)
Python 3.7.5 from Brew
pipx version 0.14.0.0

Install pipx:
`python3 -m pip install --user pipx`
`python3 -m pipx ensurepath`

```
$ pipx install cowsay --verbose
pipx > (run_pipx_command:134): Virtual Environment location is /Users/kradalby/.local/pipx/venvs/cowsay
pipx > (run:97): running /usr/local/opt/python/bin/python3.7 -m venv --without-pip /Users/kradalby/.local/pipx/venvs/cowsay
pipx > (run:97): running /Users/kradalby/.local/pipx/venvs/cowsay/bin/python -m pip install cowsay
Collecting cowsay
  Using cached https://files.pythonhosted.org/packages/d4/68/af23fbf90493044fc2ea83cd62923b9952c2d38eeeab83e0c016706bfbc8/cowsay-2.0.3-py2.py3-none-any.whl
Installing collected packages: cowsay
Successfully installed cowsay-2.0.3
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pipx > (rmdir:16): removing directory /Users/kradalby/.local/pipx/venvs/cowsay

pipx > (rmdir:16): removing directory /Users/kradalby/.local/pipx/venvs/cowsay
Could not find package cowsay. Is the name correct?
```

```
ls ~/.local/pipx/venvs/
<empty>
```

```
$ cowsay
Failed to execute process '/Users/kradalby/.pip3/bin/cowsay'. Reason:
The file '/Users/kradalby/.pip3/bin/cowsay' specified the interpreter '/Users/kradalby/.local/pipx/venvs/cowsay/bin/python', which is not an executable command.
```

The exact same thing happens with ansible and black. It also happens if I use `run`.

**Expected behavior**

Package should install, and be available in path.

I am curious about the line were it seems to remove the directory, is it because of the pip warning 👀 ? I have tried to upgrade pip, but cant get it to go away.

**Comment by itsayellow** [comment]
I don't think this has anything to do with the version of pip.  It looks like during the installation an internal exception is being thrown and thus pipx is removing the virtual environment.  But somehow you still end up with the binary pointing to the nonexistent virtual environment.

You do have a non-standard binary location for cowsay: `/Users/kradalby/.pip3/bin/cowsay`.  Normally it should be `/Users/kradalby/.local/bin/cowsay`.  Is that on purpose?  Do you have your PIPX_BIN_DIR environment variable set to  `/Users/kradalby/.pip3/bin`?

I'm wondering if you have already installed cowsay normally using pip3, and it is conflicting with the attempt to install using pipx.

If have been trying to install things using pipx that you have already installed using pip, you could try installing a new package using pipx (not installed using pip) such as `pycowsay`.  See if that works better.

It is also possible that pipx cannot write to `/Users/kradalby/.local` or `/Users/kradalby/.local/bin`?

**Comment by cs01** [comment]
> If have been trying to install things using pipx that you have already installed using pip, you could try installing a new package using pipx (not installed using pip) such as pycowsay. See if that works better.

Agreed, it looks like something was installed with another version of Python/pip that installed to `/Users/kradalby/.pip3/bin`. That doesn't explain why pipx fails with that error (maybe it's a pipx bug?), but it would explain 

```
Failed to execute process '/Users/kradalby/.pip3/bin/cowsay'. Reason:
The file '/Users/kradalby/.pip3/bin/cowsay' specified the interpreter '/Users/kradalby/.local/pipx/venvs/cowsay/bin/python', which is not an executable command.
```

Make sure you remove the various binaries from `.pip3/bin`, I think they are left on your path which makes it confusing whether it's a pipx-installed program or not.

**Comment by kradalby** [comment]
I forgot to add:

Before I started to test pipx, I completely removed my pip directory (.pip3).

As far as I can remember, I have never installed cowsay or pycowsay before, however black and ansible were installed in .pip3 earlier.

`.local/bin` is more or less empty.
```
$ ls ~/.local/bin
elm-language-server-exe
```

Tried to install pycowsay:
```
pipx install pycowsay --verbose
pipx > (run_pipx_command:134): Virtual Environment location is /Users/kradalby/.local/pipx/venvs/pycowsay
pipx > (run:97): running /usr/local/opt/python/bin/python3.7 -m venv --without-pip /Users/kradalby/.local/pipx/venvs/pycowsay
pipx > (run:97): running /Users/kradalby/.local/pipx/venvs/pycowsay/bin/python -m pip install pycowsay
Collecting pycowsay
  Using cached https://files.pythonhosted.org/packages/ee/a6/8fb6d569c59e0e3622f10ae39594cbc57f8e5f36517291e221bd156002ef/pycowsay-0.0.0.1-py3-none-any.whl
Installing collected packages: pycowsay
Successfully installed pycowsay-0.0.0.1
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
pipx > (rmdir:16): removing directory /Users/kradalby/.local/pipx/venvs/pycowsay

pipx > (rmdir:16): removing directory /Users/kradalby/.local/pipx/venvs/pycowsay
Could not find package pycowsay. Is the name correct?
```

Also tried to remove Python and delete all `site-packages` folders I can find and then reinstall. Still same.

The suggestions in issue #274 seems sensible for this type of debugging.

**Comment by kradalby** [comment]
Any updates?

**Comment by cs01** [comment]
I cannot reproduce with Python 3.7.5, but judging by the upvotes on your initial comment other people can.

The script responsible for 
finding apps is  https://github.com/pipxproject/pipx/blob/5d8523cc147a38e271bfa1a51dedac915ddb0664/src/pipx/venv_metadata_inspector.py. We could add a flag to that script to be more verbose and print extra information to stderr (stdout shouldn't be used because it is structured output parsed by pipx).

**Comment by kradalby** [comment]
I think I just figured it out, it looks like having `PIP_USER` set to 1 breaks pipx (and many other things). Sorry about that guys, it was dug deep down in a config I had to "work around pip limits" before I discovered pipx.

**Comment by cs01** [comment]
Np, this will be a good thing to capture in pipx's documentation.

**Comment by cs01** [comment]
Actually, pipx should test if that variable exists and unset it when running commands in venvs.

**Comment by cs01** [comment]
Looks like using the `--user` flag in a venv (as was happening in this circumstance) will automatically fail in an upcoming version of pip. https://discuss.python.org/t/should-pip-install-user-install-in-a-venv-install-to-the-global-user-path/2803

**Comment by uranusjr** [comment]
I was just about to mention it before your comment pop right above me :p

Both `--user` and `PIP_USER` would cause an explicit error in pip 20.0:

```
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
```

Reading this issue makes me kind of worry maybe we’ll break people’s workflow though. I’ll continue the discussion on Discourse.

**Comment by pfmoore** [comment]
I agree with @uranusjr the pip change won't make this work any better but will make it easier to work out what went wrong. As you say, the correct fix is to unset `PIP_USER`. It's worth noting, though, that if the user has `user` set in a pip config file, then they'll still get bitten by this, but they'll have other problems with venvs anyway, so I wouldn't be too worried about that.

You may also want to look into pip's `--isolated` flag, although this may have its own issues as it'll make pip ignore things like globally configured proxies and local indexes, which may not be what you want.

**Comment by cs01** [comment]
I agree too. The error message @kradalby received may have presented a more obvious reason for the error.
