### ISSUE TITLE
Log Exceptions, Errors to file with traceback info

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#274]
**How would this feature be useful?**
We catch any `Exception` in `install()` but are silent about it--there is no way to know what happened.

For debugging user bugs, this would be extremely helpful (see #273 for example.)

**Describe the solution you'd like**
Save the caught exception using something like `except Exception as e` and then use either a output what it is using plain `repr(e)` or more sophisticated printout using the `traceback` library for example.  We could do this only if `pipx --verbose` is on.

**Describe alternatives you've considered**
None.

I think any more information than the current "no information" would be helpful

**Comment by cs01** [comment]
Great suggestion. We could also log verbose output, or just errors, to a file regardless of what the user does. The error message could say "see logs at ..." if an error was caught, rather than dumping Python exceptions to the user's CLI (that should never happen).

**Comment by itsayellow** [comment]
I think a rotating log that saves the last N pipx invocations sounds excellent.
