### ISSUE TITLE
How to install a package via git together with a dependency

### ISSUE THREAD

**Issue by aborruso** [pipxproject/pipx#275]
Hi,
I need to install a package via

```
pipx install --spec git+https://github.com/saulpw/visidata.git@develop visidata
```

I would like to install at the same time lxml, that is dependency.

Thank you

**Comment by cs01** [comment]
Does injecting work?

```
pip install ... visidata
pipx inject lxml
```

**Comment by itsayellow** [comment]
Also, even if installing via git, the main package should correctly be specifying its dependencies (and they will be installed by pipx.)
