### ISSUE TITLE
command not found: pipx

### ISSUE THREAD

**Issue by behrtam** [pipxproject/pipx#283]
I installed pipx on macOS 10.13 with python3 installed via brew. If I rerun the commands it looks like this ... but I still can't run the command.

```
❯ python3 -m pip install --user pipx
Requirement already satisfied: pipx in ./Library/Python/3.7/lib/python/site-packages (0.14.0.0)
Requirement already satisfied: argcomplete<2.0,>=1.9.4 in ./Library/Python/3.7/lib/python/site-packages (from pipx) (1.10.3)
Requirement already satisfied: userpath in ./Library/Python/3.7/lib/python/site-packages (from pipx) (1.3.0)
Requirement already satisfied: click in ./Library/Python/3.7/lib/python/site-packages (from userpath->pipx) (7.0)

❯ python3 -m pipx ensurepath
The directory `/Users/randomuser/.local/bin` is already in PATH. If you are sure you want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go! ✨ 🌟 ✨

❯ echo $PATH
/Users/randomuser/.nvm/versions/node/v12.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/randomuser/.local/bin

❯ tree .local
.local
├── bin
└── pipx
    └── venvs

3 directories, 0 files

❯ python3 --version
Python 3.7.5

❯ pipx
zsh: command not found: pipx```

**Comment by behrtam** [comment]
Had a fresh look and fixed it with:
```
export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"
```

**Comment by nicolaevladescu** [comment]
That's all great but this is a manual workaround.

The correct approach should be `python3 -m pipx ensurepath --force` like it was suggested, this is how i fixed it.

**Comment by henrytien** [comment]
`export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"` thanks, work for me.

**Comment by luckman212** [comment]
Just a quick note that another way to get the `USER_BASE` dir is `python3 -m site --user-base`

**Comment by mechanicals** [comment]
> Had a fresh look and fixed it with:
> 
> ```
> export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"
> ```

This just works !!!

**Comment by mechanicals** [comment]
> Had a fresh look and fixed it with:
> 
> ```
> export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"
> ```

This just works!

**Comment by 9473** [comment]
> Had a fresh look and fixed it with:
> 
> ```
> export PATH="${PATH}:$(python3 -c 'import site; print(site.USER_BASE)')/bin"
> ```

It works! thx!!
