### ISSUE TITLE
Cannot install awslogs

### ISSUE THREAD

**Issue by setu4993** [pipxproject/pipx#284]
**Describe the bug**

Trying to install [`awslogs`](https://github.com/jorgebastida/awslogs) (as `pipx install awslogs`), but it shows the error:
```
ERROR: botocore 1.13.28 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.

Could not find package awslogs. Is the name correct?
```
The error in `python-dateutil` conflict arises from botocore, https://github.com/boto/botocore/issues/1872, but I can successfully install `awslogs` if I create a new virtual environment with virtualenvwrapper.

**How to reproduce**

Output from verbose:
```
pipx install awslogs --verbose
pipx > (run_pipx_command:134): Virtual Environment location is /Users/setu/.local/pipx/venvs/awslogs
pipx > (run:97): running /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7 -m venv --without-pip /Users/setu/.local/pipx/venvs/awslogs
pipx > (run:97): running /Users/setu/.local/pipx/venvs/awslogs/bin/python -m pip install awslogs
Collecting awslogs
  Using cached https://files.pythonhosted.org/packages/45/be/28fe3276045c564aeb79fc74ba436201ded4a17d964d8be54adb72a0c873/awslogs-0.11.0-py2.py3-none-any.whl
Processing ./Library/Caches/pip/wheels/7c/06/54/bc84598ba1daf8f970247f550b175aaaee85f68b4b0c5ab2c6/termcolor-1.1.0-cp37-none-any.whl
Collecting jmespath<1.0.0,>=0.7.1
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting boto3>=1.2.1
  Using cached https://files.pythonhosted.org/packages/67/17/567f679dac6ec93611ce05637094e9736afa40e41c9ed0aaefd90de6f7e8/boto3-1.10.28-py2.py3-none-any.whl
Collecting python-dateutil>=2.4.0
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting s3transfer<0.3.0,>=0.2.0
  Using cached https://files.pythonhosted.org/packages/16/8a/1fc3dba0c4923c2a76e1ff0d52b305c44606da63f718d14d3231e21c51b0/s3transfer-0.2.1-py2.py3-none-any.whl
Collecting botocore<1.14.0,>=1.13.28
  Using cached https://files.pythonhosted.org/packages/8e/b3/ab9044d3aa14208f5b6f69665d5f82ad9b028809666e4e70dac1ab0bfd3a/botocore-1.13.28-py2.py3-none-any.whl
Collecting six>=1.5
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Collecting docutils<0.16,>=0.10
  Using cached https://files.pythonhosted.org/packages/22/cd/a6aa959dca619918ccb55023b4cb151949c64d4d5d55b3f4ffd7eee0c6e8/docutils-0.15.2-py3-none-any.whl
Collecting urllib3<1.26,>=1.20; python_version >= "3.4"
  Using cached https://files.pythonhosted.org/packages/b4/40/a9837291310ee1ccc242ceb6ebfd9eb21539649f193a7c8c86ba15b98539/urllib3-1.25.7-py2.py3-none-any.whl
ERROR: botocore 1.13.28 has requirement python-dateutil<2.8.1,>=2.1; python_version >= "2.7", but you'll have python-dateutil 2.8.1 which is incompatible.
Installing collected packages: termcolor, jmespath, six, python-dateutil, docutils, urllib3, botocore, s3transfer, boto3, awslogs
Successfully installed awslogs-0.11.0 boto3-1.10.28 botocore-1.13.28 docutils-0.15.2 jmespath-0.9.4 python-dateutil-2.8.1 s3transfer-0.2.1 six-1.13.0 termcolor-1.1.0 urllib3-1.25.7
pipx > (rmdir:16): removing directory /Users/setu/.local/pipx/venvs/awslogs

pipx > (rmdir:16): removing directory /Users/setu/.local/pipx/venvs/awslogs
Could not find package awslogs. Is the name correct?
```
**Expected behavior**

Installation should have completed successfully and a new environment should've been created.

**Comment by setu4993** [comment]
https://github.com/boto/botocore/issues/1872 has now been resolved, and `awslogs` can be installed with `pipx`. However, still doesn't solve the issue raised here, since `pipx` could not originally resolve the requirements and provided an error message that was not really helpful (`Could not find package awslogs. Is the name correct?`).

**Comment by clbarnes** [comment]
Thanks for spotting this failure condition - seems like it would be more accurate to say "could not *resolve* package...", although no more helpful. Can we easily detect this kind of failure from pipx's side (i.e. without having to `except Exception` and parse the trace)? Or is it just a case of noting that it's a possibility in the error message?

**Comment by setu4993** [comment]
+1 on would be more accurate to say 'could not resolve'. Unsure about how pipx resolves dependencies, so can't say anything more on that end.

**Comment by itsayellow** [comment]
Package resolution is done using pip.  The ERROR visible is a pip error that pipx has passed forward.

Current pipx behavior (0.15.1.2) would be to show the original pip ERROR and add the statement "Error installing awslogs."

Without a lot of parsing of pip error messages, and layering on pipx errors on top of them, this seems like a good solution to me.  It shows the immediate problem and no longer says `Could not find package awslogs.  Is the name correct?`.

**Comment by cs01** [comment]
> boto/botocore#1872 has now been resolved, and awslogs can be installed with pipx.

Can this issue be closed and a new one opened if there is still something wrong/misleading about pipx's API?

**Comment by setu4993** [comment]
@itsayellow, @cs01 : The updated current behavior seems like a good solution to me. Closing this issue.
