### ISSUE TITLE
Travis CI Windows intermittent failures

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#296]
**Describe the bug**

pipx's Windows tests on Travis sometimes fail during initial setup steps

```
Failures
 - python - python not installed. The package was not found with the source(s) listed.
 Source(s): 'https://chocolatey.org/api/v2/'
 NOTE: When you specify explicit sources, it overrides default sources.
If the package version is a prerelease and you didn't specify `--pre`,
 the package may not be found.
Version was specified as '3.7'. It is possible that version 
 does not exist for 'python' at the source specified.
Please see https://chocolatey.org/docs/troubleshooting for more 
 assistance.
The command "choco install python --version $TRAVIS_PYTHON_VERSION" failed and exited with 1 during .
```

**How to reproduce**

This doesn't seem to be reliable, but triggering a build sometimes causes the failure.

This recently occurred in https://github.com/pipxproject/pipx/pull/268, where everything passed except the windows build (https://travis-ci.org/pipxproject/pipx/jobs/625564662?utm_medium=notification&utm_source=github_status). I also saw it once after a merge to pipx's master branch.

**Expected behavior**

Travis Windows installation should succeed, or fail with a valid test error, not a setup error.

cc @jayvdb @rajibmitra

**Comment by itsayellow** [comment]
Obsolete since we don't use Travis anymore.
