### ISSUE TITLE
Can I place PIPX_BIN_DIR inside PIPX_HOME?

### ISSUE THREAD

**Issue by halloleo** [pipxproject/pipx#331]
I would like to place PIPX_BIN_DIR inside PIPX_HOME. I.e.:

    PIPX_BIN_DIR=$HOME/pipx/bin
    PIPX_HOME=$HOME/pipx

Is this OK or can this cause trouble at some stage?

**Comment by uranusjr** [comment]
FWIW that’s exactly what I do and I haven’t noticed any problems.

**Comment by itsayellow** [comment]
Short answer: It will probably be fine, but it's not recommended.  

`PIPX_HOME` is used by pipx for internal operations, so there's a non-zero danger that in the future your sub-directory could conflict with something that pipx does.  Right now I don't think there would be any conflict however, and it should be ok.

**Comment by halloleo** [comment]
Thanks for the info. I will try to go with that scheme.

I think it could be worth considering to set `PIPX_BIN_DIR` by default to `PIPX_HOME` if `PIPX_HOME` is set...

**Comment by halloleo** [comment]
I am using this set up now for a little while and it seems to work for me too. I close the issue for now.
