### ISSUE TITLE
Deploy docs: GitHub Action triggered by release

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#333]
**How would this feature be useful?**

It would be cool if new documentation could automatically run whenever we make a release.

Implementing this action might help us gain experience and confidence to implement and Action to automatically publish to PyPI in the future.

**Describe the solution you'd like**

I've started investigating GitHub Actions, and this Issue is to track figuring out how to make an Action that would build the site using mkdocs and deploy, triggered by a Release.

**Describe alternatives you've considered**

The current way of generating and publishing the docs is fine, but it's another thing that needs to be remembered and executed properly each time.  Triggering automatically on release would remove one more thing to do by hand, hopefully ensuring it's done consistently and accurately.

**Comment by itsayellow** [comment]
My experiment repo is here:
https://github.com/itsayellow/action-test

The Action that shows up when you search the GitHub actions "marketplace" for mkdocs is:
https://github.com/marketplace/actions/deploy-mkdocs

However (at least currently) there's some issue with GitHub Actions that prevents pushing using this Action from successfully generating a new GitHub page:
https://github.community/t5/GitHub-Actions/Github-action-not-triggering-gh-pages-upon-push/m-p/26869/highlight/true#M301

Which led me to this Action, which seems to be far more actively developed, and also has a workaround for the above issue.
https://github.com/marketplace/actions/github-pages-action
https://github.com/peaceiris/actions-gh-pages

**Comment by itsayellow** [comment]
Looks like [mkdocs-deploy-gh-pages](https://github.com/mhausenblas/mkdocs-deploy-gh-pages) just fixed their deploy problem, and now it should properly trigger deployment of pages from the branch
https://github.com/mhausenblas/mkdocs-deploy-gh-pages/pull/4

**Comment by itsayellow** [comment]
Another interesting method is to use the `workflow_dispatch` trigger, which can trigger from github web ui, and even accept arguments from the web ui!

https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

https://docs.github.com/en/actions/configuring-and-managing-workflows/configuring-a-workflow#manually-running-a-workflow

**Comment by cs01** [comment]
This is great, thank you for taking the initiative on this.
