### ISSUE TITLE
executing `pipx install <package>` in `PIPX_HOME` break the `package_or_url` in pipx_metadata.json

### ISSUE THREAD

**Issue by MisLink** [pipxproject/pipx#337]
**Describe the bug**
These lines https://github.com/pipxproject/pipx/blob/a994dfe229149b93f254cb562f53c7b059e24304/src/pipx/venv.py#L367-L368
`pkg_path.exists()` return `True` because the same name folder is created in `PIPX_HOME`. Maybe check `is_absolute()` first?

**How to reproduce**
execute `pipx install <pkg>` in `PIPX_HOME`.

**Expected behavior**
create the correct `package_or_url`.

**Comment by itsayellow** [comment]
On a recent pipx this seems to work as expected.  If I go into `PIPX_HOME` and try to install a package that already exists there as a directory, I get:
```
> pipx install nox
'nox' already seems to be installed. Not modifying existing installation in '/Users/mclapp/.local/pipx/venvs/nox'. Pass '--force' to force installation.
```

If what you want is to have the local source for a pipx install in the same directory (`PIPX_HOME`) where pipx stores its venvs, then this will not be supported by pipx.
