### ISSUE TITLE
My package can't be installed with “pipx”

### ISSUE THREAD

**Issue by mludvig** [pipxproject/pipx#350]
I've got a Python project [aws-ssm-tools](https://github.com/mludvig/aws-ssm-tools) that uses `setup.py` for packaging. It comes with 3 scripts: `ssm-tunnel`, `ssm-session` and `ssm-copy`.

It can be installed with `pip install aws-ssm-tools` that puts the scripts to `~/.local/bin/` as expected.

However when I try to install it with `pipx` it fails:

```bash
~ $ pipx install aws-ssm-tools

No apps associated with package aws-ssm-tools. Try again with '--include-deps' 
to include apps of dependent packages, which are listed above. If you are 
attempting to install a library, pipx should not be used. Consider using pip or 
a similar tool instead.
```

I have the scripts specified in [`setup.py`](https://github.com/mludvig/aws-ssm-tools/blob/master/setup.py):

```python
SCRIPTS = [
    'ssm-session',
    'ssm-copy',
    'ssm-tunnel',
    'ssm-tunnel-updown.dns-example',
]

setup(
    name="aws-ssm-tools",
    version=VERSION,
    packages=find_packages(),
    scripts=SCRIPTS+[
        'ssm-tunnel-agent'
    ],
    # ...
)
```

What else do I have to do to make `pipx` happy?

**Comment by uranusjr** [comment]
I believe pipx only recognises `entry_points`, not `scripts`. Use that instead and pipx should work.

**Comment by cs01** [comment]
@mludvig did @uranusjr's suggestion work for you?

**Comment by mludvig** [comment]
Thanks for the hint, I have yet to figure out how to convert my stand alone scripts to `entry_points` based ones. I guess it shouldn't be too difficult...

**Comment by mludvig** [comment]
@uranusjr thanks for your help, it works and I can now install the package with `pipx` :)
