### ISSUE TITLE
Install a package under another name

### ISSUE THREAD

**Issue by halloleo** [pipxproject/pipx#355]
It would be great to install a package so taht its command has a different name.

**How would this feature be useful?**

This would for example allow the same command to run with different injected packages. `jupyter` is a good example for this: You might want one jupyter command with `pandas` and `seaborn` and the like, and another jupyter command with `selenium`, `scrapy` and similar...

**Describe the solution you'd like**

A command line option `--name-as` which could be used if the package exposes only one command or an option `--name-file` taking a file with name mappings for all the commands a package exposes.

**Comment by funkyfuture** [comment]
the thing is that a python package can define multiple `console_scripts` entrypoints that define the eventually available commands.

**Comment by halloleo** [comment]
I understand, but this _could_ be addressed with a names file. 

E.g. for the [`xonsh`](https://pypi.org/project/xonsh/) package defiining the scripts  `xon.sh`, `xonsh`, `xonsh-cat` one could have a name file with a content like:

    dataxonsh                # name of the new environment
    dataxon.sh=xon.sh        # mapping for the first script
    dataxonsh=xonsh          # mapping for the second script
    dataxonsh-cat=xonsh-cat  # ...

This would mean that the new venv "dataxonsh" links the internat script `xon.sh` to `dataxon.sh`,  `xonsh` to `dataxonsh` and so on.

In the new venv you could inject things like `pandas` and `numpy` without affecting the normal xonsh. Happy days... :-)

**Comment by itsayellow** [comment]
Would #445 accomplish what you're looking for?

**Comment by halloleo** [comment]
Yep, looks great. Will do the job if all console_scripts get suffixed. 

I'll test this when available on pypi and reprt back. 

Much easier system then my proposed names file...

**Comment by halloleo** [comment]
Have tested it: The `--suffix` option does the job perfectly. Thanks a lot.
