### ISSUE TITLE
Install metapackages with `requirements.txt` files

### ISSUE THREAD

**Issue by salotz** [pipxproject/pipx#357]
Introduction
=========

`pip` has the very useful feature to install a listing of packages from `requirements.txt` files. `pipx` should have something similar.

The main use case comes up when you want to install standalone packages with plugins.

Concrete Example
-------------------------

A concrete example are [jinja2 template extensions](https://jinja.palletsprojects.com/en/2.11.x/extensions/) in the [cookiecutter project](https://cookiecutter.readthedocs.io/en/1.7.0/advanced/template_extensions.html).

If you want to use a template extension plugin when writing your templates you can no longer use any plugins that aren't already bundled with the `cookiecutter` project. For example if you want to use the extension for [dates](https://github.com/hackebrot/jinja2-time) you would need to install it in the same environment as `cookiecutter` which wouldn't be possible with `pipx` without using the `inject` command. (Coincidentally, `jinja2_time` is bundled with `cookiecutter` already but it need not be and there are plenty of others that are aren't that you might want to use.)

Ideally to distribute my cookiecutter template I would just be able to distribute a `requirements.txt` that includes the main package (`cookiecutter`) along with any plugins you would want to use (e.g. `jinja2_time`):

```
cookiecutter
jinja2_time
```

Then the consumer of my template, need not install a python environment and can just run:

```
pipx install -r requirements.txt
```

Problems
-------------

Because you now have multiple projects and the entry points to these might overlap with other `pipx` installed packages there will have to be some way of specifying which packages entry points you want to install.

Using the example above if I already had `pipx install cookiecutter`  previously and then I install the `requirements.txt` above the first installation environment will either have to be over-written or modified which is undesirable either way.

Solutions
-------------

###  Specify which package to install entry points for

Just to illustrate the idea you could add a special comment in the `requirements.txt` that tells `pipx` which package to install entry points for, the other's will not have theirs installed.

```
cookiecutter # pipx: install_entrypoints
jinja2_time
```

You could also ignore some:

```
cookiecutter 
jinja2_time # pipx: ignore_entrypoints
```

This assumes that plugins interact through module imports and not their entry points. I'm okay with excluding packages that interact through their entry points (i.e. the system shell) since that isn't portable anyways.

### Specify an alias for package on install

This would work alongside the first solution and not as an alternative.

First you could specify on command line:

```
pipx installl -r requirements.txt --alias 'cookiecutter_ext'
```

Or in the `requirements.txt` itself, which would be overriden by the CLI one:

```
cookiecutter # pipx: install_entrypoints, alias='cookiecutter_ext'
jinja2_time
```

### non-destructive defaults with option to force

By default if you tried to install: 

```
cookiecutter
jinja2_time
```

And if *any* of the packages already have entry points installed (like `cookiecutter`)  it would fail by default.

```
> pipx install cookiecutter
> pipx install -r requirements.txt
'cookiecutter' is already installed, aborting installation.
Use the '--force' or '-f' command to force installation and replace current one.
```

If you want to override it you can pass the force option:

```
pipx install -f -r requirements.txt
```

This would be the most reasonable option IMO to start with since that would cover probably 90% of use cases where having extra plugins in the environment probably won't screw things up most of the time.

Notes
--------

Using (and abusing) the `requirements.txt` specification isn't necessary. This could be achieved in a cleaner way with another format like a JSON or TOML file for example. The `requirements.txt` is just widely used already. Note option 3 avoids the syntax abuse.

Alternatives
----------------

I've taken a look at `pipx inject` and it is along the same lines but it would be very convenient to have a one liner and a configuration file to just point pipx at.

Alternatives to making plugin metapackages like I have described above include:

Proposal: Make your own metapackage with a `setup.py` and publishing on an index.

Response: This is a lot of work and seems overkill to have an entire git repo just for specifying a couple of packages to be installed together. Especially when you could have a single server with a listing of `requirements.txt` for a whole bunch of metapackages. This is similar to the approach conda-forge uses.

Proposal: Get the maintainers of the package using plugins to have extra targets (e.g. `pip install main[extra]`) in their `setup.py.

Response: This is pretty reasonable and perhaps you should do this in addition to making a metapackage yourself. Ultimately this problem can be solved orthogonally and without coordination between consumers and maintainers of the main package. I.e. you don't have to annoy anyone to make this work.

**Comment by salotz** [comment]
Realized that there is a problem with this for entry points. Editing

**Comment by clbarnes** [comment]
I started working on this some time ago but held off as the venv metadata file changes were going to make it a lot easier. I too started with `requirements.txt`, but as you found, it wasn't much use without the injection information. The branch is here https://github.com/clbarnes/pipx/tree/freeze

My use case was that I have a bunch of python-based tools which I want to install on a bunch of machines, and it would be nice to have a single config file which sets up all my pipx environments, with their injected packages and so on. You could also export such a config file.

I believe the correct way to do this now is basically just reading all the metadata JSON files pipx uses, parse out the key information, and dump that into a file (my preference is TOML, because it's more human-readable than JSON, and more machine-readable than INI and YAML). Then do the reverse to actually create the environments.

**Comment by salotz** [comment]
That's quite a significant difference in my opinion. Your proposing a file format that describes essentially an entire distro which might be a scope creep for pipx. Although that is pretty useful unless your entire environment is python packages your not solving the whole distro/env problem. Maybe there could be a 'batch' mode for that?  On the other hand I tend to agree with using a toml file as you dont have to learn any parsing quirks or guess funny syntax. So if your going to introduce a new file format it's not much more effort to have multiple meta package specs in there. That could be a separate incremental improvement/milestone after the single metapackage as I've described, while keeping that future use case in mind.

**Comment by uranusjr** [comment]
I am personally -1 to this proposal since it makes pipx essentially grow its special package format, and that’s an area where standard Python packaging is perfectly suitable. The same effect can be achieved with “regular” packaging (either with `pip install --with-deps` or re-defining entry points in the meta package). I am inclined to recommend sticking to standard stuff as much as possible.

**Comment by salotz** [comment]
@uranusjr My third proposed solution (and favored minimal solution) doesn't require a new format just some extra command line options. It achieves the goal of this feature request, but not that of "metapackages" which is fine with me.

**Comment by salotz** [comment]
I'll make a separate issue just for this since the title of the issue is tied up in a lot of other questions then.
