### ISSUE TITLE
Support for `pipx install -r requirements.txt`

### ISSUE THREAD

**Issue by salotz** [pipxproject/pipx#359]
Refinement from #357 

Without digressing into defining "metapackages" having support for
installing single environments from `requirements.txt` files would be
very useful. For example, if we want to install a package that can
allow for plugins at runtime (e.g. `cookiecutter`) we might want to
additionally specify some plugin packages to install alongside it and
we would write a requirements.txt file like so:

```
cookiecutter
jinja2_time
```

As discussed in #357 there is an issue with conflicting with
previously installed packages.  To solve this problem I propose some
non-destructive default behavior and a way to override this in the
CLI.

By default if you tried to install that file with `pipx install -r
requirements.txt` pipx would try to install entry points for the first
package in the list that defines them. If that package (in this
example `cookiecutter`) already has entry points installed then it
would fail by default:

```
> pipx install cookiecutter
> pipx install -r requirements.txt
'cookiecutter' is already installed, aborting installation.
Use the '--force' or '-f' command to force installation and replace current one.
```

If you want to override it you can pass the force option:

```
pipx install -f -r requirements.txt
```

Or you can specify an alias:

```
pipx install -r requirements.txt -a cookiecutter_ext
```

**Comment by cs01** [comment]
Thanks for your feedback. We can get pretty close to this behavior with existing APIs. What do you think of
```
pipx install cookiecutter
pipx runpip cookicutter install -r requirements.txt
```

**Comment by funkyfuture** [comment]
or what about `pipx inject <package> -r <requirements-file>`?

**Comment by salotz** [comment]
@cs01 that gets the job done. I would like some option for it at some point, what @funkyfuture proposes is pretty good and doesn't overcomplicate the `pipx install` like I suggested. I'll let you guys decide if you want it :) so I'll close the issue.

Here is a little shell function for it:

```
pipx_inject_requirements () {
    pipx runpip $1 install -r $2
}
```

**Comment by cs01** [comment]
> or what about pipx inject <package> -r <requirements-file>?

this would be do-able with a slight change to pipx

**Comment by Sispheor** [comment]
This works for me:
```
cat requirements.txt | xargs pipx inject <package>
```

But yes it would be better to support it directly as it's a common pip feature.

**Comment by uranusjr** [comment]
The currently WIP #874 may be an alternative solution to this if we can come up with a user-friendly way to create the package JSON file without needing to install them first. (`pipx install --dry-run`, perhaps?)

cc @meowmeowmeowcat

**Comment by andrewcrook** [comment]
I think `pipx install-all` suggests installing a list of packages (more like a brewfile) . While `pipx inject <package> -r <requirements-file>` suggests installing all the dependencies to a package. This would be the equivalent to `pipx runpip <package> install -r requirements.txt` or `cat requirements.txt | xargs pipx inject <package>`.

However, a command to do the following  `git clone` then` pipx install . `Then  `pipx inject <package> -r ./<requirements-file>` and tidy up. Would support non-supporting pipx packages?

**Comment by hanfried** [comment]
Needed to strip out comments, too: `cat requirements.txt | sed -e 's/#.*//' | xargs pipx inject <package>.`

**Comment by dmealo** [comment]
> Thanks for your feedback. We can get pretty close to this behavior with existing APIs. What do you think of
> 
> ```
> pipx install cookiecutter
> pipx runpip cookicutter install -r requirements.txt
> ```

Second command should be `pipx runpip cookiecutter install -r requirements.txt` to fix a simple typo for those that waste a few minutes trying to figure that out like me. :)

**Comment by mukesh-tcb** [comment]
> Thanks for your feedback. We can get pretty close to this behavior with existing APIs. What do you think of
> 
> ```
> pipx install cookiecutter
> pipx runpip cookiecutter install -r requirements.txt
> ```

Thanks
