### ISSUE TITLE
pipx ensurepath should ensure that `pipx` is also in PATH

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#371]
**How would this feature be useful?**

#208 describes a situation where the user installs pipx in a python version and successfully runs `python3 -m pipx ensurepath` as recommended, but ultimately pipx itself is not in the user's path.  This is presumably because the user install of pipx ended up in a directory not in the user's path, which can happen if a non-system python is used (e.g. with pyenv) even if the non-standard python3 binary itself is in the user's path.

**Describe the solution you'd like**

`pipx ensurepath` can verify that `pipx` is in the users PATH, as well as the pipx package binaries directory.  We could either print a warning (most conservative) or add the path to `pipx` to the user's path (least conservative but more helpful).

**Describe alternatives you've considered**

The alternative would be to make sure that the user installs pipx via a system python through education.  But there will always be user-behavior edge cases, so at least a helpful message would be nice to let a person know if they've successfully installed pipx but it is not in their PATH.

**Comment by abstractumx** [comment]
I wonder if ensurepath works even if I install pipx inside a virtual env. (A kind of virtual env inside virtual evn) by running the following commands:
```
$ python3 -m venv myvenv
$ source myvenv/bin/activate
```
Then i run my venv
```
(myvenv) user@linux:~/Desktop$ pip install pip x
```
Whats happen if i run inside myvev the following:
```
(myvenv) user@linux: $pipx ensurepath
```

It will works anyway?
Thank you
