### ISSUE TITLE
Remove emojis by default

### ISSUE THREAD

**Issue by traverseda** [pipxproject/pipx#376]
They don't really have any benefit, support is platform, specific, and they look unprofessional. Also half the time I get broken characters because I don't have the right emoji fonts installed. I don't really need any cutesy icons in my tooling.

I recognize that this is a very subjective thing, and having emojis doesn't really hurt anything, I just don't like them.

I'm not expecting any action to be taken here, just wanted to mention that I think they look bad. Maybe people can vote on this issue to give a better idea of how many people also think they look bad/good?

If you like the emoji please give this comment a thumbs down.

----

The environment variable `USE_EMOJI` will allow you to opt-out of emoji usage.

**Comment by Mattwmaster58** [comment]
I agree. In Windows they look terrible.

**Comment by cs01** [comment]
>  In Windows they look terrible.

They should not be appearing in Windows

https://github.com/pipxproject/pipx/blob/8e6f8b798dd6c2ea0e59eb39f01ae1a4e7da4427/src/pipx/constants.py#L26

If they are, we need to determine a more reliable way to set `WINDOWS` or find places where the `emoji_support` isn't being used but should be.

**Comment by Mattwmaster58** [comment]
Well, I'm assuming their emoji's or at the very least fancy Unicode characters:
![image](https://user-images.githubusercontent.com/26337069/81132061-5bc05e00-8f0a-11ea-8867-7ce465511724.png)

**Comment by cs01** [comment]
> Well, I'm assuming their emoji's or at the very least fancy Unicode characters:

Ah those are probably the terminal codes to show/hide the cursor.
```
HIDE_CURSOR = "\033[?25l"
SHOW_CURSOR = "\033[?25h"
```

The goal is to do nothing fancy at all in windows. The windows animation uses a standard `.`.

I wonder if those should be taken out for windows too. Maybe we can't even clear lines.  Which terminal are you using?

**Comment by Mattwmaster58** [comment]
@cs01 I'm using CMD - latest windows insider fast ring preview. Weirdly I thought a remember changing the code page to utf8 which in theory sold it anything fix things.

**Comment by imba-tjd** [comment]
I also see `[?25l[?25h` in cmd and pwsh, but pipx works well in Windows Terminal and VS Code's terminal, which both support emoji either.

**Comment by buhtz** [comment]
See also #1057
