### ISSUE TITLE
The auto-upgrade shared libraries feature can break environments

### ISSUE THREAD

**Issue by techdragon** [pipxproject/pipx#379]
**Describe the bug**
The Auto-Upgrade shared libraries feature can break environments

**How to reproduce**
Have some things installed, leave the environment alone for a while, upgrade the system python version, go to perform `reinstall-all` or even a basic operation like `list` after the python version upgrade. And the environment attempts to autoupdate the shared libraries, fails and triggers an exit of the program. Effectively leaving the environment in a broken state that pipx cannot upgrade out of. 

**Expected behavior**
Not getting stuck like this. Auto-Upgrade should have an off switch, or fail without otherwise preventing normal command execution.

**Comment by itsayellow** [comment]
@cs01 is this from #318?  In the past I thought `reinstall-all` was working for me when my system python got upgrad

**Comment by techdragon** [comment]
Kept digging, turned out I had an old version so I'm going to call it invalid and close this.
