### ISSUE TITLE
list installed packages in more version control friendly format

### ISSUE THREAD

**Issue by zachvalenta** [pipxproject/pipx#390]
**How would this feature be useful?**

* keep track of packages you have installed, handy when moving to a new machine
* current `list` command outputs some extra stuff (file path of packages, symlinks to packages)
```sh
$ pipx list

venvs are in /Users/zach/.local/pipx/venvs
apps are exposed on your $PATH at /Users/zach/.local/bin
# actual packages
```

**Describe the solution you'd like**

* something like Hombrew `leaves` command, even better if the delimiter is not a carriage return
```sh
$ brew leaves

asciinema
automake
bat
```

**Comment by SanketDG** [comment]
Seems like an extra argument like `--clean` or a different command altogether would work out.

**Comment by zachvalenta** [comment]
> Seems like an extra argument like `--clean` or a different command altogether would work out.

This is akin to how Homebrew does it, insofar as they have `list` for all deps and `leaves` for top-level dependencies. Not apples to apples, but similar idea of a less cluttered output for piping to a file.

**Comment by lukka5** [comment]
I like the idea. Couldn't we add the versions of each package as well like a pip freeze?

**Comment by uranusjr** [comment]
This is covered by #109.

**Comment by SanketDG** [comment]
Seems like there are different usecases for both `--clean` and `--verbose`/`--json`.

`--clean` seems for archival and documentation reasons, whereas `--json` is for recreating environments back from a metadata file.

**Comment by SanketDG** [comment]
Opened a draft PR for discussion https://github.com/pipxproject/pipx/pull/392

**Comment by itsayellow** [comment]
I'm going to close this now because #660 was merged.

**Comment by zachvalenta** [comment]
Didn't see it mentioned on the PR that closed this issue, but you can accomplish this via: `pipx list --short`.
