### ISSUE TITLE
Package depending on binary exposed by dependency (borgmatic/borgbackup)

### ISSUE THREAD

**Issue by OverkillGuy** [pipxproject/pipx#402]
**Describe the bug**
Generically: A pipx-installed package cannot use executable exposed by another package (such as dependencies)

Case in point: [borgmatic](https://torsion.org/borgmatic/) tries to shell out to `borg` command, which is usually exposed by [borgbackup](https://borgbackup.readthedocs.io/en/1.1-maint/installation.html#pip-installation) package (not an explicit package dependency in this case, but can be done via `pipx inject`).

**How to reproduce**

I tried to inject borgbackup to the pipx venv:

```bash
pipx install borgmatic
pipx inject borgmatic borgbackup

# generate a dummy config file for borgmatic to "run" with
borgmatic-generate-config /tmp/dummy_conf

# States "no such file or directory: 'borg'
borgmatic -c /tmp/dummy_conf info

# No such executable (not exposed via pipx)
borg --help
```

Alternatively, by separating both into their pipx env, as expected, neither can see each other

```bash
pipx install borgbackup
borg --help  # runs OK, as expected

pipx install borgmatic
# dummy config file again
borgmatic-generate-config /tmp/dummy_conf
# Still "no such file or directory: 'borg'
# this time because borg is hidden outside the venv thanks to pipx
borgmatic -c /tmp/dummy_conf info
```

**Expected behavior**

Should be able to expose the `borg` executable to `borgmatic` _somehow_. Right now it's unusable with `pipx`.

**Proposed solution**
I see two options:
1. allow exposing executable of pipx-injected dependency (to keep one a dependency on the other): `pipx inject borgmatic --export-executable borgbackup`
2. allow linking two pipx venv-binaries (which allows each to be used without the other): `pipx install borgmatic --link-executable borgbackup`

Quick shout out for a great little package you've got there, this is the first time I get an issue with it and admittedly it's an odd one.

**EDIT**: Oh man, issue 402? [HTTP 402 = Payment required](https://http.cat/402). But I don't have any money!

**Comment by uranusjr** [comment]
pipx currently has `--include-deps` which injects binaries from dependencies. It’s an all-or-nothing switch, but may be suitable for your scenario?

**Comment by OverkillGuy** [comment]
Good catch! That certainly covers part of the usecase.

It turns out that borgmatic doesn't explicitly depend on borg being present, so it doesn't expose this specific deps. As mentioned, the flag is a bit of a loose cannon:

```bash
pipx install --include-deps borgmatic
  installed package borgmatic 1.5.2, Python 3.8.3
  These binaries are now globally available
    - borgmatic
    - chardetect
    - easy_install                    # Hmm I likely don't want that to be exposed
    - easy_install-3.8
    - generate-borgmatic-config
    - pykwalify                       # Not that either
    - upgrade-borgmatic-config
    - validate-borgmatic-config
```

So I'll plead for oversight on my part (I was certain that I re-read the help of both `pipx install` and `pipx inject` twice before reporting issue, my bad), and that certainly covers part of the need, but it's a bit too broad in this case. It's just that it exposes too many things (I don't want to expose _everything_, but likely just for 1 specific package, or 1 command in 1 package)

**Comment by itsayellow** [comment]
Here's a workaround for you.

Borgmatic configuration (https://torsion.org/borgmatic/docs/reference/configuration/) allows for configuration of the borg executable
```
    # Alternate Borg local executable. Defaults to "borg".
    # local_path: borg1
```
I believe you could set that to the full path of the borgmatic venv bin directory (e.g. `~/.local/pipx/venvs/borgmatic/bin`).

**Comment by OverkillGuy** [comment]
Closing this ticket as the issue got satisfactory workaround, and only other point "`--include-deps` is all-or-nothing and may need refinement" does not really need any action right now, it's more of a feeling =)

Thanks for the support!
