### ISSUE TITLE
How to install optional requirements?

### ISSUE THREAD

**Issue by Seanny123** [pipxproject/pipx#405]
I've installed DVC with `pipx` using the command `pipx install git+https://github.com/iterative/dvc.git`. However, this install lacks some of the extra requirements. I would like to install these with something like:
```
pipx install git+https://github.com/iterative/dvc.git[s3]
```

However, when I run this, I get the following error:
```
  ERROR: Command errored out with exit status 128:b.com/iterative/dvc.git[s3]'
   command: git clone -q 'https://github.com/iterative/dvc.git[s3]' /tmp/pip-req-build-zmk7w7vy
       cwd: None
  Complete output (1 lines):
  fatal: unable to access 'https://github.com/iterative/dvc.git[s3]/': The requested URL returned error: 400
  ----------------------------------------
ERROR: Command errored out with exit status 128: git clone -q 'https://github.com/iterative/dvc.git[s3]' /tmp/pip-req-build-zmk7w7vy Check the logs for full command output.
Cannot determine package name from spec 'git+https://github.com/iterative/dvc.git[s3]'. Check package spec for errors.
```

It seems like `pipx` is interpreting `[s3]` as part of the URL? However, this seems to go against the `pip` spec? Specifically, see [example `6.`](https://pip.pypa.io/en/stable/reference/pip_install/#examples).

**Comment by clbarnes** [comment]
Does this work in pip? I tried `pip install "git+https://github.com/iterative/dvc.git[s3]"` (quotes needed for zsh) and got a 404, which makes sense as it's a URL which doesn't exist.

If it doesn't work in pip, it's unlikely to be supported by pipx, even if they fail for different reasons.

**Comment by Seanny123** [comment]
You are correct. I misread the example.

**Comment by nyanpasu64** [comment]
https://github.com/pypa/pip/issues/6548#issuecomment-498615461

for anyone who comes across this issue in the future, the correct syntax is `pipx install "dvc[s3] @ git+https://github.com/iterative/dvc.git"`
