### ISSUE TITLE
Add details about what a Sandbox is

### ISSUE THREAD

**Issue by bbkane** [pipxproject/pipx#406]
**How would this feature be useful?**

The README has a section about "Walkthrough: Running an Application in a Temporary, Sandboxed Environment"

**Describe the solution you'd like**

Please go into more detail about the Sandbox - is it a venv? Can I run untrusted code with `pipx run`?

If the sandbox is a venv, please consider changing the verbage to something like "Walkthrough: Running an Application in a Temporary Virtual Environment".

**Describe alternatives you've considered**

This is purely a documentation feature request. I'll be happy to submit a PR with any change decided

**Comment by cs01** [comment]
Thanks, good call. The sandbox is a venv. PR is welcome.
