### ISSUE TITLE
Package renamed to pipx-app in v0.10.0. Users of < 0.10 must re-install.

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#41]
As suggested in https://github.com/cs01/pipx/issues/2, pipx's package name was changed to `pipx-app` to avoid the name conflict with another project named `pipx`.

Thus pipx users who have already installed this pipx package with a version less than 0.10 will need to uninstall it and all its packages, then re-install everything. (This is due to path assumptions made by pipx based on package name; it assumes the virtual env's name matches the package's name.)

The end-user experience will be identical (you can still just call `pipx` from the command line), but some of the paths pipx uses behind the scenes will be changed.

```
pipx uninstall-all
curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python3
# reinstall packages
```

This was a one-time rename. Thank you for your understanding!

EDIT: changed from `pipx uninstall pipx` to `pipx uninstall-all`

**Comment by neersighted** [comment]
It's currently impossible to install pipx as suggested:

```
$ pipx upgrade-all
A virtual environment for pipx was detected at /usr/home/neersighted/.local/share/pipx/venvs/pipx. The 'pipx' package has been renamed to 'pipx-app'. Please reinstall pipx:
  pipx uninstall pipx
  curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python3
$ pipx uninstall pipx                                                                                                                                                                                                             
A virtual environment for pipx was detected at /usr/home/neersighted/.local/share/pipx/venvs/pipx. The 'pipx' package has been renamed to 'pipx-app'. Please reinstall pipx:
  pipx uninstall pipx
  curl https://raw.githubusercontent.com/cs01/pipx/master/get-pipx.py | python3
```

**Comment by cs01** [comment]
Thanks for letting me know! This has been fixed in 0.10.2.1

**Comment by aiguofer** [comment]
Existing venvs break after installing `pipx-app` due to the python symlinks.

**Comment by cs01** [comment]
Darn. I guess the instructions should be
```
pipx uninstall-all
```

I'll edit the initial issue.

**Comment by MisLink** [comment]
https://github.com/cs01/pipx/blob/e7bc6559ab36fc533a17532212a290cc23e0e2e9/pipx/main.py#L810-L819

Perhaps the wording here need to be revised?
