### ISSUE TITLE
pipx list crashes after upgrade from 0.12.3.3 to 0.15.3.1

### ISSUE THREAD

**Issue by gvoysey** [pipxproject/pipx#411]
I am running python 3.6.8 on macOS; my python is provided by pyenv. 

i installed pipx with `pip install --user pipx` in the base interpreter at version 0.12.3.3 and have been using it happily. 

Today, i `pip install --upgrade pipx` and bumped pipx to 0.15.3.1.  

Attempting to run `pipx list` results in: 
```
$ pipx list                                                                                                                 
venvs are in /Users/graham/.local/pipx/venvs
apps are exposed on your $PATH at /Users/graham/.local/bin
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipx/commands/common.py", line 124, in get_package_summary
    package_metadata = venv.package_metadata[package]
KeyError: 'isort'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/graham/.pyenv/versions/3.6.8/bin/pipx", line 11, in <module>
    sys.exit(cli())
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipx/main.py", line 580, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipx/main.py", line 184, in run_pipx_command
    return commands.list_packages(venv_container)
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipx/commands/list_packages.py", line 29, in list_packages
    for package_summary in p.map(get_package_summary, dirs):
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
KeyError: 'isort'
```

**Comment by uranusjr** [comment]
Quoting the [release note of 0.15.0.0](https://pipxproject.github.io/pipx/changelog/):

> When upgrading to 0.15.0.0 or above from a pre-0.15.0.0 version, you must re-install all packages to take advantage of the new persistent pipx metadata files introduced in this release. These metadata files store pip specification values, injected packages, any custom pip arguments, and more in each main package's venv. You can do this by running `pipx reinstall-all` or `pipx uninstall-all`, then reinstalling manually.

**Comment by cs01** [comment]
I wonder if we can detect these types of errors and print a message directing them to this release notes instead of a raw stack trace.

**Comment by gvoysey** [comment]
@cs01 that would be good.  @uranusjr  is correct about the cause, but the crash was _deeply_ unintuitive and it'd be nice to have that cleaned up a bit.

**Comment by cs01** [comment]
Let's leave this open as a TODO for printing a more intuitive error when migrating to 0.15. The fix should be pretty straight forward -- just a try/except in the right place.

**Comment by gvoysey** [comment]
@cs01 sure.  if you point me at the right general area, i can see if i have cycles to get a PR out.

**Comment by cs01** [comment]
I believe the stack trace in your original issue points to it:
```
  File "/Users/graham/.pyenv/versions/3.6.8/Python.framework/Versions/3.6/lib/python3.6/site-packages/pipx/commands/common.py", line 124, in get_package_summary
    package_metadata = venv.package_metadata[package]
KeyError: 'isort'
```
@itsayellow is this the best way to detect an upgrade is required?

**Comment by itsayellow** [comment]
I think the best way to detect a missing metadata file is if `package_metadata.main_package.package is None`.

Ah I see we do not print the warning from a missing metadata file in `pipx_metadata_file.py` unless verbose is turned on:
https://github.com/pipxproject/pipx/blob/46acc8590b843ccf32a50da0502b0dda64269dae/src/pipx/pipx_metadata_file.py#L147

I think I might vaguely remember turning that warning off for non-verbose operation, possibly for times when you are creating a new venv?

**Comment by itsayellow** [comment]
Actually I take that back, currently that won't work.  Currently `venv.py` `Venv.package_metadata(self)` just skips the main package if it finds `main.package.package is None` when it is filling in the `@property` package_metadata for a `Venv`.

I think what would currently work is to test if `not venv.package_metadata`.  With no metadata file `venv.package_metadata` would be an empty dict.

Another possible solution is a two-step change where `Venv.package_metadata(self)` gets an `else` clause to its `if self.pipx_metadata.main_package.package is not None:` that would assign `None` to the `package_metadata` member, which would allow testing for `None` in any calling function to show no metadata file.

**Comment by itsayellow** [comment]
Is what you're looking for just a note (like the note for missing python version)?  If so, I can make a PR.

**Comment by cs01** [comment]
We should never print a bare stack trace to the user. That should always be replaced with an actionable error message. What I would like is for pipx list to look something like this:
```
> pipx list
pipx has added additional metadata in v15.0.0, which is a breaking change for existing packages. Since this is your first time running after the upgrade, you must reinstall or upgrade your packages to continue:
  `pipx reinstall-all` or 
  `pipx uninstall-all`, then reinstall manually.
```

**Comment by itsayellow** [comment]
So basically stop the entire list process.  (Not a warning for each package.)

OK, let me see what I can do!

**Comment by itsayellow** [comment]
Or should we detect this for any/all other pipx commands?

**Comment by cs01** [comment]
> So basically stop the entire list process. (Not a warning for each package.)

That would be ideal, but I wouldn't spend too much time on this. Avoiding the bare stack trace is the most important thing, and getting the user actionable info.

> Or should we detect this for any/all other pipx commands?

Yes if you don't mind.

**Comment by itsayellow** [comment]
It's very easy to fix on a per-venv basis, mostly because otherwise we'd have to check all the packages before printing anything to see if one of them was problematic.  

How about something like this:

<img width="605" alt="Screen Shot 2020-05-28 at 6 26 14 PM" src="https://user-images.githubusercontent.com/12565784/83210910-b8312a80-a110-11ea-9fa2-c9fb19649772.png">

**Comment by cs01** [comment]
Looks good to me! That probably makes more sense anyway to check it individually.

**Comment by gvoysey** [comment]
cheers!  thanks for the super fast turnaround and a great project. 

quick unrelated question -- coming from 14.0, is there a way to pregenerate a list of all my injected packages so that reinstall-all handles it properly after i move to 15.x? (I have a very heavily modified `ipython` and it'd be convenient to still have the package suite after the reinstall.  that said, grepping through my shell history isn't the worst thing in the world)

**Comment by itsayellow** [comment]
The only thing that comes to my mind is:
```
pipx runpip ipython list
```

It will give you everything installed to that venv, including all dependencies.  But included in that list will be the packages you injected.

**Comment by itsayellow** [comment]
Of course you'd still have to manually inject everything yourself.

This, of course, is the reason we added metadata in the first place.  Once you are setup with a new pipx version, commands like `reinstall-all` happen automatically, with injected packages and everything.

**Comment by gvoysey** [comment]
Yeah, that makes sense that it'd be a 1-time deal.  

I think this gets to what I proposed some time ago in https://github.com/pipxproject/pipx/issues/109 , so that might/should be revisited as a result of the current metadata feature?
