### ISSUE TITLE
Link data_files outside virtualenv

### ISSUE THREAD

**Issue by stanislaw55** [pipxproject/pipx#416]
**How would this feature be useful?**

I have ton of applications that are exposing not only executables but also desktop files (for menu), icons, user settings, etc. They are added into package using `data_files` argument to `setuptools.setup`. Managing all of them became real hell. If `pipx` had ability to link `data_files` for application that is installed to user folder (just like with entrypoint), it would enable me to isolate them using `pipx`.

**Describe the solution you'd like**

Create registry of `data_files` from application's metadata AND files which are present inside application's virtual environment (think: logical conjunction operation). They should have entry in `data_files` like `share/applications/app.desktop` which now ends up in `<appvenv>/share/applications/app.desktop`. Entry in `data_files` can be malformed and files can be installed in wrong paths hence double checking with files present in virtualenv.

Registry of linked files could be as simple as plain text file where each line is path to file in virtual environment, relative to the root of venv (like `share/applications/app.desktop`). It would then saved inside application's virtual environment.  

During uninstall, all links will be deleted, just like it is now done with entrypoints.

Tricky part are conflicts: trying to create a link which already exists and points to different file. For me, best thing to do would be to fail and produce verbose error message to the user.

To preserve backwards compatibility, additional flag to `install` subcommand would be helpful, something like `--link-data-files`. By default set to `False`.

**Describe alternatives you've considered**

Wrapping pipx with some additional script which will do the stuff described above. However, it seems sketchy to me, better would be to integrate this functionality into pipx itself.

**Comment by itsayellow** [comment]
To me this seems better suited to the tools that make full-blown applications out of python programs ("freezing" the python code and associated data files), like pyinstaller, py2app, py2exe, etc.  If pipx tried to do this we'd just be doing a very trivial version of something these tools already do in a very sophisticated way.

**Comment by itsayellow** [comment]
I think you can do a lot of this with proper packaging and use for example setuptools' datafiles (https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html) or with a python freeze solution mentioned above.  This is not something we're going to implement with pipx.
