### ISSUE TITLE
new venv is missing pip

### ISSUE THREAD

**Issue by jobevers** [pipxproject/pipx#419]
**Describe the bug**
The new virtual environment doesn't have pip

**How to reproduce**
```
➜  ~ pipx install --verbose sphinx
pipx > (package_name_from_spec:226): Determined package name: sphinx
pipx > (package_name_from_spec:227): Package name determined in 0.0s
pipx > (run_subprocess:112): running /home/jobevers/.pyenv/versions/3.8.2/bin/python3 -m venv --without-pip /home/jobevers/.local/pipx/venvs/sphinx
pipx > (run_subprocess:112): running /home/jobevers/.local/pipx/venvs/sphinx/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/jobevers/.local/pipx/shared/bin/python -c import sysconfig; print(sysconfig.get_path('purelib'))
pipx > (run_subprocess:112): running /home/jobevers/.local/pipx/venvs/sphinx/bin/python --version
pipx > (run_subprocess:112): running /home/jobevers/.local/pipx/venvs/sphinx/bin/python -m pip install sphinx
/home/jobevers/.local/pipx/venvs/sphinx/bin/python: No module named pip
pipx > (install_package:188): '/home/jobevers/.local/pipx/venvs/sphinx/bin/python -m pip install sphinx' failed

pipx > (rmdir:18): removing directory /home/jobevers/.local/pipx/venvs/sphinx
Error installing sphinx.
```
```
➜  ~ pipx --version
0.15.4.0
```

**Expected behavior**
pip should be in the venv; package should install.

**Comment by jobevers** [comment]
If I take out the `--without-pip` part in the venv creation, this works fine.

**Comment by cs01** [comment]
Can you try uninstalling sphinx (or `rm -r ~/.local/pipx/venvs/sphinx`), then running
```
rm -r ~/.local/pipx/shared/
pipx install --verbose sphinx
```

**Comment by spazm** [comment]
I just read this ticket and decided to give it a try. My data point: Installed smoothly.  

> ```
> pipx install --verbose sphinx
> ```
* I am using the same version of pipx (0.15.4.0).  
* debug output showed building the venv, then installing pip then installing sphinx.
* I am also using `pyenv`, python 3.8.2 at the time of install.
* This is a brand new pipx install and firpst pipx package.

Pipx installed and upgraded pip in the new environment before installing sphinx.
