### ISSUE TITLE
add pipx as an installation method for projects

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#42]
If you are an owner of a project or have a favorite project that is suited to be run by pipx, add instructions to the project's README.

Let’s make pipx as ubiquitous as pip for python package installation!

Example installation text

> This package can be installed and run from a temporary virtual environment with no commitment by running `pipx run BINARY`

> This package can be globally installed using pipx, the Python binary runner.
```
pipx install PACKAGE
```
and run directly from the command line
```
BINARY
```

**Comment by pmav99** [comment]
> can be globally installed

Is this accurate? I was under the impression that pipx installations are per-user ones, am I wrong?

**Comment by cs01** [comment]
I don’t think global and per-user are mutually exclusive terms. By default pipx installs binaries to a location in the user’s home directory. So by default it globally installs binaries for the user running the operation.

**Comment by cs01** [comment]
pipx will be listed as a "guide" on packaging.python.org soon https://github.com/pypa/python-packaging-user-guide/pull/594#issuecomment-465673352

**Comment by sahensley** [comment]
Link to the published guide: [Installing stand alone command line tools](https://packaging.python.org/guides/installing-stand-alone-command-line-tools/#installing-stand-alone-command-line-tools)

**Comment by gaborbernat** [comment]
I think with the above this can now be closed.
