### ISSUE TITLE
ModuleNotFoundError: No module named 'pip._vendor.progress'

### ISSUE THREAD

**Issue by KGTasa** [pipxproject/pipx#421]
**Describe the bug**
I tried installing pipx on Windows 10 with Python 3.8.3 and latest pip version. Upon doing so, it ended with ModuleNotFoundError: No module named 'pip._vendor.progress'

**How to reproduce**
I don't really know. It doesn't recognise pipx as command

**Expected behavior**
It should have installed pipx

**Comment by cs01** [comment]
Can you share the command you ran and the stack trace?

**Comment by KGTasa** [comment]
python -m pip install --user pipx
python -m pipx ensurepath
I removed the number 3 after python because it didn't find anything with it.

**Comment by itsayellow** [comment]
@KGTasa can you run
```
python --version
```

If the python you're using is a version 2.x.x, then it is not compatible with pipx.  You need at least python version 3.6.

**Comment by KGTasa** [comment]
I ran it and it said it is 3.8.3

**Comment by itsayellow** [comment]
Could you copy here all of the text that is printed after you try to install pipx?  We'd like to see the exact errors returned.

**Comment by KGTasa** [comment]
C:\Users\Mladenovic>python -m pip install --user pipx
Requirement already satisfied: pipx in c:\users\mladenovic\appdata\roaming\python\python38\site-packages (0.15.4.0)
Requirement already satisfied: argcomplete<2.0,>=1.9.4 in c:\users\mladenovic\appdata\roaming\python\python38\site-packages (from pipx) (1.11.1)
Requirement already satisfied: userpath in c:\users\mladenovic\appdata\roaming\python\python38\site-packages (from pipx) (1.4.0)
Requirement already satisfied: click in c:\users\mladenovic\appdata\roaming\python\python38\site-packages (from userpath->pipx) (7.1.2)

C:\Users\Mladenovic>python -m pipx ensurepath
←[?25lThe directory `C:\Users\Mladenovic\.local\bin` is already in PATH. If you are sure you want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go!
←[?25h
C:\Users\Mladenovic>pipx --version
'pipx' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Mladenovic>

**Comment by itsayellow** [comment]
This seems like a different error than your original issue.  This time, it just seems like it cannot find `pipx` in your PATH.

Does it work if you try and execute pipx using the full path to it, e.g.:
```
C:\Users\mladenovic\Appdata\Roaming\Python\Python38\Scripts\pipx --version
```

If that works then your immediate problem is that you have to add `C:\Users\mladenovic\Appdata\Roaming\Python\Python38\Scripts` to your PATH.

**Comment by KGTasa** [comment]
I added C:\Users\Mladenovic\Appdata\Roaming\Python\Python38\Scripts to the path, and in cmd this happened:

C:\Users\Mladenovic>pipx
Fatal error in launcher: Unable to create process using '"c:\users\mladenovic\appdata\local\programs\python\python38-32\python.exe"  "C:\Users\Mladenovic\Appdata\Roaming\Python\Python38\Scripts\pipx.exe" '

**Comment by itsayellow** [comment]
Hmmm.

Does pip work for you at all?

Try:
```
python3 -m pip --version
```
And let us know what the output was.

**Comment by itsayellow** [comment]
Additionally, if pip works, could you please execute
```
python3 -m pip list
```
and report the output of that command.

**Comment by KGTasa** [comment]
C:\Users\Mladenovic>python -m pip --version
pip 20.1.1 from C:\Users\Mladenovic\AppData\Local\Programs\Python\Python38\lib\site-packages\pip (python 3.8)

C:\Users\Mladenovic>python -m pip list
Package     Version
----------- --------
argcomplete 1.11.1
click       7.1.2
pip         20.1.1
pipx        0.15.4.0
setuptools  41.2.0
userpath    1.4.0

I typed python instead of python 3 because when I typed python3 nothing happened.

**Comment by itsayellow** [comment]
From your original error this *sounds* like something wrong with pip itself, that a component of pip is missing.  I'm not sure why that would be, but let's be sure

Lets try again installing pipx, so we can see exactly what's going on.

First uninstall:
```
python -m pip uninstall argcomplete click pipx userpath
```

Then install, and please capture the full text of what happens so we can see the full output:
```
python -m pip install --user pipx
```

thanks for your patience!

**Comment by KGTasa** [comment]
`C:\Users\Mladenovic>python -m pip uninstall argcomplete click pipx userpath
Found existing installation: argcomplete 1.11.1
Uninstalling argcomplete-1.11.1:
  Would remove:
    c:\users\mladenovic\appdata\roaming\python\python38\scripts\activate-global-python-argcomplete
    c:\users\mladenovic\appdata\roaming\python\python38\scripts\python-argcomplete-check-easy-install-script
    c:\users\mladenovic\appdata\roaming\python\python38\scripts\python-argcomplete-tcsh
    c:\users\mladenovic\appdata\roaming\python\python38\scripts\register-python-argcomplete
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\argcomplete-1.11.1.dist-info\*
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\argcomplete\*
Proceed (y/n)? y
  Successfully uninstalled argcomplete-1.11.1
Found existing installation: click 7.1.2
Uninstalling click-7.1.2:
  Would remove:
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\click-7.1.2.dist-info\*
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\click\*
Proceed (y/n)? y
  Successfully uninstalled click-7.1.2
Found existing installation: pipx 0.15.4.0
Uninstalling pipx-0.15.4.0:
  Would remove:
    c:\users\mladenovic\appdata\roaming\python\python38\scripts\pipx.exe
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\pipx-0.15.4.0.dist-info\*
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\pipx\*
Proceed (y/n)? y
  Successfully uninstalled pipx-0.15.4.0
Found existing installation: userpath 1.4.0
Uninstalling userpath-1.4.0:
  Would remove:
    c:\users\mladenovic\appdata\roaming\python\python38\scripts\userpath.exe
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\userpath-1.4.0.dist-info\*
    c:\users\mladenovic\appdata\roaming\python\python38\site-packages\userpath\*
Proceed (y/n)? y
  Successfully uninstalled userpath-1.4.0

C:\Users\Mladenovic>python -m pip install --user pipx
Collecting pipx
  Using cached pipx-0.15.4.0-py3-none-any.whl (39 kB)
Collecting argcomplete<2.0,>=1.9.4
  Using cached argcomplete-1.11.1-py2.py3-none-any.whl (36 kB)
Collecting userpath
  Using cached userpath-1.4.0-py2.py3-none-any.whl (14 kB)
Collecting click
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Installing collected packages: argcomplete, click, userpath, pipx
Successfully installed argcomplete-1.11.1 click-7.1.2 pipx-0.15.4.0 userpath-1.4.0`

After that, I tried typing pipx and something popped up, so I think it worked. Here is everything I got:

`C:\Users\Mladenovic>pipx
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,runpip,ensurepath,completions}
            ...

Install and execute apps from Python packages.

Binaries can either be installed globally into isolated Virtual Environments
or run directly in an temporary Virtual Environment.

Virtual Environment location is C:\Users\Mladenovic\.local\pipx\venvs.
Symlinks to apps are placed in C:\Users\Mladenovic\.local\bin.

Optional Environment Variables:
PIPX_HOME: Overrides default pipx location. Virtual Environments
will be installed to $PIPX_HOME/venvs.
PIPX_BIN_DIR: Overrides location of app installations. Apps are symlinked
or copied here.
USE_EMOJI: Override emoji behavior. Default value varies based on platform.

optional arguments:
  -h, --help            show this help message and exit
  --version             Print version and exit

subcommands:
  Get help for commands with pipx COMMAND --help

  {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,runpip,ensurepath,completions}
    install             Install a package
    inject              Install packages into an existing Virtual Environment
    upgrade             Upgrade a package
    upgrade-all         Upgrade all packages. Runs `pip install -U <pkgname>` for each package.
    uninstall           Uninstall a package
    uninstall-all       Uninstall all packages
    reinstall-all       Reinstall all packages
    list                List installed packages
    run                 Download the latest version of a package to a temporary virtual environment, then run an app
                        from it. Also compatible with local `__pypackages__` directory (experimental).
    runpip              Run pip in an existing pipx-managed Virtual Environment
    ensurepath          Ensure directory where pipx stores apps is on your PATH environment variable. Note that
                        running this may modify your shell's configuration file(s) such as '~/.bashrc'.
    completions         Print instructions on enabling shell completions for pipx
←[?25l←[?25h`

Thank you very much for your help!

**Comment by itsayellow** [comment]
Glad it worked out for you!  Since you seem to be up and running I'll close this issue.
