### ISSUE TITLE
'reinstall-all' should also reinstall shared libraries

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#424]
**Describe the bug**

`pipx reinstall-all` currently reinstalls all the apps, but does not reinstall the shared libraries (pip, setuptools, wheel).
**How to reproduce**

`pipx reinstall-all` 
**Expected behavior**

`pipx reinstall-all` should clear out the shared libraries so that they are automatically reinstalled and upgrade to their latest versions.

**Comment by itsayellow** [comment]
This could also help #294 .  It is a good bug to watch out for to see if `reinstall-all` works in that case.
