### ISSUE TITLE
`.` command is deprecated as for fish shell

### ISSUE THREAD

**Issue by eduidl** [pipxproject/pipx#429]
It may be a little from a bug, but currently `. ` is deprecated (https://github.com/fish-shell/fish-shell/issues/310).
Therefore, `pipx completions` command should suggest to use `source` command instead of `.` command.

> . (a single period) is an alias for the source command. The use of . is deprecated in favour of
source, and . will be removed in a future version of fish.

(This is quoted from `source --help`)

**Describe the bug**

```
$ pipx completions

:

fish:
    register-python-argcomplete --shell fish pipx | .
```

**Expected behavior**

```
$ pipx completions

:

fish:
    register-python-argcomplete --shell fish pipx | source
```

**Comment by eduidl** [comment]
I Issued also in argcomplete (https://github.com/kislyuk/argcomplete/issues/308).

**Comment by itsayellow** [comment]
For the record, this is documented in the fish documetation as well:
https://fishshell.com/docs/current/cmds/source.html

> . (a single period) is an alias for the source command. The use of . is deprecated in favour of source, and . will be removed in a future version of fish.
