### ISSUE TITLE
Wrong default PIPX_BIN_DIR value on windows 1909

### ISSUE THREAD

**Issue by OranShuster** [pipxproject/pipx#431]
**Describe the bug**
Machine used is 
Windows 1909 update
python 3.8.1 (Installed using pyenv which was installed using choco)
pip 20.1.1
latest version of pipx of today

The path assumed by ensure_path is different then the actual path pip will install the pipx executable
i wrote the process of how i found the correct bin path for ease of reproduction

According to `constants.py`-
`DEFAULT_PIPX_BIN_DIR = Path.home() / ".local/bin"`
while Path.home() gives
```
>>> from pathlib import Path
>>> Path.home()
WindowsPath('C:/Users/<username>')
```

that means the expected place that pipx.exe will be installed is
`C:/Users/<username>/.local/bin`

However, `pip help install` shows us the following about `--user`
```
  --user                      Install to the Python user install directory for your platform. Typically ~/.local/, or **%APPDATA%\Python on
                              Windows**. (See the Python documentation for site.USER_BASE for full details.)
```
and `%APPDATA%` is 
```
$env:APPDATA
C:\Users\<username>\AppData\Roaming
```

and indeed i found the pipx.exe in under that folder
```
    Directory: C:\Users\thris\AppData\Roaming\Python\Python38\Scripts


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----        6/22/2020  12:46 PM          93044 pipx.exe
```

After changing PIPX_BIN_PATH and running ensurepath again, everything works as expected

**How to reproduce**
install pipx using pip

**Expected behavior**
after running `python -m pipx ensurepath` and opening a new terminal, running `pipx` should show the available commands

**Comment by uranusjr** [comment]
`PIPX_BIN_PATH` is not where `pipx.exe` is installed, but *where pipx installs package binaries* (i.e. what exe files end up when you `pipx install` something). pipx is doing the right thing, albeit confusing.

Maybe `pipx ensurepath` should make sure *both* directories are in `PATH` to avoid this confusion.

**Comment by OranShuster** [comment]
the wording in the docs is definetly confusing
```
pipx's default binary location is ~/.local/bin. This can be overriden with the environment variable PIPX_BIN_DIR.
```

only looking at the help description for the ensurepath command it is clear what it does
```
            "Ensure directory where pipx stores apps is on your "
            "PATH environment variable. Note that running this may modify "
            "your shell's configuration file(s) such as '~/.bashrc'."
```

Obviously the person installing pipx should make sure python scripts is on its path so every other tool can be used not only pipx.

side note - `python3` does not exist on my system. i belive the python/2/3 names were deprecated some time ago. it depends on repo and method of installation ofcourse

**Comment by OranShuster** [comment]
like i thought initially, user error
since i'm using pyenv i can't really add any single python install to the PATH
so after installing any executables through python you should use 
`pyenv rehash` so it will add shims for every executable

users installing python without pyenv should manage their PATH themselves.
it still might be good idea that `ensurepath` will make sure pipx executable is on the PATH and give a warning incase it doesnt, i think its a better user experiance

i guess this issue can be closed

**Comment by itsayellow** [comment]
@OranShuster good point about the non-clear docs.   Let us fix that.

Closing by your suggestion.
