### ISSUE TITLE
Use Github Actions instead of Travis on push

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#440]
**How would this feature be useful?**

We could use native Github Actions to do the same push-triggered verifications that we currently do using Travis CI.

It would remove Travis from our flow, removing one more moving part, and keeping all committing actions within Github, which seems more reliable to me.

It would also make it easier for us to in the future integrate other actions, such as doing a lot of housekeeping on a release.  For example on a Github release, we could rebuild the docs and publish them, and submit to PyPI.

**Describe the solution you'd like**

I have a branch in my repo up and running using Github Actions that currently replicates our Travis CI
push-triggered verifications and tests.
https://github.com/itsayellow/pipx/tree/github-actions

**Describe alternatives you've considered**

We don't strictly speaking **need** to do this, the current Travis verifications work.  But I thought this might conceptually be simpler, and thought I'd submit it for discussion since I have it completely implemented and it would be ready to drop in now as a PR.

**Comment by itsayellow** [comment]
Related: #333

**Comment by itsayellow** [comment]
Whether or not we do this, I did learn something interesting and useful.

Before we would have compile errors in the tests sometimes with installing dependency `regex`, because there wasn't a pre-built wheel to download, and compiling would not find an include header file (`stdio.h`).  I found this problem when trying to make tests in macOS work, and solved it by the following:  Before running nox tests, I did `pip install wheel` and then `pip install regex`.  This has the side effect of building a regex wheel for the current system, and storing it in the pip cache.  Later, when pipx tries to install `regex` into one of its venvs, there is a wheel cached on the same system, and it can just use that wheel instead of problematically trying to compile it from source.

I do not know why compiling `regex` from source outside of nox works better than compiling it from source inside of nox!

**Comment by cs01** [comment]
I have no experience with GitHub actions but I think I am fine if we migrate to it. GitHub was recently acquired by Microsoft and has a lot of momentum while Travis recently had massive layoffs, and if we can fully automate the release process that would be amazing.

**Comment by itsayellow** [comment]
Ok I'll submit a pull request.  To start with it just replicates our Travis CI verifications, and adds a macos target, which may or may not be useful (macos is posix and pretty close to linux.)
