### ISSUE TITLE
Equivalent to pip show

### ISSUE THREAD

**Issue by rugk** [pipxproject/pipx#457]
**How would this feature be useful?**
I want to show information about a package, e.g. the installed version, dependencies etc.

**Describe the solution you'd like**
Just like the original `pip`, `pip show` should be there, but that command does not exist, appearently.

See https://stackoverflow.com/q/10214827/5008962

**Describe alternatives you've considered**

Dunno, how do I show the installed version of a package then??

* Also `list` behaves differently than in pip, so I also cannot list the version there. (it seems to show me no libs)
* Aaand, show the version number with `list`, even if I inject a package, I have no clue what version it installed…

**Comment by uranusjr** [comment]
I’d rather this feature is not duplicated in pipx, personally. Just use `pipx runpip` for this.

**Comment by itsayellow** [comment]
Version numbers for the main package are currently displayed with `pipx list`.

Version numbers for injected packages with `pipx list --include-injected` are in the development version of pipx and will be in the next release.

**Comment by Ivoz** [comment]
```$ pipx runpip <pipx-venv-name> show <specific-package>```

**Comment by itsayellow** [comment]
Closing, use `runpip` with `show`.
