### ISSUE TITLE
Potential code quality issues found

### ISSUE THREAD

**Issue by pnijhara** [pipxproject/pipx#459]
I forked this repo last week and ran a DeepSource analysis on it. DeepSource found a variety of different issues categorized based on their types and severity which you can view [here](https://deepsource.io/gh/pnijhara/pipx/).

Brief description -
Anti-Patterns: 21
Bug Risks: 08
Performance issues: 03
Security Issues: 21

You can find a detailed description and fixes for some of them [here](https://deepsource.io/gh/pnijhara/pipx/issues/?category=recommended).

Please let me know what issues you'd like to focus on fixing and I'd be happy to take a look into it. Also, you can choose to hide certain types of issues too (if you wish to ignore them or you believe it is a false positive). I'd also be happy to send a patch with the DeepSource configuration file with the required fixes.

You can find the required configuration file for DeepSource [here](https://github.com/pnijhara/pipx/blob/master/.deepsource.toml).

**Comment by itsayellow** [comment]
Interesting.

From my first glance, I don't understand why `flake8` isn't catching the **Unused Arguments** that this analysis finds in a couple of functions??
https://deepsource.io/gh/pnijhara/pipx/issue/PYL-W0613/occurrences

**Comment by itsayellow** [comment]
Do we need to add this:
https://pypi.org/project/flake8-unused-arguments/

**Comment by itsayellow** [comment]
Some of these are really good finds to clean up.  This is worth prioritizing.

**Comment by uranusjr** [comment]
Flake8 does not flag unused arguments like this since there’s no other way to call the function. The unused argument is not always a problem (e.g. in inheritance you need them to make function overriding useful). There are a few issues found here I feel are too generalised and up to personal coding style, but many of them are indeed very good finds and should be cleaned up.

**Comment by pnijhara** [comment]
Thank you for the reviews @itsayellow and @uranusjr. I will send a PR to pipx with some fixes and a DeepSource config file.
