### ISSUE TITLE
ModuleNotFoundError installing package with setuptools_scm

### ISSUE THREAD

**Issue by polm** [pipxproject/pipx#463]
**Describe the bug**

When I try to install [cutlet](https://github.com/polm/cutlet) I get this error:

 ```
  ERROR: Command errored out with exit status 1:
     command: /tmp/tmpw195j32y/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-db8tw4n5/cutlet/setup.py'"'"'; __file__='"'"'/tmp/pip-install-db8tw4n5/cutlet/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rwdkx6tl
         cwd: /tmp/pip-install-db8tw4n5/cutlet/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-db8tw4n5/cutlet/setup.py", line 7, in <module>
        import setuptools_scm
    ModuleNotFoundError: No module named 'setuptools_scm'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

```

**How to reproduce**

This should reproduce the error:

    pipx install cutlet

I'm on Linux but I don't think platform is relevant so I'll omit verbose output, let me know if it would actually help.

**Expected behavior**

cutlet should have installed without issue.

-----

I maintain this package, so I'd like to make sure it works. I'm not sure if I'm doing something wrong and should change it or if this is an issue with pipx.

To clarify why I'm importing `setuptools_scm`, if it's not present the package is installed as version `0.0.0`, which can cause issues. Importing makes sure that the package is present rather than building a package with a bogus version. `setuptools-scm` is specified in `setup_requires`, so I'm not sure if there's something else I should do here.

**Comment by uranusjr** [comment]
One workaround would be to use PEP 517, i.e. adding a `pyproject.toml` containing the following:

```toml
[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
```

This will make pipx (the pip process underneath, to be exact) correctly set up a build environment that contains `setuptools-scm`. You can read more about the file [here](https://snarky.ca/what-the-heck-is-pyproject-toml/).

**Comment by polm** [comment]
Great, thank you, that makes sense. I'll try adding it and report back.

**Comment by polm** [comment]
Hm, using the above (plus a little extra) I was able to get setup working, but then pipx doesn't find the package script that's specified in `scripts` in `setup.py`. Any idea where I can specify a script? I do not want to specify an entry point, I already have a working command line script. 

I tried looking for an explanation of that but it's hard to find guides that aren't dependent on poetry...

**Comment by polm** [comment]
Found the part of the docs where it makes it clear that I need to use `entry_points`. 

https://pipxproject.github.io/pipx/how-pipx-works/#developing-for-pipx

This is kind of frustrating if I already have working scripts, though luckily in this case it wasn't a big change. Thanks for the quick reply on the initial report.

**Comment by uranusjr** [comment]
`scripts` are platform-specific and don’t work well on Windows, so it’s better to use it instead anyway 🙂

**Comment by casperdcl** [comment]
fyi https://github.com/iterative/shtab uses `setuptools_scm` without needing `pyproject.toml`
