### ISSUE TITLE
Doesn't work with Ubuntu installed pythons

### ISSUE THREAD

**Issue by Suor** [pipxproject/pipx#474]
**How to reproduce**

`pipx install dvc` produces:
```
Error: Command '['/home/suor/.local/pipx/shared/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

'/usr/bin/python3 -m venv --clear /home/suor/.local/pipx/shared' failed
```

`python3 -Im ensurepip` says:
```
/usr/bin/python3: No module named ensurepip
```
 Verbose install:
```
pipx > (setup:552): pipx version is 0.15.5.0
pipx > (setup:552): pipx version is 0.15.5.0
pipx > (package_name_from_spec:253): Determined package name: dvc
pipx > (package_name_from_spec:254): Package name determined in 0.0s
creating virtual environment...
pipx > (run_subprocess:113): running /usr/bin/python3 -m venv --without-pip /home/suor/.local/pipx/venvs/dvc
creating shared libraries...
pipx > (run_subprocess:113): running /usr/bin/python3 -m venv --clear /home/suor/.local/pipx/shared
Error: Command '['/home/suor/.local/pipx/shared/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

pipx > (rmdir:17): removing directory /home/suor/.local/pipx/venvs/dvc
'/usr/bin/python3 -m venv --clear /home/suor/.local/pipx/shared' failed
```

**Comment by uranusjr** [comment]
Ubuntu’s built-in Python is missing standard library components and is not suitable for usages outside of apt-installed software. Read more context here: https://bugs.launchpad.net/ubuntu/+source/python3.4/+bug/1290847

There is not much pipx can do here.

**Comment by cs01** [comment]
This is unfortunately the default behavior on Ubuntu installations. You will need to install pip and venv.

```
sudo apt install python3-venv python3-pip
```

https://packaging.python.org/guides/installing-using-linux-tools/#debian-ubuntu

**Comment by phil-blain** [comment]
Hi ! 

I'd like to be able to use pipx, but I do not have administrative rights on our systems, so I can't install the `python3-venv` system package.


I managed to use the system `venv` module in the following way:
```bash
$ mkdir project
$ cd project/
$ python3 -m venv venv --without-pip
$ ls -l venv/bin/
total 12K
-rw-r--r-- 1 <me> <group> 2.2K Nov  2 22:17 activate
-rw-r--r-- 1 <me> <group> 1.3K Nov  2 22:17 activate.csh
-rw-r--r-- 1 <me> <group> 2.4K Nov  2 22:17 activate.fish
lrwxrwxrwx 1 <me> <group>    7 Nov  2 22:17 python -> python3*
lrwxrwxrwx 1 <me> <group>   16 Nov  2 22:17 python3 -> /usr/bin/python3*
$ curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py
$ source venv/bin/activate
(venv) $ which python
/tmp/<me>/454106/project/venv/bin/python
(venv) $ python get-pip.py 
Collecting pip
  Using cached pip-20.2.4-py2.py3-none-any.whl (1.5 MB)
Collecting setuptools
  Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
Collecting wheel
  Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Installing collected packages: pip, setuptools, wheel
Successfully installed pip-20.2.4 setuptools-50.3.2 wheel-0.35.1
(venv) $ which pip
/tmp/<me>/454106/project/venv/bin/pip
(venv) $ pip list
Package    Version
---------- -------
pip        20.2.4
setuptools 50.3.2
wheel      0.35.1
(venv) $ deactivate
$ 
```

It would be really great if pipx could use this workaround, so that it could be used without sudo privileges !

**Comment by itsayellow** [comment]
@phil-blain it sounds like you have `python3-venv` installed on your system, which is not what the https://packaging.python.org/guides/installing-using-linux-tools/#debian-ubuntu implies is default.

The question is, is `python3-venv` now being installed on Ubuntu by default?  Otherwise this workaround may only work in your particular case where your system happens to have one of the two necessary apt packages installed.

**Comment by phil-blain** [comment]
I do not have `python-venv` installed. What `python-venv` does, as far as I know, is it installs the  Python `ensurepip` module, which makes the `venv` module work correctly. 

The workaround I use is to create the venv without pip, which works out of the box on Ubuntu (as long as `python3` is installed), and then use the official pip bootstrapping script, [`get-pip.py`](https://pip.pypa.io/en/stable/installing/), to install pip (and setuptools and wheel) inside the virtual environment. 

So this approach does not require the `python3-venv` Ubuntu package to be installed.

(and for the record, the default is still to not install this module, at least on 20.04).

**Comment by uranusjr** [comment]
Personally I would strongly prefer not using get-pip.py. Users should voice their frustration toward Debian and push them to fix their own stuff, instead of demanding every Python project to ship workarounds. Both ensurepip and venv are standard Python library modules, and it is a Debian bug if they do not include these in the package `python`.

**Comment by phil-blain** [comment]
I agree, but that only helps futur users of futur Debian/Ubuntu versions, and does nothing for users without admin rights right now :) 

I mean, I can fork pipx and add this workaround in my fork, but I would prefer not having to do that, and contribute to the project here instead (I understand if the pipx team has other priorities, but I could at least try to work on that myself and submit a PR)

**Comment by itsayellow** [comment]
@phil-blain `python3-venv` provides the `venv` functionality you used.  So the fact that you were even able to execute `python3 -m venv venv` means you have that package installed.  What you lack is `python3-pip`.  Again, to me this doesn't sound common to have one without the other.

I agree with @uranusjr, I'm not interested in hosting a hack for ubuntu installations that lack necessary apt packages.

**Comment by phil-blain** [comment]
I do understand if the pipx project is not interested. 

For the record, we have both `python3` and `python3-pip` installed, but not `python3-venv`:
```
$ apt -qq list python3 python3-pip python3-venv
python3/bionic-updates,now 3.6.7-1~18.04 amd64 [installed]
python3-pip/bionic-updates,bionic-updates,now 9.0.1-2.3~ubuntu1.18.04.1 all [installed]
python3-venv/bionic-updates 3.6.7-1~18.04 amd64
$ which pip3
/usr/bin/pip3
$ python3 -m venv
usage: venv [-h] [--system-site-packages] [--symlinks | --copies] [--clear]
            [--upgrade] [--without-pip] [--prompt PROMPT]
            ENV_DIR [ENV_DIR ...]
venv: error: the following arguments are required: ENV_DIR
$ python3 -m venv venv
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/home/me/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
$ python3 -m ensurepip
/usr/bin/python3: No module named ensurepip
```

And creating a venv without pip *does* work:
```
$ python3 -m venv venv --without-pip
$ ls  venv/bin/
activate  activate.csh  activate.fish  python@  python3@
```
