### ISSUE TITLE
pipx fails to install editable packages with extras in spec

### ISSUE THREAD

**Issue by aleksey-sergey** [pipxproject/pipx#475]
**Describe the bug**

pipx 0.15.5.0 refuses to install editable packages with [extras](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) in spec

**How to reproduce**

```bash
pipx install --editable .[dev]
# Unable to parse package spec: .[dev]
```

**Expected behavior**

`pipx` installs local package and extras in editable mode.

**Comment by itsayellow** [comment]
For reference:
https://pip.pypa.io/en/stable/reference/pip_install/#examples (see section "Install a package with setuptools extras.")
https://packaging.python.org/tutorials/installing-packages/#installing-setuptools-extras

Yes we need to fix this, thanks for the catch @aleksey-sergey .

Does anybody understand what the version specifier with the editable local install from the packaging.python.org link above does:
```
pip install -e .[PDF]==3.0  # editable project in current directory
```
Is that a typo, or is it somehow possible for a local path install to specify a version?

**Comment by uranusjr** [comment]
Looks like a typo. I submitted pypa/packaging.python.org#766 for this.

**Comment by itsayellow** [comment]
Ok, just checking.  Thanks @uranusjr for submitting a bug report, I was going to if you didn't!

**Comment by itsayellow** [comment]
@aleksey-sergey , pipx 0.15.5.1 is released which contains the fix for your issue.  Please let us know if you it doesn't fix your issue.

**Comment by aleksey-sergey** [comment]
@itsayellow , I checked pipx 0.15.5.1 and it works great. Big thanks for a fix!
