### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by kloczek** [pipxproject/pipx#486]
In setup.py is:
```
license="License :: OSI Approved :: MIT License",
```
However in LICENSE seems is not only MIT license text but BSD-3-Clause as well.

**Comment by itsayellow** [comment]
This sounds like a question for @cs01

**Comment by cs01** [comment]
I used some of pipsi's code to inspect packages for entrypoints when first writing pipx. At this point it's all gone from pipx, so that section in the LICENSE file can be removed.

**Comment by cs01** [comment]
The license now only contains MIT, so it is unambiguous. Thank you for asking @kloczek.
