### ISSUE TITLE
package has invalid interpreter

### ISSUE THREAD

**Issue by caleb15** [pipxproject/pipx#492]
**Describe the bug**
When I try to use okta-awscli (installed through pipx) I get an error:
```
└─[0] okta-awscli --profile 15five-root-administrator --okta-profile administrator
zsh: /home/caleb/.local/bin/okta-awscli: bad interpreter: /home/caleb/.local/pipx/venvs/okta-awscli/bin/python: no such file or directory
```

I listed the packages in pipx it said that it had a invalid interpreter:
```
(deploy) ┌─[caleb@caleb-H110M-A] - [~/Documents/fifteen5-deploy] - [2020-09-03 09:40:51]
└─[0] pipx list
venvs are in /home/caleb/.local/pipx/venvs
apps are exposed on your $PATH at /home/caleb/.local/bin
   package awscli has invalid interpreter /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.5/bin/python3.7
   package okta-awscli has invalid interpreter /home/linuxbrew/.linuxbrew/Cellar/python@3.8/3.8.5/bin/python3.7
```

**How to reproduce**
Not quite sure what happened but my guess is:
1. install pipx through homebrew
2. Install above packages through pipx
3. homebrew upgrade
4. things don't work yo

**Expected behavior**
packages transition to correct interpreter after upgrade or offer instructions on how to do so

**Comment by caleb15** [comment]
Solution: `pipx reinstall-all`

Thanks to @itsayellow :)

https://github.com/pipxproject/pipx/issues/146#issuecomment-574476592

**Comment by itsayellow** [comment]
Maybe we need a FAQ for this?  Or something more prominent in the documentation?

**Comment by MONTYYYYY** [comment]
i also had a ```
from oktaawscli.okta_awscli import main
ModuleNotFoundError: No module named 'oktaawscli'
``` after i updated my Mac os from Monterey to Venutura.  @caleb15 's solution : `pipx reinstall-all` fixed the bug.

**Comment by Cassete** [comment]
I also had a similar issue with two packages (lit, wllvm)
`bad interpreter: /home/linuxbrew/.linuxbrew/opt/python@3.11/bin/python3.11: no such file or directory`

**NOTE**: it was my first time installing pipx (apt) and my first time installing any package at all with it but imediatly after running `pipx reinstall-all` it worked
