### ISSUE TITLE
pipx doesn't support local source dirs

### ISSUE THREAD

**Issue by hydrargyrum** [pipxproject/pipx#494]
**Describe the bug**
With regular pip, it's possible to install packages not only from pypi but also from local dirs, for example if you've cloned a git repository to develop on it, it's possible to run `pip install /local/path/to/git/repository` (especially with `-e` option, although it's not always useful). But pipx fails when doing the same thing.

**How to reproduce**
```
% pipx install /local/path/to/git/repository
Not installing to existing directory '/local/path/to/git/repository'. Pass '--force' to force installation
```

**Expected behavior**
The package should be installed in a venv like a pypi package.

**Comment by itsayellow** [comment]
This should work in pipx.  The error message you show is what pipx says when you already have something by the same name installed using pipx.  If you run `pipx list` is there already a package installed with the same name as your `repository` name?

**Comment by itsayellow** [comment]
What version of pipx are you using?  I can't find that error message in the current version of pipx.  Please make sure you are using the most recent version of pipx.
```
pipx --version
```
Also can you display the output from running with the `--verbose` switch turned on:
```
pipx install --verbose /local/path/to/git/repository
```

**Comment by itsayellow** [comment]
BTW, installing from a local directory is fully supported using pipx, but with `-e` and without.

**Comment by hydrargyrum** [comment]
I'm using Debian's pipx

```
% pipx --version
0.12.3.1
% pipx install --verbose --system-site-packages -e $PWD
pipx (run_pipx_command:125): Virtual Environment location is /local/path/to/git/repository
Not installing to existing directory '/local/path/to/git/repository'. Pass '--force' to force installation
```

**Comment by itsayellow** [comment]
Hmm, version 0.12.3.1 is pretty ancient (It's over a year and a half old).  Please try installing a new version of pipx and try again, there have been many many improvements since that version.

You can follow the user-install instructions to install a new version of pipx just for your user:
https://pipxproject.github.io/pipx/installation/
```
python3 -m pip install --user pipx
python3 -m pipx ensurepath
```

**Comment by itsayellow** [comment]
I'm going to close this, but feel free to reopen it if you find the same problem on a recent version of pipx.  

pipx certainly does support installing from a local path.
