### ISSUE TITLE
pipx upgrade exit codes should follow convention and indicate failure

### ISSUE THREAD

**Issue by noahnu** [pipxproject/pipx#497]
**Describe the bug**

Running `pipx upgrade <package>` returns "0" on a noop and "1" on success.

This means you can't determine if the command was successful or not. For example, if the shared venv was corrupted (a common occurrence when installing python with brew on mac), or any number of other reasons.

**How to reproduce**

Run pipx upgrade for an installed package with an old version.

**Expected behavior**

`pipx upgrade <package>` should return 0 on success, and 1 on failure.

A pattern that I've seen elsewhere is to provide a CLI flag for more granular exit codes. For example, terraform has a flag `-detailed-exitcode` which when set will return 0 on success (0 is _always_ success), 1 on generic error, 2 on success but with non-empty diff. E.g. https://www.terraform.io/docs/commands/plan.html#detailed-exitcode. At least this way, you can differentiate success modes from failure modes. If you're writing an automation script and you're "okay" with return code "2", you can capture it and allow the script to succeed.

Since this would be a breaking change, perhaps an extra CLI flag which changes the return code behaviour?

**Comment by itsayellow** [comment]
Yes that is bizarre.  At the very least `upgrade` should return 0 on success.  This must have just been a goof in the code (I can see in the code very clearly where this exit code is set.)

**Comment by itsayellow** [comment]
Some notes to the pipx maintainers.
* We need to add tests that actually upgrade a package, right now we only test upgrade on a package that is already fully upgraded
* `upgrade_all()` currently does not return any value (even though `main.py` expects a return value!)  This needs to be fixed.

**Comment by itsayellow** [comment]
Ah I see what the idea was in the code:  `upgrade-all()` is counting how many packages were successfully upgraded, and is summing the return values (0 for no-upgrade, 1 for upgrade successful) from `upgrade()`.

Unfortunately the same return value from `upgrade()` is also being used as the pipx exit code.  Thus the problem.
