### ISSUE TITLE
ansible install test is broken (`test_install_tricky_packages[ansible]`)

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#504]
**Describe the bug**

The ansible install test (`test_install_tricky_packages[ansible]`) seems to be failing with the latest version of ansible (2.10).  Trying to install ansible on my own system gives:
```
> pipx install ansible
Note: Dependent package 'ansible-base<2.11,>=2.10.1' contains 11 apps
  - ansible
  - ansible-config
  - ansible-connection
  - ansible-console
  - ansible-doc
  - ansible-galaxy
  - ansible-inventory
  - ansible-playbook
  - ansible-pull
  - ansible-test
  - ansible-vault

No apps associated with package ansible. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

It looks as though ansible split off their executables into ansible-base.

I don't really use or know ansible...does anybody know what the proper way to mend the tests is?  Should we just be installing `ansible-base`?  Or somehow make an exception for ansible in this test to use `--include-deps`?  Or just installing the previous version of ansible?

**How to reproduce**

**Expected behavior**

**Comment by cs01** [comment]
We should specify a version of ansible that we know works with pipx so the test is deterministic.  Installing the latest version (as is done now) means external state can change, which makes the test non deterministic. This is my fault, I think I wrote those tests.
