### ISSUE TITLE
Installation not pulling in optional extras-requires packages. 

### ISSUE THREAD

**Issue by washad** [pipxproject/pipx#515]
(Full disclosure, this issue is occurring after an OS upgrade, though I've uninstalled and re-installed pipx) -- great tool by the way!!

I have a project on Bitbucket (private). I have historically installed locally with pipx; 
`pipx install "my-project[cli] @ git+ssh://git@bitbucket.org/my-company/myproject.git"`

The setup.cfg for the project has an install-requires of
`[options.extras_require]`
```
cli =
    begins
    docker
```

Installing goes smoothly, but the `begins` and `docker` packages do not install. I verify by looking within `/home/steve/.local/pipx/venvs/my-project/lib/python/site-packages`

[pipx-verbose.txt](https://github.com/pipxproject/pipx/files/5330613/pipx-verbose.txt)

**Expected behavior**
Historically, this would have correctly detected the [cli] designation and installed the appropriate packages. I'm not sure if this has to do with a recent upgrade or something is broken on my end. 

If it is an issue on my part, can you recommend troubleshooting tips? 

Thank you, Sincerely, Steve Jackson

**Comment by itsayellow** [comment]
First of all, I ❤️ any issue that starts with props for pipx. 😄 

This is a little tricky to troubleshoot without seeing the package involved.  Are you not at liberty to share that?

Some questions that would be helpful to know: The last time this worked for you, do you remember the version of pipx?  Also, what OS are you using now and were you using before?

**Comment by itsayellow** [comment]
Just looking at the code I think I see the problem.  Pretty sure this is our fault.  Thanks for the issue!

**Comment by washad** [comment]
I noticed a call for a package to test with in the PR. 

I did a search on github and came up with this one;  [link](https://github.com/ftnext/python4kyoani). It looks like a command line application and has an optional [dev] install. Don't know if that helps.
