### ISSUE TITLE
[docs] Help text for `pip install` default python doesn't translate well to web

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#523]
**Describe the bug**

The help for `pipx install` currently has a paragraph explaining `PIPX_DEFAULT_PYTHON` which helpfully tells you what pipx views as your current default python.  The problem is when our web docs are generated, this part of the help code generates an unhelpful default python specific to the nox session:
```
The default python executable used to install a package is
~/work/pipx/pipx/.nox/docs/bin/python and can be overridden by setting the environment
variable `PIPX_DEFAULT_PYTHON`.
```

Also, another minor improvement would be to get this help text to properly wrap when being viewed from the command (It currently doesn't wrap on the console properly.)

**How to reproduce**

View our web docs that were generated from pipx code.

**Expected behavior**

I'm not exactly sure the best fix, but not putting `~/work/pipx/pipx/.nox/docs/bin/python` as the default python executable for the web docs.

**Comment by uranusjr** [comment]
One solution would be to detect an environment variable during documentation build, e.g. set `PIPX__DOC_INSTALL_PYTHON` in `conf.py` and display that if detected.
