### ISSUE TITLE
reinstall-all don't use the initial spec but install latest version of each packages

### ISSUE THREAD

**Issue by oncleben31** [pipxproject/pipx#527]
**Describe the bug**
When using the command `pipx resintall-all` the packages are uninstalled and installed again but without taking into account the spec used during the initial installation. it's mean it reinstall only latest version for each packages.

**How to reproduce**
`pipx install --suffix=1010 poetry==1.0.10` will install poetry 1.0.10
`pipx reinstall-all` will install poetry 1.1.3 

**Expected behavior**
The initial spec should be reused during reinstall-all or at least give an option to choose to have latest versions or initial versions.

**Comment by itsayellow** [comment]
Fair point.

Removing the version specifier after install was done intentionally as a way to enable a future `pipx upgrade` to actually be able to upgrade the package.  But doing it that way may have been too heavy-handed.

Maybe the best behavior is to leave the version specifier in the metadata after install, but remove the version specifier in the metadata if the user executes `pipx upgrade`.

Also, like you say, maybe we need an option to `pipx reinstall` that allows something like "default keep at version originally specified, optional upgrade everything to latest version."

**Comment by oncleben31** [comment]
Can you point me where the specifier is removed from the metadata. I can try to work on a fix.

**Comment by itsayellow** [comment]
Thanks for offering to help!

The function `pipx.package_specifier. parse_specifier_for_metadata` is involved with removing the version specifier.

Here is where we write the package specifier (referred to as `package_or_url` in our codebase) to metadata.
https://github.com/pipxproject/pipx/blob/4db161a6295df33aee82cba4242d27ebb02ca35b/src/pipx/venv.py#L308

Here is the definition of `parse_specifier_for_metadata`
https://github.com/pipxproject/pipx/blob/4db161a6295df33aee82cba4242d27ebb02ca35b/src/pipx/package_specifier.py#L159

I believe it should be as simple as changing the option `remove_version_specifiers=False` in the invocation of `_parsed_package_to_package_or_url(`

That is probably the easiest part.  

The next part would be to actually remove version specifiers before we upgrade a package, probably here:
https://github.com/pipxproject/pipx/blob/4db161a6295df33aee82cba4242d27ebb02ca35b/src/pipx/commands/upgrade.py#L45

**Comment by itsayellow** [comment]
If we don't remove the version specifier before upgrading, the code will be executing something like this:
```
pip install --upgrade <package>==<old_version>
```
Which pip will fail to upgrade because no upgraded version will still satisfy the version specification.

**Comment by oncleben31** [comment]
Thank you for the details information.
I'm trying to work on a fix. But I have difficulties to design a test to ensure `upgrade`command is still working.

```python
def test_upgrade_specifier(pipx_temp_env, capsys):
    name = "pylint"
    specifier = "==2.3.1"

    assert not run_pipx_cli(["install", f"{name}{specifier}"])
    assert not run_pipx_cli(["upgrade", f"{name}"])
    captured = capsys.readouterr()
    assert f"upgraded package pylint from 2.3.1 to" in captured.out
```
The second assert with the `upgrade` is failing without touching the current code of pipx. Do you have an idea why ?

```console
============================================ FAILURES =============================================
_____________________________________ test_upgrade_specifier ______________________________________

pipx_temp_env = None, capsys = <_pytest.capture.CaptureFixture object at 0x10adecf70>

    def test_upgrade_specifier(pipx_temp_env, capsys):
        name = "pylint"
        specifier = "==2.3.1"
    
        assert not run_pipx_cli(["install", f"{name}{specifier}"])
>       assert not run_pipx_cli(["upgrade", f"{name}"])
E       AssertionError: assert not 1
E        +  where 1 = run_pipx_cli(['upgrade', 'pylint'])

tests/test_upgrade.py:45: AssertionError
```

**Comment by oncleben31** [comment]
Ok I found the reason. Exit code is 1 after a version bump. Exit code 0 is when package is already at latest version.
