### ISSUE TITLE
Ansi default on Windows

### ISSUE THREAD

**Issue by ericfrederich** [pipxproject/pipx#546]
I'm on a fresh install of Windows with a fresh install of Python (for Windows 3.9.0).
I installed via

```bash
py -m pip install --user pipx
py -m pipx ensurepath
```

In both PowerShell and in cmd.exe running `pipx --ansi` produces nice colors.

Is there a reason it doesn't default to `--ansi` on Windows?

**Comment by itsayellow** [comment]
I'm a little confused...pipx doesn't have an `--ansi` option.

**Comment by ericfrederich** [comment]
I'm an idiot... please disregard.  I meant to put this on Poetry.
