### ISSUE TITLE
No apps associated with package ansible

### ISSUE THREAD

**Issue by laktak** [pipxproject/pipx#547]
**Describe the bug**

It's not possible to install ansible with pipx.

@pdecat shows a [workaround here](https://github.com/pipxproject/pipx/issues/20#issuecomment-705683989) - since this was a closed issue I'd like to know if this is a bug in pipx or not.

**How to reproduce**
```
$ pipx install ansible
Note: Dependent package 'ansible-base<2.11,>=2.10.3' contains 11 apps
  - ansible
  - ansible-config
  - ansible-connection
  - ansible-console
  - ansible-doc
  - ansible-galaxy
  - ansible-inventory
  - ansible-playbook
  - ansible-pull
  - ansible-test
  - ansible-vault

No apps associated with package ansible. Try again with '--include-deps' to include apps of dependent packages, which are listed above. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

**Comment by itsayellow** [comment]
This is not a bug in pipx.  It's just that the `ansible` package no longer has binaries associated with it specifically.  Binaries are only present in its dependent package `ansible-base`.

By default pipx only links binaries that come from the primary package.

You can do what pipx is telling you (`pipx install ansible --include-deps`) to link binaries from dependent packages, or you can use the workaround you describe.
