### ISSUE TITLE
Suffix with dash "-" inside

### ISSUE THREAD

**Issue by AdrienPensart** [pipxproject/pipx#561]
Running this command does not work : 

pipx install my-package.whl --suffix "-prerelease"

usage: pipx install [-h] [--include-deps] [--verbose] [--force]
                    [--suffix SUFFIX] [--python PYTHON]
                    [--system-site-packages] [--index-url INDEX_URL]
                    [--editable] [--pip-args PIP_ARGS]
                    package_spec
pipx install: error: argument --suffix: expected one argument

Tried : 
--suffix \-prerelease
--suffix ./-prerelease
--suffix "-prerelease"
--suffix '-prerelease'
--suffix -- -prerelease
--suffix -- '-prerelease'

**Comment by itsayellow** [comment]
try the longer form:
```
pipx install my-package.whl --suffix="-prerelease"
```

**Comment by AdrienPensart** [comment]
It's working, thx!
