### ISSUE TITLE
pipx inject binary

### ISSUE THREAD

**Issue by scolby33** [pipxproject/pipx#58]
`pipx inject` is great for adding an additional dependency, but what about adding an additional binary?

For instance, I use [beancount](https://github.com/beancount/beancount) and there is an optional web interface package [fava](https://github.com/beancount/fava). `pipx install beancount; pipx inject beancount fava` worked to install the fava package, but didn't symlink the binary.

Perhaps this functionality could be added to `pipx inject`? I'm not sure if it should be by default or as an option `pipx inject --link-binaries`, but either would work for me.

**Comment by cs01** [comment]
This is a good question.  Another question along the same lines is whether the initial install should look at all dependencies installed and expose their binaries as well.  

I think for this it would be pretty straightforward to make the api as you described. I can try to add it at some point.

**Comment by cs01** [comment]
This has been added in 0.12.3.0.
