### ISSUE TITLE
Using the root logger badly interacts with pytest

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#581]
**Describe the bug**

Because pipx uses the root logger, this causes problems with pytest.

Specifically, in pytest the root logger persists between tests, so every time we run another pipx test in the same pytest session, our `setup`-added handlers keep accumulating.  This causes the same message to be printed to STDERR many times over (multiple stream handlers).  It also causes attempts to print the message to old files that are now closed, which adds many logging errors (one error for each closed log file from a previous test.)

To fix I'm going to use the `logger = logging.getLogger(__name__)` syntax like we should've been doing all along.

**How to reproduce**

**Expected behavior**

**Comment by itsayellow** [comment]
Since we are running in a continuous pytest run, it seems that `logging` is never unloaded, so each invocation of `pipx.main.setup` layers more handlers for each test and is never reset as it would be in real life.

`logging.basicConfig` basically adds no handlers if it sees that there are pre-existing handlers.  Whereas now that we are using "Advanced Logging" and adding our own handlers, we have to take care of the case where there are pre-existing handlers (i.e. the handlers from other tests!)

**Comment by uranusjr** [comment]
Another solution would be to use something like `logging.config.dictConfig`, which would re-initialises (or replaces, not sure how it’s implemented internally) the loggers instead of adding on to them.

**Comment by itsayellow** [comment]
I didn't even see that there was a `logging.config` module, thanks.  Much better than what I was doing, using the semi-undocumented `logging.Logger.handlers` and manually deleting old handlers.

**Comment by itsayellow** [comment]
Another thing I noticed with the "accumulating logging handlers" situation was that memory usage kept climbing for my pytest run.  On another branch the OS actually shut down my pytest run because it ran out of memory, for a very large parameterized series of tests.  I think a ton of errors for trying to write to closed streams probably didn't help.
