### ISSUE TITLE
Windows 10 pipx Installations only work in the first command window you open

### ISSUE THREAD

**Issue by BruceEckel** [pipxproject/pipx#589]
![image](https://user-images.githubusercontent.com/1001900/102722224-eba9f100-42bc-11eb-8fad-7a98f9b74701.png)

If I open a second command window, it doesn't know about the pipx-installed command. It doesn't matter which window you try first, it's the second, third, etc. window that is opened that doesn't know about the command. This is also true for powershell windows.

If you open a second, third, etc. ***tab*** in the same command window, the pipx-installed command *does* work.

**Comment by itsayellow** [comment]
I'm not a Windows expert, but I believe this is just because the PATH (environment variable) settings don't change for new command windows until you logout and log back in to your account.

I would at least try logging out and logging in again, I think that might fix your problem.

**Comment by BruceEckel** [comment]
You are correct. After I logged out and in (or rebooted), then every different cli I installed with pipx was immediately available across any already-opened windows. So pipx itself was not completely installed without logging out and in.
