### ISSUE TITLE
pipx seems to use python 3.9 when it should be using 3.8

### ISSUE THREAD

**Issue by guyjacks** [pipxproject/pipx#591]
I installed pipx to install pipenv.

When I use pipenv to install Python packages it appears that its using python 3.9 (see python 3.9 in the file paths in the trace below).  python --version is 3.8 which is what I want.  pipenv is configured to use 3.8 in the virtualenv it creates and manages, but it seems to be using python 3.9 from pipx.

Installing initially failed dependencies...
[InstallError]:   File "/Users/guyjacks/.local/pipx/venvs/pipenv/lib/**python3.9**/site-packages/pipenv/cli/command.py", line 233, in install
[InstallError]:       retcode = do_install(
[InstallError]:   File "/Users/guyjacks/.local/pipx/venvs/pipenv/lib/python3.9/site-packages/pipenv/core.py", line 2052, in do_install
[InstallError]:       do_init(
[InstallError]:   File "/Users/guyjacks/.local/pipx/venvs/pipenv/lib/python3.9/site-packages/pipenv/core.py", line 1304, in do_init
[InstallError]:       do_install_dependencies(
[InstallError]:   File "/Users/guyjacks/.local/pipx/venvs/pipenv/lib/python3.9/site-packages/pipenv/core.py", line 899, in do_install_dependencies
[InstallError]:       batch_install(
[InstallError]:   File "/Users/guyjacks/.local/pipx/venvs/pipenv/lib/python3.9/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/Users/guyjacks/.local/pipx/venvs/pipenv/lib/python3.9/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Collecting cryptography==3.3.1
[pipenv.exceptions.InstallError]:   Using cached cryptography-3.3.1.tar.gz (539 kB)
[pipenv.exceptions.InstallError]: ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta in pyproject.toml
ERROR: Couldn't install package: cryptography

**Comment by itsayellow** [comment]
To install a python app using pipx to use a non-default python version, you need to use the `--python` flag with `pipx install`

Did you install pipenv like this?
```
pipx install pipenv --python python3.8
```

You can use `python3.8` if that's in your path, or the full path to the python3.8 executable.

**Comment by uranusjr** [comment]
To explain the behaviour: pipx by default installs applications using the Python itself is installed in, *not* the `python` command in `PATH`.

**Comment by itsayellow** [comment]
Closing this, feel free to reopen if you're still having trouble.
