### ISSUE TITLE
pipx ensurepath under ubuntu is broken

### ISSUE THREAD

**Issue by kghose** [pipxproject/pipx#597]
**Describe the bug**

`pipx ensurepath` does not add the correct path under Ubuntu

It does this:
```
Success! Added /home/runner/work/pipx-ubuntu-bux/pipx-ubuntu-
    bux/"/opt/pipx_bin" to the PATH environment variable.
```

**How to reproduce**

Please see the minimal example here: https://github.com/kghose/pipx-ubuntu-bux/blob/main/.github/workflows/bug.yaml

The initial commit includes `ubuntu` in the OS matrix and it fails: https://github.com/kghose/pipx-ubuntu-bux/actions/runs/486022607

Taking `ubuntu` out of the OS matrix results in the action succeeding on Windows and macOS: https://github.com/kghose/pipx-ubuntu-bux/runs/1703697490?check_suite_focus=true

**Expected behavior**

`pipx ensurepath` should work on ubuntu

pipx is awesome! Thank you for making it!

**Comment by itsayellow** [comment]
@kghose some questions:
* What shell are you using?
* Have you tried this in a non-CI Ubuntu shell?

pipx uses the `userpath` package, and it should modify `~/.profile` in a Ubuntu shell, if you're using bash.  Could you try to read back your `~/.profile` to see if a new `export PATH `... command has been added to the end of that file?

The problem in your CI environment may be that your second `run` step is not spawning a new **login** shell but only a plain shell.  `~/.profile` is read only when starting a new login shell.

One thing to try is to try explicitly adding the following `source` command in your `Test` step:
```
    - name: Test
      run: |
        source ~/.profile
        echo $PATH
        cowsay
```

**Comment by kghose** [comment]
@itsayellow , thank you for taking a look.

If you look at the log I linked to in the ticket you will see in them

```
25l⚠️  Note: '/home/runner/work/pipx-ubuntu-bux/pipx-ubuntu-bux/"/opt/pipx_bin"' is not on your PATH environment variable.
```

and

```
Success! Added /home/runner/work/pipx-ubuntu-bux/pipx-ubuntu-
    bux/"/opt/pipx_bin" to the PATH environment variable.
```

and from my echo path
```
/opt/hostedtoolcache/Python/3.6.12/x64/bin:/opt/hostedtoolcache/Python/3.6.12/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/opt/pipx_bin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

I can see that `/opt/pipx_bin` has been added to the path.

This is consistent with `/home/runner/work/pipx-ubuntu-bux/pipx-ubuntu-bux/"/opt/pipx_bin"` being a corrupted path string

But you must have seen the linked log, so I assume your interpretation is different?

**Comment by itsayellow** [comment]
Ohhh I see the main problem is that the path added is mangled?

**Comment by itsayellow** [comment]
Do you know what the proper path to add should be?

**Comment by itsayellow** [comment]
Also, your pipx doesn't look like the new pipx.  It looks like the output of `pipx ensurepath` is giving you output that would imply it is an old version.  You may be picking up an old pipx on your system and not the one you just installed in the first step.

For your second step, when you run pipx, could you also execute:
```
pipx --version
```

You might rewrite your ensurepath step as this:
```
- name: Install test dependencies
      run: |
        pip install pipx
        python3 -m pipx install cowsay
        python3 -m pipx ensurepath
```

**Comment by kghose** [comment]
Hi @itsayellow thanks for taking a look.

In the latest run (https://github.com/kghose/pipx-ubuntu-bux/runs/1718277851?check_suite_focus=true) we have

```
Collecting pipx
  Downloading pipx-0.16.0.0-py3-none-any.whl (48 kB)
```

And

```
pipx --version
0.16.0.0
```
Which I believe is the latest one.

**Comment by itsayellow** [comment]
The only thing I can think of is that there are pipx environment variables that are messed up, which would create this odd path.

Can you check the environment variables in your run for `PIPX_HOME` and `PIPX_BIN_DIR`?
```shell
echo "PIPX_HOME=$PIPX_HOME"
echo "PIPX_BIN_DIR=$PIPX_BIN_DIR"
```

**Comment by kghose** [comment]
Hi @itsayellow 

```
"/opt/pipx"
"/opt/pipx_bin"
```
respectively

https://github.com/kghose/pipx-ubuntu-bux/runs/1718380415?check_suite_focus=true

**Comment by kghose** [comment]
This line: https://github.com/kghose/pipx-ubuntu-bux/runs/1718427042?check_suite_focus=true#step:5:56 is odd. Might be an indication there are some extraneous characters there.

**Comment by itsayellow** [comment]
Good point, I think those quotes are the problem.  To test this, before running pipx, you could try setting them to the same paths, but without the quotes:
```
export PIPX_HOME=/opt/pipx
export PIPX_BIN_DIR=/opt/pipx_bin
```

@kghose, it doesn't look like you are setting those environment variables, correct?  I wonder what is setting them, whether it's Ubuntu or Github.

**Comment by itsayellow** [comment]
Just looked on my Ubuntu 20.04 and I don't see those environment variables set.  This may be particular to Github's (or Microsoft Azure's?) runners.

**Comment by kghose** [comment]
@itsayellow you are correct sir! 

https://github.com/kghose/pipx-ubuntu-bux/runs/1718804227?check_suite_focus=true#step:5:13

Why in the world would they set this? And why would they set this incorrectly? Anyhoo. Thank you for your help! I will close this and open a github ticket I guess (?).

**Comment by itsayellow** [comment]
Glad you have a solution, and I would give my heartfelt thanks if you opened a github ticket! 👍  I'm sure other users will encounter the same problem.

**Comment by kghose** [comment]
https://github.community/t/pipx-env-variables-set-incorrectly/156093
