### ISSUE TITLE
Windows CMD - colors and Symbols are not displayed correctly

### ISSUE THREAD

**Issue by CarliJoy** [pipxproject/pipx#603]
**Describe the bug**
Using Windows 10 colors and symbols are not displayed.

**How to reproduce**
Install pipx with Python 3.8 on Windows 10 like described in the documentation.
Use any pipx command with cmd.

**Expected behavior**
Symbol and Colors are displayed like in a bash shell.

What I currently get is:

![2021-01-20_14h04_14](https://user-images.githubusercontent.com/7687556/105182045-dda1f700-5b2c-11eb-9f36-f98e39695503.gif)

**Comment by uranusjr** [comment]
Looks like there is an issue in your console configuration. Does color in other programs (e.g. pip) work?

**Comment by CarliJoy** [comment]
> Looks like there is an issue in your console configuration. Does color in other programs (e.g. pip) work?

Yep you're right:
https://superuser.com/questions/413073/windows-console-with-ansi-colors-handling/1050078#1050078
I have Windows 10 build 14393 - too old for ANSI support.

But coloring in pip actually works - no Idea how they do that:
![2021-01-20_15h30_53](https://user-images.githubusercontent.com/7687556/105189422-3d040500-5b35-11eb-9e15-0c452a9724be.png)


Also with pipenv it works like a charm without ANSI support.
![2021-01-20_15h35_35](https://user-images.githubusercontent.com/7687556/105189468-48efc700-5b35-11eb-9fec-1bbf066f7a32.gif)

**Comment by uranusjr** [comment]
Both pip and pipenv use colorama for colors, which is based on Windows API, not ANSI codes. Maybe pipx can use it as well.

With that said, I just noticed pipx’s code base actually turns all colors off on Windows, so those escape codes are likely not colors at all. I wonder where those come from. `argcomplete`?

**Comment by itsayellow** [comment]
I think those *may* be the `HIDE_CURSOR` `SHOW_CURSOR` codes for shells.
https://github.com/pipxproject/pipx/blob/5c3cc823ab780f4d562e5e8c1ed0c31aee893133/src/pipx/animate.py#L12-L13

**Comment by uranusjr** [comment]
Or use a platform-specific solution on Windows? There are Windows APIs for this: https://stackoverflow.com/a/10455937/1376863

**Comment by itsayellow** [comment]
I always am annoyed with Windows because there are so many different shells, and they all seem to behave differently, especially when trying to do anything more than print text.  I wonder if the solution in the stackoverflow link works for all the shells people use.

**Comment by itsayellow** [comment]
I suppose to truly fix this we should investigate something like [colorama](https://github.com/tartley/colorama) and [cursor](https://github.com/GijsTimmers/cursor).

And then somebody would have to try it in every Windows shell to see which one(s) it fails in 😉

**Comment by CarliJoy** [comment]
> And then somebody would have to try it in every Windows shell to see which one(s) it fails in wink

I could offer to test 
* Windows CMD
* Integrated Terminal in PyCharm
* GIT Bash (in Windows)
* Maybe Powershell


-> actually I don't know more ;-)

**Comment by itsayellow** [comment]
@CarliJoy, could you test the linked PR and see if it stops printing cryptic characters in your Windows shells?

**Comment by CarliJoy** [comment]
With `--version` it works.
But during install they are still there:


![2021-01-24_16h16_57](https://user-images.githubusercontent.com/7687556/105634755-fd545a80-5e5f-11eb-82d5-a2ab25e8183d.gif)

**Comment by itsayellow** [comment]
Hmm, ok.  Does the released pipx version fail the same way for `pipx install`?  Or is this a regression with this PR?

**Comment by itsayellow** [comment]
Ah got it!  `\033[K` is the ANSI code for "clear line" which we use for animation.  OK, that's something else to fix.

**Comment by itsayellow** [comment]
It looks like `\033[K` will be translated correctly with the fix in #612

**Comment by itsayellow** [comment]
Thanks for your help testing @CarliJoy .

**Comment by CarliJoy** [comment]
shall I test your fix in #612 again?
Thanks for writing the code :+1:

**Comment by itsayellow** [comment]
If you have some time testing #612 would be great.  For #612 you will still see `[?25l` and `[?25h` but it should fix the animation problems with `pipx install`.  (If it doesn't, it would be good to know!)

**Comment by CarliJoy** [comment]
Double Posting from #612 

Current Result on Windows:

![2021-01-27_14h51_03](https://user-images.githubusercontent.com/7687556/106000703-6a116400-60af-11eb-9efa-ee44cbb05671.gif)
