### ISSUE TITLE
Implement better handling of pip errors

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#613]
I came across this piece of negative feedback about pipx and I think reflecting on negative feedback is very valuable https://twitter.com/carltongibson/status/1353766968663429120

> ansible ... 
SOME LOAD OF NOISE ABOUT HOW SOMETHING BROKE WITHOUT ANY ADVISE ON A SIMPLE WAY TO FIX IT

Admittedly this isn’t a concrete error, but maybe there is something we can take from it. Perhaps an audit of all the error messages to ensure there is a succinct fix.

**Comment by itsayellow** [comment]
It's hard to know what he's experiencing with this level of detail... 😆 

It could be that he's getting the pip error that we pipe through to the user when pip has a failure.  Although in that case I'm not sure why virtualenvwrapper would work and pipx wouldn't.

**Comment by itsayellow** [comment]
I have often wondered about the utility of the pip errors we pass through.  Especially with something that includes compilation steps, you can get pages and pages of "noise" as he says.

**Comment by itsayellow** [comment]
Or is he getting a problem while *running* ansible?

**Comment by itsayellow** [comment]
Also some of the buried comments from another user talk about how possibly the problem might be ansible **with plugins**.  So it might be that something else in the same venv was needed and missing or malfunctioning.

**Comment by uranusjr** [comment]
The comment sounds weird to me as well (and I suspect Jeff Triplett felt the same, hence the inquiry). If virtualenvwrapper is the alternative, pipx probably isn’t a good tool for what he’s trying to do in the first place.

**Comment by cs01** [comment]
Thanks guys. If you think there is nothing further that needs to be done feel free to close. I just wanted to flag it in case there is anything we can take from it.

**Comment by itsayellow** [comment]
I am curious what people think about piping through the entire pip response in case of a pip error.  For experienced users this can show what's wrong.  But if you're not an experienced user it is easily overwhelming.

I've thought of the possibility of saving the full pip output into a separate error file in case of pip error, and then letting the user know where to find it.  (possibly in `pipx/logs`.)  However this might annoy the experienced users who just want to see what went wrong immediately.

We could also save the full pip output to a file, while try to grep it for the specific error to show to the user right away.

I've seen a lot of pages of pip error outputs when developing the slow tests that test many many packages, and I will say they were often overwhelming to me.

**Comment by cs01** [comment]
I think you are on to something. Pipx is trying to provide a layer of abstraction over pip, so the better we can do that the better the UX. I am thinking we can do a few things to help:

* only display the last n characters of pip output 
* make the output visually distinct from pipx output, such as indenting, using a muted color like grey, etc 
* Display path to full pip output for further investigation if desired 
* If verbose is true, print it inline
* Do not add any new flags to pipx to tweak how this is handled since they will further complicate the api, and we should be able to set good enough defaults

**Comment by itsayellow** [comment]
I like that.  I think it would be a significant improvement in UX.

Should we rename this Issue or start a new one?

**Comment by cs01** [comment]
Leaving in this one is fine if you want to rename it and run with the implementation?

**Comment by itsayellow** [comment]
I'm not sure I have the bandwidth to do this properly right now.  Although I think it's a worthy endeavor.

**Comment by itsayellow** [comment]
Looking at the old artifacts from the CI "slow" tests, it seems that usually the most salient line from a pip session that ends in error is the one starting with "Failed to build".  That line seems to show every package (main or dependency) that failed to build in that pip session.

This line seems to occur sometimes in stdout and sometimes in stderr.  In general it seems that there pip outputs both a sizeable stderr and a sizeable stdout with somewhat different information in each, but I can't tell how it decides what output to send to which stream.

**Comment by itsayellow** [comment]
Well I just tried installing 'mayan-edms' in my macOS Python 3.9.  It fails, but it never prints the string "Failed to build".  🤷 So maybe that phrase isn't universal or maybe pip has started to output different error messages.

**Comment by itsayellow** [comment]
Ah ok, it says "Failed to build" when `wheel` is installed.  If `wheel` isn't installed it says other things.

**Comment by itsayellow** [comment]
from pfmoore in https://github.com/pypa/pip/issues/6104#issuecomment-450681450:
> I'd argue at least in part that the tool that calls pip should be catching the errors, and presenting them to you in a more helpful way, and not just dumping pip's error output on you (after all, pip is a tool for Python developers, so its output assumes a set of skills and knowledge that you don't have).
😄

**Comment by itsayellow** [comment]
Just posted this:
https://github.com/pypa/pip/issues/6959#issuecomment-767403725

Hopefully it's on-topic and useful to pip.

**Comment by itsayellow** [comment]
Here's an example of stdout, stderr from pipx trying to install `mayan-edms` on Windows 10.  With `wheel` installed there is no phrase "Failed to build".  I'm curious if somebody more knowledgeable than I understands why.  Is `wheel` not applicable for package `pycryptodome`, which is the one failing, so `wheel` is not being used?  Or is it the use of `distutils`?

It's a tough one to parse errors from, because there's no clear line saying that `pycryptodome` has failed to build, there's just a lot of errors where the only clue that they refer to `pycrptodome` is that that string is in the name of the temp directory involved. ☹️ 

<details>

```
creating virtual environment...
installing mayan-edms...
STDOUT
Collecting mayan-edms
  Using cached mayan_edms-3.5.5-py2.py3-none-any.whl (5.0 MB)
Collecting bleach==3.1.5
  Using cached bleach-3.1.5-py2.py3-none-any.whl (151 kB)
Collecting celery==4.4.7
  Using cached celery-4.4.7-py2.py3-none-any.whl (427 kB)
Collecting django==2.2.16
  Using cached Django-2.2.16-py3-none-any.whl (7.5 MB)
Collecting django-activity-stream==0.8.0
  Using cached django-activity-stream-0.8.0.tar.gz (29 kB)
Collecting django-celery-beat==2.0.0
  Using cached django_celery_beat-2.0.0-py2.py3-none-any.whl (37 kB)
Collecting django-colorful==1.3
  Using cached django_colorful-1.3-py2.py3-none-any.whl (10 kB)
Collecting django-cors-headers==3.2.1
  Using cached django_cors_headers-3.2.1-py3-none-any.whl (14 kB)
Collecting django-formtools==2.2
  Using cached django_formtools-2.2-py2.py3-none-any.whl (148 kB)
Collecting django-mathfilters==1.0.0
  Using cached django_mathfilters-1.0.0-py3-none-any.whl (5.9 kB)
Collecting django-model-utils==4.0.0
  Using cached django_model_utils-4.0.0-py2.py3-none-any.whl (29 kB)
Collecting django-mptt==0.11.0
  Using cached django_mptt-0.11.0-py2.py3-none-any.whl (109 kB)
Collecting django-pure-pagination==0.3.0
  Using cached django-pure-pagination-0.3.0.tar.gz (10 kB)
Collecting django-qsstats-magic==1.1.0
  Using cached django-qsstats-magic-1.1.0.tar.gz (8.6 kB)
Collecting django-solo==1.1.3
  Using cached django-solo-1.1.3.tar.gz (8.9 kB)
Collecting django-stronghold==0.4.0
  Using cached django_stronghold-0.4.0-py2.py3-none-any.whl (9.9 kB)
Collecting django-widget-tweaks==1.4.8
  Using cached django_widget_tweaks-1.4.8-py2.py3-none-any.whl (11 kB)
Collecting djangorestframework==3.11.0
  Using cached djangorestframework-3.11.0-py3-none-any.whl (911 kB)
Collecting djangorestframework-recursive==0.1.2
  Using cached djangorestframework_recursive-0.1.2-py2.py3-none-any.whl (4.4 kB)
Collecting drf-yasg==1.17.1
  Using cached drf_yasg-1.17.1-py2.py3-none-any.whl (1.1 MB)
Collecting extract-msg==0.23.3
  Using cached extract_msg-0.23.3-py2.py3-none-any.whl (45 kB)
Collecting flanker==0.9.11
  Using cached flanker-0.9.11.tar.gz (105 kB)
Collecting flex==6.14.1
  Using cached flex-6.14.1.tar.gz (40 kB)
Collecting furl==2.1.0
  Using cached furl-2.1.0-py2.py3-none-any.whl (20 kB)
Collecting fusepy==3.0.1
  Using cached fusepy-3.0.1.tar.gz (11 kB)
Collecting gevent==20.4.0
  Using cached gevent-20.4.0.tar.gz (5.5 MB)
  Installing build dependencies: started
  Installing build dependencies: still running...
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting graphviz==0.14
  Using cached graphviz-0.14-py2.py3-none-any.whl (18 kB)
Collecting gunicorn==20.0.4
  Using cached gunicorn-20.0.4-py2.py3-none-any.whl (77 kB)
Requirement already satisfied: setuptools>=3.0 in c:\users\mclapp\.local\pipx\shared\lib\site-packages (from gunicorn==20.0.4->mayan-edms) (51.3.3)
Collecting imapclient==2.1.0
  Using cached IMAPClient-2.1.0-py2.py3-none-any.whl (73 kB)
Collecting mock==4.0.2
  Using cached mock-4.0.2-py3-none-any.whl (28 kB)
Collecting node-semver==0.8.0
  Using cached node_semver-0.8.0-py3-none-any.whl (24 kB)
Collecting olefile==0.46
  Using cached olefile-0.46.zip (112 kB)
Collecting packaging==20.3
  Using cached packaging-20.3-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: pyparsing>=2.0.2 in c:\users\mclapp\.local\pipx\shared\lib\site-packages (from packaging==20.3->mayan-edms) (2.4.7)
Collecting Pillow==7.1.2
  Using cached Pillow-7.1.2.tar.gz (38.9 MB)
Collecting pycountry==19.8.18
  Using cached pycountry-19.8.18.tar.gz (10.0 MB)
Collecting pycryptodome==3.9.7
  Using cached pycryptodome-3.9.7.tar.gz (15.5 MB)

STDERR
  WARNING: In the tar file C:\Users\mclapp\AppData\Local\Temp\pip-unpack-xe0ph791\django-activity-stream-0.8.0.tar.gz the member django-activity-stream-0.8.0/CHANGELOG.rst is invalid: unable to resolve link inside archive
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\mclapp\.local\pipx\venvs\mayan-edms\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mclapp\\AppData\\Local\\Temp\\pip-install-pmhu53se\\pycryptodome_616b28aa74f94014ae904e150f68c737\\setup.py'"'"'; __file__='"'"'C:\\Users\\mclapp\\AppData\\Local\\Temp\\pip-install-pmhu53se\\pycryptodome_616b28aa74f94014ae904e150f68c737\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mclapp\AppData\Local\Temp\pip-pip-egg-info-_2oce2vs'
         cwd: C:\Users\mclapp\AppData\Local\Temp\pip-install-pmhu53se\pycryptodome_616b28aa74f94014ae904e150f68c737\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mclapp\AppData\Local\Temp\pip-install-pmhu53se\pycryptodome_616b28aa74f94014ae904e150f68c737\setup.py", line 455, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\mclapp\AppData\Local\Temp\pip-install-pmhu53se\pycryptodome_616b28aa74f94014ae904e150f68c737\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\mclapp\AppData\Local\Temp\pip-install-pmhu53se\pycryptodome_616b28aa74f94014ae904e150f68c737\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\mclapp\AppData\Local\Temp\pip-install-pmhu53se\pycryptodome_616b28aa74f94014ae904e150f68c737\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "C:\Program Files\Python39\lib\distutils\_msvccompiler.py", line 323, in compile
        self.initialize()
      File "C:\Program Files\Python39\lib\distutils\_msvccompiler.py", line 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "C:\Users\mclapp\.local\pipx\shared\Lib\site-packages\setuptools\msvc.py", line 313, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "C:\Users\mclapp\.local\pipx\shared\Lib\site-packages\setuptools\msvc.py", line 267, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

</details>

**Comment by itsayellow** [comment]
The best we may hope for given pip's current output is to signal that pip encountered a fatal error "installing the <main package> or one of its dependencies", and *possibly* find out what the offending dependency(s) was and if so list that/them.

**Comment by itsayellow** [comment]
I actually have a [branch](https://github.com/itsayellow/pipx/tree/pip-error) working pretty well to make a more presentable pip error display.  It needs some more code polishing and tests, but I like the output.

The output progresses from most reliable information on what happened with pip to least reliable.
* link to full pip output (always works)
* Which packages failed to build (as far as I can tell always works). For those sessions that do not show "Failed to build" in the pip output, it appears by simply observing the last package showing "Collecting \<package name\>" in stdout we can find the package that failed to build.
* Other errors that are hopefully useful, while omitting useless pip output (mostly works)

example:
```
(venv39) PS C:\Users\mclapp\git\pipx> pipx install magic-wormhole==0.12.0
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\mclapp\.local\pipx\logs\cmd_2021-01-30_20.09.13_pip_errors.log
pip failed to build package:                   
    twisted                 
Possibly relevant errors from pip install:
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
    ERROR: Failed building wheel for twisted                                       
Error installing magic-wormhole from spec 'magic-wormhole==0.12.0'.       
```

Another example:
```
(venv39) PS C:\Users\mclapp\git\pipx> pipx install weblate               
Fatal error from pip prevented installation. Full pip output in file:
    C:\Users\mclapp\.local\pipx\logs\cmd_2021-01-30_20.16.04_pip_errors.log
pip seemed to fail during the build of package:
    borgbackup<1.2.0,>=1.1.9
Possibly relevant errors from pip install:
    Exception: Unable to find OpenSSL >= 1.0 headers. (Looked here: /usr, /usr/local, /usr/local/opt/openssl, /usr/local/ssl, /usr/local/openssl, /usr/local/borg, /opt/local, /opt/pkg)

Error installing weblate.
```
