### ISSUE TITLE
De-parallelize `pipx list`

### ISSUE THREAD

**Issue by itsayellow** [pipxproject/pipx#616]
**How would this feature be useful?**

`pipx list` uses `multiprocessing.Pool` to parallelize venv analyses.  On my system, this **always takes longer** than if I force the code to run sequentially by inserting the line `Pool = None` before the `if Pool:` statement.

I've tested with 59 venvs, and I've tested with only a few venvs, and always the sequential for-loop is faster than the `multiprocessing.Pool` method.

This could be because I have an SSD drive, but it makes me wonder in general if using multiprocessing for this is worth it, or if it's often worse than the simpler sequential method.

On my test case with 59 pipx-installed packages:
`time pipx list`: 3.13s (multiprocessing code) 0.88s (sequential code)

On my test case with 7 pipx-installed packages:
`time pipx list`: 1.84s (multiprocessing code) 0.15s (sequential code)

I'm curious if other people find the same behavior on other systems.

**Describe the solution you'd like**

Get rid of `multiprocessing` code in `command/list_packages.py`, only use the fallback sequential code.

**Describe alternatives you've considered**

**Comment by itsayellow** [comment]
I just tested this with all the relevant pipx directories mapped to the slowest USB thumb drive I could find 😆 

Slow USB drive 59 pipx-installed packages:
`time pipx list`: 2.90s (multiprocessing code) 0.70s (sequential code)

I'm starting to feel like this is as conclusive as I'm likely to get.  The sequential code is better.

It makes sense really, because this code is not compute-limited, and so shouldn't really be a use case for multiprocessing code.  We're probably getting penalized by the overhead in spawning the extra processes.

**Comment by itsayellow** [comment]
The same is true on my Windows VM:

Winows VM 4 pipx-installed packages:
`Measure-Command { pipx list }`: 0.49s (multiprocessing code) 0.27s (sequential code)

Winows VM 12 pipx-installed packages:
`Measure-Command { pipx list }`: 0.49s (multiprocessing code) 0.27s (sequential code)

Winows VM 54 pipx-installed packages:
`Measure-Command { pipx list }`: 0.57s (multiprocessing code) 0.39s (sequential code)

I have no idea if a Virtual Machine is a realistic test for Windows, but at least the sequential code still seems faster.

**Comment by gaborbernat** [comment]
Let's do this 👍🏻
