### ISSUE TITLE
Pipx & Virtual Environments

### ISSUE THREAD

**Issue by chrisfinazzo** [pipxproject/pipx#617]
**Describe the bug**

*Disclaimer*: I am new to Python, apologies if this question has been answered elsewhere.

I want to create a virtual environment which contains its own version of Python and a tool which will be used in several different projects. `pipx run APP` seems to do this, but the environments are more temporary than I would want.

Previously, I tried to do this using pyenv + pyenv-virtualenv, but couldn't get it to work consistently. In addition, the virtualenv plugin [appears][] to be abandoned, so I need an alternative.

[appears]: https://github.com/pyenv/pyenv-virtualenv/issues/374

**Expected behavior**
Having come from rbenv, I expected similar behavior but was disappointed. E.g, a `.python-version` file with the version of Python that I installed and the environment switches automatically when I navigate to this directory.

With this in mind, what is the current best practice for using virtual environments with pipx? For reference, `.local` with v3.9 is shown below to illustrate my current setup.

<img width="770" alt="Screen Shot 2021-01-31 at 2 21 56 PM" src="https://user-images.githubusercontent.com/1534882/106395327-b4585500-63cf-11eb-8a31-8f35f33d48d9.png">

**Comment by itsayellow** [comment]
You probably want to install your app using `pipx install` with the `--python` option
```
pip install --python /path/to/python my-package
```
Which will install `my-package` and adds whatever apps / binaries it has associated with it in `~/.local/bin` if you are using the default settings.

If `~/.local/bin` is in your PATH (perhaps using `pipx ensurepath` once) then you should be able to use those apps from your shell.

pipx is a wrapper around the plain python virtual environment, so if you want more control you can investigate that
https://docs.python.org/3/tutorial/venv.html

**Comment by itsayellow** [comment]
@chrisfinazzo are you good?  Can we close this issue?

**Comment by chrisfinazzo** [comment]
@itsayellow I think so. I ended up continuing with the configuration I described - just using the built-in `venv` module and it seems to work fine.
