### ISSUE TITLE
Libraries from the local folder are not imported

### ISSUE THREAD

**Issue by mmozos** [pipxproject/pipx#623]
**Describe the bug**
With the latest version ([0.16.0.0](https://github.com/pipxproject/pipx/releases/tag/0.16.0.0)) the libraries from the local folder `__pypackages__` are not imported.

**How to reproduce**

`python3  -m pip install --user pythonloc`
`python3 -m pipx ensurepath`
`piploc install flask`
`pipx run --pypackages flask`

**Traceback**
```
Traceback (most recent call last):
  File "/home/martin/workspace/flask-desktop/__pypackages__/3.8/lib/bin/flask", line 5, in <module>
    from flask.cli import main
ModuleNotFoundError: No module named 'flask'
```

**Expected behavior**

It should show the following:
```
Usage: flask [OPTIONS] COMMAND [ARGS]...

  A general utility script for Flask applications.

  Provides commands from Flask, extensions, and the application. Loads the
  application defined in the FLASK_APP environment variable, or from a
  wsgi.py file. Setting the FLASK_ENV environment variable to 'development'
  will enable debug mode.

    $ export FLASK_APP=hello.py
    $ export FLASK_ENV=development
    $ flask run

Options:
  --version  Show the flask version
  --help     Show this message and exit.

Commands:
  db      Perform database migrations.
  lint    Lint and check code style with 'flake8' and 'isort' recursively.
  ps      Perform postgres operations.
  roles   Role commands.
  routes  Show the routes for the app.
  run     Run a development server.
  shell   Run a shell in the app context.
  users   User commands.
```

**Comment by itsayellow** [comment]
@cs01, any ideas?  I think you're the resident `pythonloc` expert.  :) 

It looks as though `pipx run` is finding the console script and running it, but that somehow the libraries aren't available.

**Comment by itsayellow** [comment]
@mmozos just a guess looking at the code:  Have you changed python versions lately?  Could pipx be running from a different python version than the flask you installed?

It looks like our code adds `__pypackages_/<python_version>/lib` to env variable PYTHON_PATH before running your `flask` app.  pipx determines `<python_version>` by using its own python version.  If that's different than what you have for flask (3.8) then that might explain why it isn't working.

**Comment by itsayellow** [comment]
Ohhh I see what's happening.  One part of our code `run_pypackage_bin` adds the `__pypackages__` path to env variable `PYTHONPATH`, and then `exec_app` uses `_fix_subprocess_env` to remove `PYTHONPATH` before running the code.

Here is the helpful comment in the code:
```
    # Remove PYTHONPATH because some platforms (macOS with Homebrew) add pipx
    #   directories to it, and can make it appear to venvs as though pipx
    #   dependencies are in the venv path (#233)
```
Hmmm.  Seems we have a fix in conflict with the operation of a feature.

**Comment by itsayellow** [comment]
I think probably the quickest fix would be to change `_fix_subprocess_env` so instead of completely removing `PYTHONPATH`, it removes it unless there is a path starting with `__pypackages__`.  If there is such a path(s), then it leaves only those in.

**Comment by mmozos** [comment]
> @mmozos just a guess looking at the code: Have you changed python versions lately? Could pipx be running from a different python version than the flask you installed?
> 
> It looks like our code adds `__pypackages_/<python_version>/lib` to env variable PYTHON_PATH before running your `flask` app. pipx determines `<python_version>` by using its own python version. If that's different than what you have for flask (3.8) then that might explain why it isn't working.
> 
> **EDIT**: Hmm this may not explain anything. It looks like our code should use the same root path for both the console script binary and the libraries. So if it finds the console script I'm not sure why it isn't adding the right path for the supporting packages.

I am using the only one and the default python version that comes in Linux Mint 20.04.
