### ISSUE TITLE
reinstall-all lost injected packages.

### ISSUE THREAD

**Issue by MisLink** [pipxproject/pipx#63]
In my case, I always `inject` a lot of flake8 plugins to flake8.

Would it be possible that injected packages should be recorded so that it is clear which ones should be reinstalled together? 
Furthermore, it would be a big help if there's an extra option that pipx does the job.

**Comment by cs01** [comment]
I think this can be done by capturing the output of `pip freeze` before uninstalling, then running `pip install` on its output when reinstalling. I will add this.

**Comment by itsayellow** [comment]
fixed via #222
