### ISSUE TITLE
Unable to pipx install dicttoxml

### ISSUE THREAD

**Issue by digitensions** [pipxproject/pipx#642]
Hi there,
I've got pipx to safely install packages for scripts across multiple Ubuntu virtual machines. I'm pretty new to python3 installations, so relieved such a product exists. Hope my issue isn't too basic for this bug tracker, or that it hasn't been discussed before.

**Describe the bug**
I can't install dicttoxml, despite it being available via PyPi.org and easily installable in a venv I create myself. It's a pretty critical element to many of the scripts I need to work with so would love for this to work and have it available safely, globally.

**How to reproduce**
Working with Ubuntu VM 20.04, Python 3.8. Pip3 installation of pipx.
When I use regular installation `pipx install dicttoxml` I get this message returned:
`No apps associated with package dicttoxml or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.`

**Expected behavior**
I've successfully installed flake8 and pylint so far, so would appreciate any advice.

**Comment by uranusjr** [comment]
What do you intend to use the installed `dicttoxml`? The package does not have “script entry point”, i.e. something to run from the command line (not in Python code), which is what pipx is for.

**Comment by digitensions** [comment]
Ah okay, that's my problem. Sorry! I didn't realise pipx was just for running from command line only. I should've though looking at the metadata sys.argv commands which would only work for CLI stuff.
