### ISSUE TITLE
Respect poetry lock files?

### ISSUE THREAD

**Issue by meandmymind** [pipxproject/pipx#668]
**How would this feature be useful?**
When installing [poetry](https://github.com/python-poetry/poetry) via `poetry` itself, it respects `poetry.lock` file that contains some locked dependencies that are not locked in `poetry`'s `pyproject.toml`.

I was having troubles while `pipx install ./my-local-poetry-fork`. `poetry`'s `pyproject.toml` contains unlocked dependency `poetry-core = { git = "https://github.com/python-poetry/poetry-core", branch = "master"}` while lock file contains locked version of it
```
[[package]]
name = "poetry-core"
version = "1.1.0a0"
description = "Poetry PEP 517 Build Backend"
category = "main"
optional = false
python-versions = "^3.6"
develop = false
```

So `poetry install` gives `poetry-core==`1.1.0a0` while `pipx install` gives latest `poetry-core` master which is now `==1.1.0a3` that breaks poetry installation.

**Describe the solution you'd like**
Reuse locked dependencies from poetry.lock somehow?

**Describe alternatives you've considered**
For now I had to copy locked dependency version from `poetry.lock` to `pyproject.toml` 

Maybe this issue is with `poetry` package as they are doing bad things leaving `poetry-core@master` tag in `pyproject.toml`?

**Comment by uranusjr** [comment]
IMP installing from a lock file is a good idea, but installing from `poetry.lock` is not. Lock files are considered an implementation detail of the tool (Poetry in this case), almost entirely undocumented, and subject to change across versions. This will be a rabbit hole too deep to go down IMO.

When Python ever gets a standard lock file format (hint hint), pipx should support installing from it (exactly how it should do it is another discussion).

**Comment by meandmymind** [comment]
@uranusjr yeah now I see this. I guess `pip` would support standartized lock files and `pipx` will just pass it as a PACKAGE_SPEC to `pip`.

**Comment by uranusjr** [comment]
For now, the best solution would be to `poetry export` to a temporary directory and do `pipx install main-package-to-expose --pip-args="-c $PATH_TO_EXPORT"`.

For directly installing into pip, you can do `pip install main-package-to-expose -c <(poetry export)` in bash, but pipx currently doesn’t seem to pipe stdin to subprocess, unfortunately 🙂
