### ISSUE TITLE
Can I run pipx with a proxy network?

### ISSUE THREAD

**Issue by TaskeHAMANO** [pipxproject/pipx#669]
Hi! Thank you for providing such a great tool.

I would like to ask about an usage with proxy network, like a company environment. When I use `pip`, this feature can use with `pip install numpy --proxy=http://...`., but it seems that `pipx` does not have this feature, right?

**How would this feature be useful?**
Network with proxy is not so unique in commercial use. This feature extends the library demand.

**Describe the solution you'd like**
I am appreciate if I could use it same with the `pip`.
`pipx install --proxy=http://...`

**Describe alternatives you've considered**
None.

**Comment by uranusjr** [comment]
YOu can use `--pip-args` to pass arguments to pip.

**Comment by itsayellow** [comment]
More info:
https://pipxproject.github.io/pipx/troubleshooting/#specifying-pipx-options

Also, pipx should respect pip configuration if you've set it with a pip config file or with `PIP_*` environment variables.

**Comment by TaskeHAMANO** [comment]
@uranusjr and @itsayellow 

Thanks for sharing the information! Your instructions work well.

```bash
set PIP_PROXY=http://...
pipx install ...
```
