### ISSUE TITLE
Use pip.conf to configure installation

### ISSUE THREAD

**Issue by abingham** [pipxproject/pipx#675]
**How would this feature be useful?**
It would mean that pipx and pip would behave the same, e.g. by drawing packages from the same repositories by default.

**Describe the solution you'd like**
My (perhaps incorrect) model of pipx is that it a) creates a venv for the app and b) installs the app into that venv with pip. As such, I'd expect pipx to honor pip.conf when installing packages. This way I don't have to treat pip and pipx differently; pipx will transparently "work like pip" for installation

I feel like this must have been discussed, but I couldn't see anything about it in the issues or docs. So I apologize if this is a rehash of an old topic. If this is actually known to be a bad idea, I'd be curious to know why.

**Describe alternatives you've considered**
There are of course ways to pass repo URLs to pipx, but this seems clumsy compared to simply having pipx work like pip.

**Comment by itsayellow** [comment]
This already happens, it just hasn't been explicitly documented.

Since internally pipx uses a subprocess and pip to install packages, any configuration for pip will apply to packages installed with pipx.  This includes environment variables and `pip.conf`.

**Comment by abingham** [comment]
*facepalm* I apologize for the noise. When I first tried `pipx install` I misspelled the package name, and I interpreted the resulting failure as pipx not finding my private repo. It does indeed work exactly as you say.

pipx is excellent. Thanks!.

**Comment by itsayellow** [comment]
No problem at all.  Issues like this help us know that perhaps there is something like pip configuration with pipx that we could be documenting better... 😄  Thanks for engaging, glad you like pipx.
