### ISSUE TITLE
Custom install dir for venvs

### ISSUE THREAD

**Issue by neutrinoceros** [pipxproject/pipx#685]
**How would this feature be useful?**
I'm working on a cluster which has _very_ strictly limited home directories (3MB). I have plenty of space available to install software, just not in my home dir. Using pipx to install only a couple of my own, extremely lightweight tools, is enough to exceed the quota.

**Describe the solution you'd like**
I'd like to be able to configure pipx somehow to change the installation directory to a custom location.
I guess an easy way would be through an env variable, though I have to say I'm not a fan, and I would very much prefer that pipx would store the variable itself and expose it via a CLI, for instance something like

```shell
pipx set install_dir=my/path
```

Note that a simpler solution would be to have pipx _ask_ for confirmation/custom value via a prompt at installation time.
While it means that the install dir can't be easily reconfigured after pipx is installed, it still solves my use case pretty well since I didn't get the luxury of installing many apps anyway, so reinstalling pipx itself is a decent option still.

**Describe alternatives you've considered**
Right now I don't know of any. I looked for a solution in your docs but couldn't find one, but I'd be happy to learn I simply missed something ?

**Comment by uranusjr** [comment]
Is `PIPX_HOME` what you want?

https://pipxproject.github.io/pipx/docs/

**Comment by neutrinoceros** [comment]
Yes, thank you very much !
