### ISSUE TITLE
Can pipx install packages which are managed via Poetry?

### ISSUE THREAD

**Issue by halloleo** [pipxproject/pipx#693]
I want to create a project via [Poetry](https://python-poetry.org).I plan to install my project later on the end user machines with pipx.

From my understanding Poetry creates  only a `pyproject.toml` file for package installation, not a `setup.py` file. However [pipx seems to expect `setup.py` only as install file](https://pipxproject.github.io/pipx/how-pipx-works/#developing-for-pipx). 

Therefore I would like to check:  Can pipx install packages which are managed just via the `pyproject.toml` file of Poetry?

**Comment by uranusjr** [comment]
Yes. The setup.py code is only an example; Poetry has its own entry points syntax, but pipx should pick it up correctly (via [PyPA’s interactivity specifications](https://packaging.python.org/specifications/)), as long as Poetry is packaging things properly.

**Comment by cs01** [comment]
The bottom of https://github.com/pipxproject/pipx#where-does-pipx-install-apps-from mentions how to set up a poetry project to work with pipx

**Comment by halloleo** [comment]
Thanks for all the information. Makes total sense.
