### ISSUE TITLE
Traceback when locale not set to UTF-8

### ISSUE THREAD

**Issue by pmav99** [pipxproject/pipx#73]
On a machine where the locale has not been set to UTF-8 you get tracebacks when installing/running pipx. E.g. when installing:
```
Traceback (most recent call last):
  File "get-pipx.py.1", line 287, in <module>
    main()
  File "get-pipx.py.1", line 283, in main
    print(f"Enjoy! {'\u2728 \U0001f31f \u2728' if not WINDOWS else ''}")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2728' in position 7: ordinal not in range(256)
```
Or when installing a package:
```
ipx install poetry
zsh: correct 'pipx' to 'popd' [nyae]? n
2nstalling package 'poetry'       
  installed package poetry 0.12.11, Python 3.6.7
  These binaries are now globally available
    - poetry
Traceback (most recent call last):
  File "/home/pmav2/.local/bin/pipx", line 10, in <module>
    sys.exit(cli())
  File "/home/pmav2/.local/pipx/venvs/pipx-app/lib/python3.6/site-packages/pipx/main.py", line 932, in cli
    run_pipx_command(args)
  File "/home/pmav2/.local/pipx/venvs/pipx-app/lib/python3.6/site-packages/pipx/main.py", line 642, in run_pipx_command
    force=args.force,
  File "/home/pmav2/.local/pipx/venvs/pipx-app/lib/python3.6/site-packages/pipx/main.py", line 505, in install
    print(f"done! {stars}")
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2728' in position 6: ordinal not in range(256)
```
Obviously, the problem is the special characters in the print statements. My guess is that you could check `sys.getdefaultencoding()` before you actually try to print them.

If you want to test this, on ubuntu you can set an "ansi" encoding with:
```
sudo update-locale LANG=en_US
```
and restore utf-8 with:
```
sudo update-locale LANG=en_US.UTF-8
```
You probably need to open a new terminal after each change though.

**Comment by Omnifarious** [comment]
I have the exact same issue. Except in my environment, `sys.stdout.encoding` ends up being `ANSI_X3.4-1968`, which is even worse than `latin-1` for what it will and won't successfully encode.

**Comment by tucked** [comment]
`ensurepath` too...
```
# python3 -m pipx ensurepath
Success! Added /root/.local/bin to the PATH environment variable.
Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

'ascii' codec can't encode character '\u2728' in position 83: ordinal not in range(128)
```
```
# LANG=en_US.utf8 python3 -m pipx ensurepath
Success! Added /root/.local/bin to the PATH environment variable.
Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

You likely need to open a new terminal or re-login for the changes to take effect. ✨ 🌟 ✨
```
`LC_ALL` works too
```
# LC_ALL=en_US.utf8 python3 -m pipx ensurepath
Success! Added /root/.local/bin to the PATH environment variable.
Consider adding shell completions for pipx. Run 'pipx completions' for instructions.

You likely need to open a new terminal or re-login for the changes to take effect. ✨ 🌟 ✨
```

**Comment by jsoutherland** [comment]
It looks like it's possible to avoid these issues by disabling emojis like this:

``USE_EMOJI=false python3 -m pipx ensurepath``

**Comment by itsayellow** [comment]
Looks like we need to disable emojis for non unicode locales?  Unless somebody knows a better way.

**Comment by itsayellow** [comment]
This https://stackoverflow.com/a/33378779 might be a good approach.

**Comment by itsayellow** [comment]
Well now I'm confused, because we actually check for `utf-8` encoding and disable emojis if the encoding is different.
https://github.com/pipxproject/pipx/blob/9bab569319040dafc414bad383ca294614b0dd92/src/pipx/constants.py#L54-L59

@tucked, @jsoutherland which version of pipx are you using?  (i.e. `pipx --version`)

**Comment by itsayellow** [comment]
@tucked, @jsoutherland and if you could, could you execute this in your shell and post the results:
```
python3 -c "import sys; print(sys.getdefaultencoding()); print(sys.stdout.encoding); print(sys.stderr.encoding)"
```

**Comment by itsayellow** [comment]
Ah ha!  I finally figured out how to both **generate** a new locale, and then use it to test.  This is my result:
```shell
> sudo locale-gen en_US
Generating locales (this might take a while)...
  en_US.ISO-8859-1... done
Generation complete.
> LANG=en_US python3 -c "import sys; print(sys.getdefaultencoding()); print(sys.stdout.encoding); print(sys.stderr.encoding)"
utf-8
iso8859-1
iso8859-1
```

The point being: `sys.getdefaultencoding()` is not the same as `sys.stdout.encoding` or `sys.stderr.encoding`.

So by checking `sys.getdefaultencoding()` we are not necessarily verifying that we can successfully print unicode characters.

**Comment by itsayellow** [comment]
I made an improved version of our emoji platform-checking code that hopefully fixes these issues.  Could somebody with emoji problems please test the pipx version in:
https://github.com/itsayellow/pipx/tree/unicode-check

e.g.
```
git clone --branch unicode-check https://github.com/itsayellow/pipx
```

**Comment by jsoutherland** [comment]
I'll give it a shot soon (tomorrow?). I'm having trouble replicating the environment this weekend that a co-worker was using.

**Comment by uranusjr** [comment]
> So by checking `sys.getdefaultencoding()` we are not necessarily verifying that we can successfully print unicode characters.

`sys.getdefaultencoding()` only affects the behaviour when you do `str.encode()` and `bytes.decode()` without the `encoding` argument (or has it set to `None`). IIRC it is a compile-time constant and is almost always set to `utf-8` these days (even on Windows). So it is mostly irralevent in this context.

**Comment by tucked** [comment]
Wow, pipx dev/build is wonky... figured it out eventually, though (I think), and @itsayellow's branch seems to resolve the issue!
```
$ LC_ALL= LANG= pipx ensurepath
/home/tucked/.local/bin is already in PATH.
/home/tucked/.local/bin is already in PATH.

All pipx binary directories have been added to PATH. If you are sure
you want to proceed, try again with the '--force' flag.

'ascii' codec can't encode character '\u2728' in position 31: ordinal not in range(128)
```
```
$ LC_ALL= LANG= python3 ~/projects/pipx/src/pipx ensurepath
/home/tucked/.local/bin is already in PATH.

All pipx binary directories have been added to PATH. If you are sure you want to proceed, try again with the '--force' flag.

Otherwise pipx is ready to go!
```

**Comment by itsayellow** [comment]
Glad it worked, thanks for testing @tucked.

What about the dev / build was confusing or frustrating?

**Comment by tucked** [comment]
> What about the dev / build was confusing or frustrating?

`pip install` does not seem to work on the repo (i.e. `pip install git+https://github.com/itsayellow/pipx.git@unicode-check#egg=pipx` or `pip install .` after cloning).

**Comment by itsayellow** [comment]
`pip install .` is basically how I (and I assume other devs) do their development, and it seems to work fine for me.

Did you have specific errors?  I'd be interested in another bug report if you have the time.

I do know that after installing into a venv I have to execute `hash -r` in my zsh in order to execute the newly-installed venv pipx as opposed to my system pipx.

**Comment by tucked** [comment]
I figured out the issue... `python3 -m venv` gives me a virtualenv with pip 9.0.1 (which doesn't understand PEP 517, at least) 🤦 
Everything works fine after I upgrade it. Sorry for the false alarm!

(I do still think running without installing is a bit odd, but I'll butt out until I exit the proverbial peanut gallery 😅)

**Comment by itsayellow** [comment]
Ah, that's good to know that `python3 -m pip --upgrade pip` is an essential step for people.

**Comment by uranusjr** [comment]
I filed #619 to mention a pip upgrade may be required to install pipx.
