### ISSUE TITLE
Update git packages with pipx upgrade-all

### ISSUE THREAD

**Issue by petobens** [pipxproject/pipx#75]
This might be a bit far fetched but imagine I've installed some package with `--spec git+https:.../some_branch/` and that package gets an update i.e a new commit in `some_branch`.
Can pipx pull those new changes upon `pipx upgrade`? (AFAICT it doesn't do this already).
Thanks!

**Comment by cs01** [comment]
It can do this already with something like this

```
pipx upgrade pipx-app --spec git+https://github.com/cs01/pipx@branch-name
```

**Comment by petobens** [comment]
Thanks for the quick reply. My real use case is that I want this to work with `pipx upgrade-all` which doesn't work at the time being right?

**Comment by cs01** [comment]
Correct, it won't work in that case.

**Comment by petobens** [comment]
Ok. If there are plans to implement something that will allow such behavior then we can leave this open; otherwise feel free to close. Thanks once again

**Comment by cs01** [comment]
I could add a file to the virtual env. Something like a `.pipxrc` with JSON that includes various keys, the "spec" being one of them. Then pipx could recognize and read that file, and re-use the same origin for all updates. 

If people like this idea I can add it. As always, feel free to vote with a thumbs up or provide an alternative suggestion to vote on.

**Comment by itsayellow** [comment]
I just did an upgrade-all, and unfortunately it overwrote one of my personal git-based pipx installs with one from pypi that is completely unrelated...  They just happened to have the same name.  In this case it was a pretty serious breakage.

**Comment by cs01** [comment]
@itsayellow ah so sorry to hear that. The `.pipxrc` file probably would have prevented that from happening, but I haven't gotten around to adding it.

**Comment by itsayellow** [comment]
thanks @cs01 , I was perplexed for a while at what was happening, but I'm ok now.  Just wanted to add another motivation for this issue.  Thanks for all your work on pipx.

**Comment by itsayellow** [comment]
This is fixed via #222, for cases where the package version number changes (the most reliable way to detect an upgrade is needed.)

**Comment by petobens** [comment]
Thank you! Is there going to be a release soon?

**Comment by cs01** [comment]
Yes, we're getting close
