### ISSUE TITLE
logo design

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#76]
Now that pipx has moved to its own [GitHub organization](https://github.com/pipxproject/), it’s time for a logo! Submissions welcome!

**Comment by IrishMorales** [comment]
Here's some based on the current logo, plus a cow mascot based on the "cowsay moo" example :)
Used: Raleway, OFL license

![pipx logo1](https://user-images.githubusercontent.com/42305156/52177987-a0d77b00-2803-11e9-82d1-98df39cef15b.png)
![pipx logo3](https://user-images.githubusercontent.com/42305156/52177991-a2a13e80-2803-11e9-9d37-81aa31cbf801.png)
![pipx logo4](https://user-images.githubusercontent.com/42305156/52178068-bbf6ba80-2804-11e9-8ba4-b5064abd0aaa.png)
![pipx logo2](https://user-images.githubusercontent.com/42305156/52177989-a208a800-2803-11e9-9251-89266717b97e.png)

**Comment by cs01** [comment]
Nice! I like the first one but maybe with a smaller “x”. Can you make a couple with a smaller x and I can see which one looks good?

**Comment by IrishMorales** [comment]
Thanks! 😄 Here are some alternate versions with the smaller "x":
![pipx logo1 4](https://user-images.githubusercontent.com/42305156/52516922-f382be00-2c6d-11e9-8260-20e05e91fc2b.png)
![pipx logo1 1](https://user-images.githubusercontent.com/42305156/52516919-f2ea2780-2c6d-11e9-90f0-eaf5ae572dd5.png)
![pipx logo1 3](https://user-images.githubusercontent.com/42305156/52516921-f382be00-2c6d-11e9-8ac5-fcae26eac4af.png)
![pipx logo1 2](https://user-images.githubusercontent.com/42305156/52516920-f2ea2780-2c6d-11e9-82fa-e450e5841508.png)

**Comment by mirzazulfan** [comment]
Hi @cs01 what about this logo?
![xpip](https://user-images.githubusercontent.com/36124339/55212186-609fe200-5221-11e9-8449-6e9aa61f5f01.png)

**Comment by cs01** [comment]
The logo has been updated on the homepage and docs. Thanks!

**Comment by sisp** [comment]
@IrishMorales Do you have a vector image version of the logo? I'd be interested in adding a monochromatic variant of it to https://simpleicons.org.

**Comment by dukecat0** [comment]
@sisp The vector image version is available now: https://github.com/pypa/pipx/blob/main/logo.svg

**Comment by dukecat0** [comment]
@sisp Thanks for your work! This one looks good to me. 👍

**Comment by sisp** [comment]
@dukecat0 See https://github.com/simple-icons/simple-icons/pull/10072 my PR over at Simple Icons.
