### ISSUE TITLE
Things install fine but I get warning "Cache entry deserialization failed, entry ignored"

### ISSUE THREAD

**Issue by halloleo** [pipxproject/pipx#77]
Just started using `pipx`. Packages install fine, but I get *always* the following warning on the console: 

    Cache entry deserialization failed, entry ignored

This happens on Centos 6 with Python 3.6.4.

**Comment by halloleo** [comment]
Thanks @cs01. 

How can I specify in `pipx` not to use the cache? Can I even put this somehow in a config file to persist it?

**Comment by cs01** [comment]
With the latest version, `--no-cache-dir` should work for you
```
pipx install --pip-args="--no-cache-dir" PACKAGE
```
At this time there is no config to persist this argument.

**Comment by brightmaraba** [comment]
Upgrade Pip using  curl https://bootstrap.pypa.io/get-pip.py | python3
