### ISSUE TITLE
migrate back from `pipx-app` to `pipx`

### ISSUE THREAD

**Issue by cs01** [pipxproject/pipx#82]
Thanks to @ncolgan, the pipx owner will be transferring ownership of the pipx PyPI package name to me (see https://github.com/khalti/pipx/issues/2).

Update all installation instructions and docs, and also look into getting rid of `pipx-bootstrap` altogether so that `pip install pipx` "just works".

**Comment by cs01** [comment]
The name change is complete!

If you're looking to switch from `pipx-app` to `pipx` you can do the following. Note that if you ran `pipx inject` on any packages, the injected packages will be lost in this process.

```
pipx uninstall pipx-app  # uninstall pipx-app
pip install --user pipx  # install pipx to site-packages
pipx upgrade-all python3  # pipx will look to the same venv locations as pipx-app, and will be recognize all packages already installed
```

**Comment by kadrach** [comment]
```
pipx uninstall pipx-app
pip install --user pipx
% pipx                                                         
Traceback (most recent call last):
  File "/home/neckerskorn/.local/bin/pipx", line 7, in <module>
    from pipx.main import cli
ModuleNotFoundError: No module named 'pipx'
% pip list                                                                  
Package    Version
---------- --------
pip        19.0.1
pipx       0.12.0.4
setuptools 40.6.2
virtualenv 16.3.0
You are using pip version 19.0.1, however version 19.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
😢

**Comment by kadrach** [comment]
Probably some virtualenv confusion. Installing pipx from scratch worked.

**Comment by apollo13** [comment]
Just upgraded back to `pipx`. `pipx list` then failed but `reinstall-all` fixed it! :+1:
