### ISSUE TITLE
Dependency re-use or application "groups"

### ISSUE THREAD

**Issue by kadrach** [pipxproject/pipx#83]
I work within the AWS ecosystem quite a bit, which leads to me having a myriad different tools installed that each require botocore (~40MB), leading to lots of space taken up by multiple copies of dependencies.

It would be cool to re-use existing "installed" dependencies across multiple venvs (installing each package individually, having each pipx environment's site-packages just be symlinks?).

Perhaps pipx can allow creation of "grouped" applications? `inject` also exposing injected binaries. (This can cause dependency version issues but is probably the way most people `pip install` a bunch of tools in succession?)

**Comment by psafont** [comment]
At that point it might be worth installing botocore with `pip install --user` and enabling site-packages when installing the tools (`pipx install --system-site-packages <package>`)

**Comment by kadrach** [comment]
That's certainly the next best option, but means I'm managing a separate layer of venvs in between my "actual" python interpreter and pipx :(

**Comment by cs01** [comment]
What you described sounds like yarn pnp where symlinks are created to existing packages.  This is a good, logical idea, but it fear it will add a lot of complexity to pipx.  Ideally that would be something pip could do in the future (install all packages to a global cache with hashes, then create symlinks to “site-packages”).

Did you have any different implementation ideas?

**Comment by apollo13** [comment]
> `inject` also exposing injected binaries. (This can cause dependency version issues but is probably the way most people `pip install` a bunch of tools in succession?)

I think this would be a nice addition. For instance with my ansible workflows I have ansible installed via pipx and now I'd want to add molecule for testing -- preferably in the same environment because then molecule and ansible would share the same plugins etc…

**Comment by kadrach** [comment]
@cs01 Yeah that's basically what I had in mind (didn't get as far as hashing, I'm not across how it's done in the yarn ecosystem). 

Agree that this will add a lot of complexity. Native support in pip would obviously be great :)

While pip still does not have a dependency resolver, I believe a lot of work has happened in that space over the past year, for both poetry and pipenv.

**Comment by cs01** [comment]
> inject also exposing injected binaries. 

This has been added to pipx:

```
pipx inject PACKAGE --include-apps
```
