### ISSUE TITLE
reinstall is ignoring spec

### ISSUE THREAD

**Issue by schlamar** [pipxproject/pipx#87]
Reinstall is just using the name as package name. But if the venv name is not usable (e.g. `pipx install nonexistingpackage --spec "flake8==2.0.0"`) or if you installed a pinned version, this information is lost and reinstall is either not working (for the former) or is installing the wrong version (for the latter).

You should store spec information in a config file and use that on reinstall.

**Comment by schlamar** [comment]
Oh, it's ignoring the base python as well. This should be in the config, too.

**Comment by itsayellow** [comment]
Fixed by #222.
