### ISSUE TITLE
pipx not listing itself?

### ISSUE THREAD

**Issue by joshsleeper** [pipxproject/pipx#92]
ubuntu `18.10`, fully patched
python `3.6.7`
pipx `0.12.0.4`

---

`pipx-app` used to list itself with `pipx list`, but with some recent changes that appears to be busted... unless it only ever worked by accident of course!

`pipx` was installed as suggested, using...

```sh
python3 -m pip install --user pipx
```

`pipx list` results, with `pipx` itself dubiously MIA
```sh
$ pipx list
venvs are in /home/username/.local/pipx/venvs
symlinks to binaries are in /home/username/.local/bin
   package black 18.9b0, Python 3.6.7
    - black
    - blackd
   package pipenv 2018.11.26, Python 3.6.7
    - pipenv
    - pipenv-resolver
```

**Comment by cs01** [comment]
The (deprecated) `pipx-app` installation instruction method installed it to a `pipx`-compatible location such that it was managed by pipx (and thus `pipx list` would show it).

New installation instructions for `pipx` just use `pip` for installing, upgrading, and uninstalling `pipx`. So the behavior you are observing is as expected.

If you liked having pipx manage pipx you can still do the follwing
```
pip install --user pipx  # installs to site-packages
pipx install pipx  # installs to /Users/cssmith/.local/pipx/venvs/pipx and /Users/cssmith/.local/bin/pipx
pip uninstall pipx  # removes from site-packages
```

It is a little mind-bendy, but it works! 😄

**Comment by joshsleeper** [comment]
Ahh, good to know!
Thanks for clarifying mate, I'm happy to update it with `pip` as long as that's the expected way to do it!
